/* ============================================================================
 * boot_splash.c -- Persistent boot splash screen (Windows 11-style)
 *
 * Displays:
 *   1. Black background
 *   2. Centered icon at ~38% vertical
 *   3. Progressive arc spinner (Fluent 2 breathing ring)
 *   4. Status text below spinner
 *
 * The splash owns the framebuffer from boot_splash_init() until
 * boot_splash_finish(). During this time, fb_putchar is locked so
 * printk output goes only to serial.
 *
 * Animation is driven by the unified timer tick callback (PIT backend on
 * TCG, LAPIC elsewhere) at divisor 10 (~10fps at 100Hz), registered by
 * spinner_start() in spinner.c, which rotates and breathes a dynamic arc
 * ring continuously even during blocking I/O.
 * ============================================================================ */

#include "kernel/boot_splash.h"
#include "kernel/boot_info.h"
#include "kernel/drivers/framebuffer.h"
#include "kernel/timer.h"
#include "kernel/types.h"
#include "kernel/klog.h"
#include "kernel/spinner.h"
#include "kernel/gfx/arc_ring.h"

/* Embedded icon pixel data (generated by tools/convert_icon.py) */
#include <kernel/os_logo.h>

/* Boot splash TTF font API (implemented in gfx_text.c with SSE2) */
extern int boot_font_init(int pixel_size);
extern int boot_font_measure(const char *text);
extern void boot_font_render(const char *text, int32_t x, int32_t y, uint32_t color);

/* ---- Layout constants ----
 * All pixel values are computed at runtime from the detected resolution. */
#define ICON_Y_PCT      38      /* icon center at 38% vertical height */

/* Default spinner accent color: Fluent Blue (#0078D4) */
#define SPINNER_ACCENT_COLOR  0x000078D4

/* ---- State ---- */
static volatile uint8_t  splash_on;
static volatile uint8_t  debug_mode; /* 1 when splash aborted by DEBUG flag */
static uint8_t  ttf_ready;         /* 1 once boot_font_init succeeds */
static uint32_t scr_w, scr_h;
static uint32_t icon_x, icon_y;    /* top-left of icon */
static uint32_t icon_size;         /* pixel size of selected prebuilt logo */
static const unsigned int *icon_pixels; /* pointer to selected logo array */
static uint32_t spinner_cx, spinner_cy; /* center of spinner ring */
static uint32_t text_y;            /* top of status text */
static uint32_t diag_y;            /* top of diagnostic line (below status) */

/* HiDPI scale factor (1, 2, or 3) -- computed in boot_splash_init() */
static uint32_t g_scale;

/* Scaled layout values -- all computed in boot_splash_init() */
static uint32_t g_spinner_y_offset; /* spinner center below icon bottom */
static uint32_t g_text_y_offset;   /* text below spinner center */
static uint32_t g_text_area_w;     /* width of status text clear area */
static uint32_t g_font_size;       /* TTF pixel size */

/* ---- Framebuffer helpers (direct to back buffer) ---- */

static void splash_fill_rect(uint32_t x, uint32_t y,
                              uint32_t w, uint32_t h, uint32_t color)
{
    for (uint32_t py = y; py < y + h && py < scr_h; py++)
        for (uint32_t px = x; px < x + w && px < scr_w; px++)
            fb_put_pixel(px, py, color);
}



/* Draw the icon with alpha-blending, optionally dimmed by fade/255.
 * Pixel-perfect 1:1 blit from the prebuilt native-size logo array. */
static void splash_draw_icon_faded(uint8_t fade)
{
    for (uint32_t dy = 0; dy < icon_size; dy++) {
        for (uint32_t dx = 0; dx < icon_size; dx++) {
            uint32_t pixel = icon_pixels[dy * icon_size + dx];
            uint8_t a = (uint8_t)(pixel >> 24);
            if (a == 0) continue;

            uint32_t sx = icon_x + dx;
            uint32_t sy = icon_y + dy;
            if (sx >= scr_w || sy >= scr_h) continue;

            uint8_t b = (uint8_t)((pixel & 0xFF)         * a / 255 * fade / 255);
            uint8_t g = (uint8_t)(((pixel >> 8)  & 0xFF) * a / 255 * fade / 255);
            uint8_t r = (uint8_t)(((pixel >> 16) & 0xFF) * a / 255 * fade / 255);
            fb_put_pixel(sx, sy,
                (uint32_t)b | ((uint32_t)g << 8) | ((uint32_t)r << 16));
        }
    }
}

/* Draw a status string centered horizontally at text_y using the TTF font.
 * Falls back to no-op if TTF is not yet initialized. */
static void splash_draw_text(const char *text, uint32_t color)
{
    /* Clear text area */
    uint32_t area_x = (scr_w > g_text_area_w) ? (scr_w - g_text_area_w) / 2 : 0;
    uint32_t text_h = g_font_size + 8;  /* conservative height */
    splash_fill_rect(area_x, text_y, g_text_area_w, text_h, 0x000000);

    if (!ttf_ready) return;

    int32_t tw = boot_font_measure(text);
    int32_t sx = (int32_t)(scr_w - (uint32_t)tw) / 2;
    boot_font_render(text, sx, (int32_t)text_y, color);
}



/* ============================================================================
 * Public API
 * ============================================================================ */

void boot_splash_init(void)
{
    /* postbars=diag (2): the Tier 1 VPD diagnostic layout is authoritative for
     * the whole boot. Suppress the splash artwork entirely (no black-wipe, no
     * icon/spinner/fade) so the VPD bars stay on screen. splash_on remains 0,
     * so every boot_splash_* call becomes a no-op, and the caller also skips
     * vpd_stop_tier1() in this mode so Tier 1 keeps rendering.
     *
     * Still take ownership of the display like the normal path does: stop
     * screen klog (LOG_FATAL) and lock the compositor BEFORE returning, so
     * later boot INFO/WARN logs cannot route through fb_putchar -> fb_swap and
     * flip a stale back buffer over the raw-VRAM VPD. The compositor's first
     * frame unlocks itself (compositor.c) so the desktop still comes up. Log
     * the diag message only AFTER suppression so it is serial-only (no swap). */
    if (g_boot_info.config.config_found && g_boot_info.config.postbars == 2) {
        klog_set_screen_level(LOG_FATAL);
        fb_lock_compositor();
        klog(LOG_INFO, "SPLASH", "postbars=diag: splash suppressed, VPD Tier 1 authoritative");
        return;
    }

    scr_w = fb_get_width();
    scr_h = fb_get_height();

    if (scr_w == 0 || scr_h == 0) return;

    /* ---- HiDPI scale factor (for boot_info / desktop use) -------------
     * Integer scale: 1× ≤1080p,  2× ≤2160p,  3× >2160p. */
    g_scale = (scr_h > 2160) ? 3 : (scr_h > 1080) ? 2 : 1;

    /* ---- Icon: pick exact prebuilt size -- no runtime scaling ----------- */
    icon_size   = OS_LOGO_SIZE_FOR_HEIGHT(scr_h);
    icon_pixels = OS_LOGO_FOR_HEIGHT(scr_h);

    /* ---- Spinner geometry (replaces dot geometry) ----------------------
     * Ring radius/stroke scale with screen height.
     * Font size is decoupled -- proportional to screen height. */
    struct arc_ring_size ring = arc_ring_size_for_height(scr_h);
    g_spinner_y_offset = icon_size * 58 / 100;     /* same as old DOT_Y_OFFSET */
    g_text_y_offset    = (uint32_t)ring.radius + 20; /* text below spinner */
    g_text_area_w      = icon_size * 56 / 10;      /* ~716px @ 128px icon */

    /* Font size: fixed tiers per resolution -- small enough for fast TTF init */
    if      (scr_h >= 2160) g_font_size = 36;
    else if (scr_h >= 1440) g_font_size = 26;
    else if (scr_h >= 1080) g_font_size = 20;
    else                    g_font_size = 18;

    /* Minimum guard for very small displays */
    if (g_text_area_w < 400)   g_text_area_w = 400;

    klog(LOG_DEBUG, "SPLASH",
         "%ux%u  scale=%ux  icon=%upx  font=%upx  ring_r=%d  ring_s=%d",
         scr_w, scr_h, g_scale, icon_size, g_font_size,
         ring.radius, ring.stroke);

    /* ---- Compute layout positions ------------------------------------- */
    uint32_t icon_center_y = scr_h * ICON_Y_PCT / 100;
    icon_x = (scr_w - icon_size) / 2;
    icon_y = icon_center_y - icon_size / 2;

    spinner_cx = scr_w / 2;
    spinner_cy = icon_y + icon_size + g_spinner_y_offset;

    text_y = spinner_cy + g_text_y_offset;
    diag_y = text_y + g_font_size + 8;   /* diagnostic line below status */

    /* ---- Initialize spinner (does NOT start animation yet) ------------ */
    spinner_init((int32_t)spinner_cx, (int32_t)spinner_cy,
                 ring.radius, ring.stroke, SPINNER_ACCENT_COLOR);

    /* Suppress klog and lock compositor FIRST, before any slow init. */
    klog_set_screen_level(LOG_FATAL);
    fb_lock_compositor();
    splash_on = 1;

    /* Push a clean black frame immediately to replace UEFI/VRAM content. */
    splash_fill_rect(0, 0, scr_w, scr_h, 0x000000);
    fb_swap();

    /* Try to init TTF font at scaled size. */
    ttf_ready = 0;
    if (boot_font_init((int)g_font_size) == 0)
        ttf_ready = 1;

    /* ---- Fade-in: 5 frames × 100ms = 500ms total ----
     * Text is included from frame 1 onwards so it appears 200ms in,
     * not after the entire fade completes. The fill_rect black-wipe
     * at the start of each frame clears everything, so text must be
     * re-drawn after icon + spinner in every frame where it's wanted. */
    static const uint8_t fade_levels[5] = { 51, 102, 153, 204, 255 };
    for (int fi = 0; fi < 5; fi++) {
        splash_fill_rect(0, 0, scr_w, scr_h, 0x000000);
        splash_draw_icon_faded(fade_levels[fi]);
        spinner_draw_faded(fade_levels[fi]);
        if (fi >= 1 && ttf_ready)
            splash_draw_text("Starting...", 0x00AAAAAA);
        fb_swap();
        sleep_ms(100);
    }
}

/* Called from main.c after timer_hal_init() + sti to start animation */
void boot_splash_start_animation(void)
{
    if (!splash_on) return;
    spinner_start();
}

void boot_splash_status(const char *msg)
{
    if (!splash_on) {
        /* Debug mode: print status to screen via printk (only after
         * explicit abort, not during early boot before splash init) */
        if (debug_mode && msg && msg[0]) {
            extern void printk(const char *fmt, ...);
            printk("[BOOT] %s\n", msg);
        }
        return;
    }

    splash_draw_text(msg, 0x00AAAAAA);
    uint32_t area_x = (scr_w > g_text_area_w) ? (scr_w - g_text_area_w) / 2 : 0;
    uint32_t text_h = g_font_size + 8;
    fb_swap_rect(area_x, text_y, g_text_area_w, text_h);
}

void boot_splash_diag(const char *msg)
{
    if (!splash_on) return;

    uint32_t area_x = (scr_w > g_text_area_w) ? (scr_w - g_text_area_w) / 2 : 0;
    uint32_t dh = g_font_size + 8;
    splash_fill_rect(area_x, diag_y, g_text_area_w, dh, 0x000000);

    if (ttf_ready && msg && msg[0]) {
        int32_t tw = boot_font_measure(msg);
        int32_t sx = (int32_t)(scr_w - (uint32_t)tw) / 2;
        boot_font_render(msg, sx, (int32_t)diag_y, 0x00888888);
    }

    fb_swap_rect(area_x, diag_y, g_text_area_w, dh);
}

void boot_splash_delay(uint32_t seconds)
{
    if (!splash_on || seconds == 0) return;

    /* Sleep in 50ms steps, advancing the spinner each step */
    uint32_t steps = seconds * 20;
    for (uint32_t i = 0; i < steps; i++) {
        sleep_ms(50);
        spinner_advance();
    }
}

void boot_splash_tick(void)
{
    if (!splash_on) return;
    spinner_advance();  /* advance one animation frame */
}

void boot_splash_finish(void)
{
    if (!splash_on) return;

    /* Stop spinner animation */
    spinner_stop();

    splash_on = 0;

    /* ---- Fade-out: 5 frames × 67ms ≈ 330ms total ----
     * Dim splash to black before handing off to the desktop compositor.
     * timer_hal_init() provides g_system_timer so sleep_ms() works correctly. */
    static const uint8_t fade_out[5] = { 204, 153, 102, 51, 0 };
    for (int fi = 0; fi < 5; fi++) {
        if (fade_out[fi] > 0) {
            splash_fill_rect(0, 0, scr_w, scr_h, 0x000000);
            splash_draw_icon_faded(fade_out[fi]);
            spinner_draw_faded(fade_out[fi]);
        } else {
            splash_fill_rect(0, 0, scr_w, scr_h, 0x000000);
        }
        fb_swap();
        sleep_ms(67);
    }

    /* NOTE: compositor remains LOCKED after this function returns.
     * fb_unlock_compositor() is called from main.c's first-frame compositor
     * path, after wm_composite() has painted the full desktop.  Unlocking
     * here would let printk() write to the screen during window creation,
     * producing the "[OK] Heap / Terminal / Gallery" bleed-through. */
}

int boot_splash_active(void)
{
    return splash_on;
}

int boot_splash_text_ready(void)
{
    /* STRICTER than boot_splash_active(), and the difference is load-bearing
     * for any caller that must know its message was actually SEEN.
     * boot_splash_init() sets splash_on BEFORE attempting boot_font_init(),
     * so a font or PMM failure leaves splash_on = 1 with ttf_ready = 0 --
     * and boot_splash_status() then clears the text area and renders
     * nothing. A caller checking only splash_on would conclude it had shown
     * a message no operator can see. */
    return splash_on && ttf_ready;
}

void boot_splash_abort(void)
{
    if (!splash_on) return;
    spinner_stop();
    splash_on = 0;
    debug_mode = 1;
    /* Clear to black and unlock framebuffer for printk */
    splash_fill_rect(0, 0, scr_w, scr_h, 0x000000);
    fb_swap();
    fb_unlock_compositor();
}
