/* ============================================================================
 * boot_splash_font.h — Embedded TTF font for boot splash text
 *
 * Contains:
 *   - boot_font_data[]: raw Selawik Regular TTF bytes (44 KB)
 *   - boot_font_init(): initialize stb_truetype for the embedded font
 *   - boot_font_measure(): measure text width in pixels
 *   - boot_font_render(): render anti-aliased text to framebuffer
 *
 * The implementation lives in gfx_text.c (compiled with SSE2).
 * boot_splash.c includes this header for declarations only.
 * ============================================================================ */

#pragma once

#include "kernel/types.h"

/* Embedded font data (generated by tools/convert_boot_font.py) */
#include "boot_splash_font_data.h"

/* Initialize the boot splash font at the given pixel size.
 * Must be called after fb_init() and simd_init().
 * Returns 0 on success, -1 on failure. */
int boot_font_init(int pixel_size);

/* Measure the width of a text string in pixels. */
int boot_font_measure(const char *text);

/* Render anti-aliased text directly to the framebuffer back buffer.
 * color is 0x00RRGGBB format. */
void boot_font_render(const char *text, int32_t x, int32_t y, uint32_t color);
