/* ============================================================================
 * boot_splash.c — Persistent boot splash screen (Windows 11-style)
 *
 * Displays:
 *   1. Black background
 *   2. Centered 48×48 icon at ~40% vertical
 *   3. Animated horizontal dots (5 dots, pulse wave)
 *   4. Status text below dots
 *
 * The splash owns the framebuffer from boot_splash_init() until
 * boot_splash_finish(). During this time, fb_putchar is locked so
 * printk output goes only to serial.
 *
 * Animation is driven by the PIT timer interrupt at ~14 fps,
 * so dots animate continuously even during blocking I/O.
 * ============================================================================ */

#include "kernel/boot_splash.h"
#include "kernel/drivers/framebuffer.h"
#include "kernel/drivers/pit.h"
#include "kernel/types.h"
#include "kernel/klog.h"

/* Embedded icon pixel data (generated by tools/convert_icon.py) */
#include <kernel/os_logo.h>

/* Boot splash TTF font API (implemented in gfx_text.c with SSE2) */
extern int boot_font_init(int pixel_size);
extern int boot_font_measure(const char *text);
extern void boot_font_render(const char *text, int32_t x, int32_t y, uint32_t color);

/* ---- Layout constants (scale-independent proportional offsets) ----
 * All pixel values are computed at runtime from the detected resolution.
 * Base constants below are for 720p (scale=1×). Multiply by `g_scale`. */
#define ICON_Y_PCT      38      /* icon center at 38% vertical height */
/* DOT_Y_OFFSET, TEXT_Y_OFFSET, font size, dot radii, spacing,
 * and icon render size are all computed in boot_splash_init(). */

#define NUM_DOTS        6

/* Animation: each dot cycles through 16 frames of pulse */
#define PULSE_FRAMES    16

/* PIT callback rate: every 10 ticks at 100 Hz = 10 fps */
#define ANIM_TICK_DIVISOR 10

/* ---- State ---- */
static volatile uint8_t  splash_on;
static uint8_t  ttf_ready;         /* 1 once boot_font_init succeeds */
static uint32_t scr_w, scr_h;
static uint32_t icon_x, icon_y;    /* top-left of icon */
static uint32_t icon_size;         /* pixel size of selected prebuilt logo */
static const unsigned int *icon_pixels; /* pointer to selected logo array */
static uint32_t dot_cx, dot_cy;    /* center of dot row */
static uint32_t text_y;            /* top of status text */
static volatile uint32_t anim_frame;

/* HiDPI scale factor (1, 2, or 3) — computed in boot_splash_init() */
static uint32_t g_scale;

/* Scaled layout values — all computed in boot_splash_init() */
static int32_t g_dot_min_r;        /* resting dot radius */
static int32_t g_dot_max_r;        /* active (peak) dot radius */
static uint32_t g_dot_spacing;     /* px between dot centers */
static uint32_t g_dot_y_offset;    /* dots below icon bottom */
static uint32_t g_text_y_offset;   /* text below dot center */
static uint32_t g_text_area_w;     /* width of status text clear area */
static uint32_t g_font_size;       /* TTF pixel size */

/* ---- Framebuffer helpers (direct to back buffer) ---- */

static void splash_fill_rect(uint32_t x, uint32_t y,
                              uint32_t w, uint32_t h, uint32_t color)
{
    for (uint32_t py = y; py < y + h && py < scr_h; py++)
        for (uint32_t px = x; px < x + w && px < scr_w; px++)
            fb_put_pixel(px, py, color);
}

/* Draw a filled circle with smooth anti-aliased edge.
 * Uses distance-squared comparison with a 2px-wide blend zone. */
static void splash_draw_dot(int32_t cx, int32_t cy, int32_t r, uint32_t color)
{
    uint8_t cr = (uint8_t)(color >> 16);
    uint8_t cg = (uint8_t)(color >> 8);
    uint8_t cb = (uint8_t)(color);
    int32_t ro = r + 2;  /* outer bound including AA fringe */

    /* Precompute thresholds */
    int32_t r_inner_sq = (r - 1) * (r - 1);  /* fully opaque inside this */
    int32_t r_outer_sq = (r + 1) * (r + 1);  /* fully transparent outside this */

    for (int32_t y = -ro; y <= ro; y++) {
        int32_t py = cy + y;
        if (py < 0 || (uint32_t)py >= scr_h) continue;

        for (int32_t x = -ro; x <= ro; x++) {
            int32_t px = cx + x;
            if (px < 0 || (uint32_t)px >= scr_w) continue;

            int32_t d2 = x * x + y * y;

            if (d2 <= r_inner_sq) {
                /* Fully inside — opaque */
                fb_put_pixel((uint32_t)px, (uint32_t)py, color | 0xFF000000);
            } else if (d2 <= r_outer_sq) {
                /* AA fringe zone: smooth falloff from r-1 to r+1 */
                /* Alpha = 255 * (r+1 - sqrt(d2)) / 2
                 * Approximate: alpha = 255 * (r_outer_sq - d2) / (r_outer_sq - r_inner_sq) */
                int32_t range = r_outer_sq - r_inner_sq;
                int32_t frac = r_outer_sq - d2;
                uint32_t alpha = (uint32_t)(frac * 255 / range);
                if (alpha > 255) alpha = 255;
                if (alpha < 10) continue;

                /* Blend onto black background (simple scale) */
                uint8_t ob = (uint8_t)((cb * alpha) / 255);
                uint8_t og = (uint8_t)((cg * alpha) / 255);
                uint8_t or_ = (uint8_t)((cr * alpha) / 255);
                fb_put_pixel((uint32_t)px, (uint32_t)py,
                    (uint32_t)ob | ((uint32_t)og << 8) | ((uint32_t)or_ << 16));
            }
        }
    }
}

/* Draw the icon with alpha-blending, optionally dimmed by fade/255.
 * Pixel-perfect 1:1 blit from the prebuilt native-size logo array. */
static void splash_draw_icon_faded(uint8_t fade)
{
    for (uint32_t dy = 0; dy < icon_size; dy++) {
        for (uint32_t dx = 0; dx < icon_size; dx++) {
            uint32_t pixel = icon_pixels[dy * icon_size + dx];
            uint8_t a = (uint8_t)(pixel >> 24);
            if (a == 0) continue;

            uint32_t sx = icon_x + dx;
            uint32_t sy = icon_y + dy;
            if (sx >= scr_w || sy >= scr_h) continue;

            uint8_t b = (uint8_t)((pixel & 0xFF)         * a / 255 * fade / 255);
            uint8_t g = (uint8_t)(((pixel >> 8)  & 0xFF) * a / 255 * fade / 255);
            uint8_t r = (uint8_t)(((pixel >> 16) & 0xFF) * a / 255 * fade / 255);
            fb_put_pixel(sx, sy,
                (uint32_t)b | ((uint32_t)g << 8) | ((uint32_t)r << 16));
        }
    }
}

/* Draw a status string centered horizontally at text_y using the TTF font.
 * Falls back to no-op if TTF is not yet initialized. */
static void splash_draw_text(const char *text, uint32_t color)
{
    /* Clear text area */
    uint32_t area_x = (scr_w > g_text_area_w) ? (scr_w - g_text_area_w) / 2 : 0;
    uint32_t text_h = g_font_size + 8;  /* conservative height */
    splash_fill_rect(area_x, text_y, g_text_area_w, text_h, 0x000000);

    if (!ttf_ready) return;

    int32_t tw = boot_font_measure(text);
    int32_t sx = (int32_t)(scr_w - (uint32_t)tw) / 2;
    boot_font_render(text, sx, (int32_t)text_y, color);
}

/* Draw the 5 horizontal dots with a smooth wave animation.
 *
 * Each dot has a pulse window of PULSE_LEN frames (grow → peak → shrink).
 * Consecutive dots are staggered by STAGGER frames, so the next dot
 * starts growing WHILE the previous one is still shrinking.
 * This overlap creates the smooth "wave" effect seen in Windows 11. */
#define PULSE_LEN   8   /* frames for one dot's full grow→peak→shrink */
#define STAGGER     2   /* frames offset between consecutive dots (starts: 0,2,4,6,8) */
/* Total cycle: last dot finishes PULSE_LEN frames after it starts,
 * which is at (NUM_DOTS-1)*STAGGER + PULSE_LEN.
 * Add a small rest gap before the wave restarts. */
#define REST_GAP    0   /* no gap — wave wraps seamlessly */
#define TOTAL_CYCLE ((NUM_DOTS - 1) * STAGGER + PULSE_LEN + REST_GAP)

/* Smooth pulse curve: maps phase (0..PULSE_LEN-1) to intensity (0..4).
 * Shape: ramp up → hold peak → ramp down.
 *   phase: 0  1  2  3  4  5  6  7
 *   value: 0  2  4  4  4  2  1  0  */
static const int32_t pulse_curve[8] = { 0, 2, 4, 4, 4, 2, 1, 0 };

static void splash_draw_dots(void)
{
    /* Clear dot area */
    uint32_t area_w = NUM_DOTS * g_dot_spacing + (uint32_t)g_dot_max_r * 2 + 8;
    uint32_t area_x = dot_cx - area_w / 2;
    uint32_t area_h = (uint32_t)g_dot_max_r * 2 + 8;
    uint32_t area_y = dot_cy - (uint32_t)g_dot_max_r - 4;
    splash_fill_rect(area_x, area_y, area_w, area_h, 0x000000);

    uint32_t frame = anim_frame;
    uint32_t cycle_pos = frame % TOTAL_CYCLE;

    for (uint32_t i = 0; i < NUM_DOTS; i++) {
        int32_t x = (int32_t)dot_cx
                   + (int32_t)(i * g_dot_spacing)
                   - (int32_t)((NUM_DOTS - 1) * g_dot_spacing / 2);
        int32_t y = (int32_t)dot_cy;

        /* This dot's phase within the wave */
        int32_t dot_start = (int32_t)i * STAGGER;
        int32_t phase = (int32_t)cycle_pos - dot_start;

        int32_t intensity = 0;  /* 0 = resting */
        if (phase >= 0 && phase < PULSE_LEN) {
            intensity = pulse_curve[phase];
        }

        /* Map intensity (0..4) to radius and brightness */
        int32_t r = g_dot_min_r + (g_dot_max_r - g_dot_min_r) * intensity / 4;
        uint32_t brightness;
        if (intensity == 0)      brightness = 0x44;  /* resting */
        else if (intensity == 1) brightness = 0x77;
        else if (intensity == 2) brightness = 0xAA;
        else if (intensity == 3) brightness = 0xDD;
        else                     brightness = 0xFF;  /* peak */

        uint32_t color = (brightness << 16) | (brightness << 8) | brightness;
        splash_draw_dot(x, y, r, color);
    }
}

/* Like splash_draw_dots() but scales dot brightness by fade/255.
 * Clears the dot area first before drawing — same as the normal variant. */
static void splash_draw_dots_faded(uint8_t fade)
{
    /* Clear dot area */
    uint32_t area_w = NUM_DOTS * g_dot_spacing + (uint32_t)g_dot_max_r * 2 + 8;
    uint32_t area_x = dot_cx - area_w / 2;
    uint32_t area_h = (uint32_t)g_dot_max_r * 2 + 8;
    uint32_t area_y = dot_cy - (uint32_t)g_dot_max_r - 4;
    splash_fill_rect(area_x, area_y, area_w, area_h, 0x000000);

    uint32_t cycle_pos = 0;   /* all dots at rest — no animation yet */

    for (uint32_t i = 0; i < NUM_DOTS; i++) {
        int32_t x = (int32_t)dot_cx
                   + (int32_t)(i * g_dot_spacing)
                   - (int32_t)((NUM_DOTS - 1) * g_dot_spacing / 2);
        int32_t y = (int32_t)dot_cy;

        int32_t dot_start = (int32_t)i * STAGGER;
        int32_t phase = (int32_t)cycle_pos - dot_start;
        int32_t intensity = (phase >= 0 && phase < PULSE_LEN) ?
                             pulse_curve[phase] : 0;

        int32_t r = g_dot_min_r + (g_dot_max_r - g_dot_min_r) * intensity / 4;
        uint32_t brightness;
        if      (intensity == 0) brightness = 0x44;
        else if (intensity == 1) brightness = 0x77;
        else if (intensity == 2) brightness = 0xAA;
        else if (intensity == 3) brightness = 0xDD;
        else                     brightness = 0xFF;

        /* Dim by fade factor */
        brightness = (brightness * (uint32_t)fade) / 255;
        uint32_t color = (brightness << 16) | (brightness << 8) | brightness;
        splash_draw_dot(x, y, r, color);
    }
}

/* PIT callback: area swap uses scaled g_dot_* values */
static void splash_timer_callback(void)
{
    if (!splash_on) return;

    anim_frame++;
    splash_draw_dots();

    uint32_t area_w = NUM_DOTS * g_dot_spacing + (uint32_t)g_dot_max_r * 2 + 8;
    uint32_t area_x = dot_cx - area_w / 2;
    uint32_t area_h = (uint32_t)g_dot_max_r * 2 + 8;
    uint32_t area_y = dot_cy - (uint32_t)g_dot_max_r - 4;
    fb_swap_rect(area_x, area_y, area_w, area_h);
}

/* ============================================================================
 * Public API
 * ============================================================================ */

void boot_splash_init(void)
{
    scr_w = fb_get_width();
    scr_h = fb_get_height();

    if (scr_w == 0 || scr_h == 0) return;

    /* ---- HiDPI scale factor (for boot_info / desktop use) -------------
     * Integer scale: 1× ≤1080p,  2× ≤2160p,  3× >2160p. */
    g_scale = (scr_h > 2160) ? 3 : (scr_h > 1080) ? 2 : 1;

    /* ---- Icon: pick exact prebuilt size — no runtime scaling ----------- */
    icon_size   = OS_LOGO_SIZE_FOR_HEIGHT(scr_h);
    icon_pixels = OS_LOGO_FOR_HEIGHT(scr_h);

    /* ---- All layout values derived from icon_size (continuous scale) --
     * Dot geometry scales with the icon so spacing/radius stay proportional.
     * Font size is decoupled from icon_size — it's proportional to screen
     * height so TTF init cost stays predictable (critical: avoids the
     * icon_size/6 regression that raised 720p font from 15→21px and made
     * TTF init ~2× slower, causing a 3s blank-text gap before first status).
     */
    g_dot_spacing  = icon_size / 5;            /* 25px @ 128px icon */
    g_dot_min_r    = (int32_t)(icon_size / 30); /* 4px  @ 128px icon */
    g_dot_max_r    = (int32_t)(icon_size / 18); /* 7px  @ 128px icon */
    g_dot_y_offset = icon_size * 58 / 100;     /* 74px @ 128px icon */
    g_text_y_offset= icon_size * 40 / 100;     /* 51px @ 128px icon */
    g_text_area_w  = icon_size * 56 / 10;      /* ~716px @ 128px icon */

    /* Font size: fixed tiers per resolution — small enough for fast TTF init */
    if      (scr_h >= 2160) g_font_size = 32;
    else if (scr_h >= 1440) g_font_size = 24;
    else if (scr_h >= 1080) g_font_size = 18;
    else                    g_font_size = 15;

    /* Minimum guards for very small displays */
    if (g_dot_min_r < 2)       g_dot_min_r = 2;
    if (g_dot_max_r < 4)       g_dot_max_r = 4;
    if (g_dot_spacing < 12)    g_dot_spacing = 12;
    if (g_text_area_w < 400)   g_text_area_w = 400;

    klog(LOG_DEBUG, "SPLASH",
         "%ux%u  scale=%ux  icon=%upx  font=%upx  dot_r=%d/%d",
         scr_w, scr_h, g_scale, icon_size, g_font_size,
         g_dot_min_r, g_dot_max_r);

    /* ---- Compute layout positions ------------------------------------- */
    uint32_t icon_center_y = scr_h * ICON_Y_PCT / 100;
    icon_x = (scr_w - icon_size) / 2;
    icon_y = icon_center_y - icon_size / 2;

    dot_cx = scr_w / 2;
    dot_cy = icon_y + icon_size + g_dot_y_offset;

    text_y = dot_cy + g_text_y_offset;

    /* Suppress klog and lock compositor FIRST, before any slow init. */
    klog_set_screen_level(LOG_FATAL);
    fb_lock_compositor();
    splash_on = 1;

    /* Push a clean black frame immediately to replace UEFI/VRAM content. */
    splash_fill_rect(0, 0, scr_w, scr_h, 0x000000);
    fb_swap();

    /* Try to init TTF font at scaled size. */
    ttf_ready = 0;
    if (boot_font_init((int)g_font_size) == 0)
        ttf_ready = 1;

    anim_frame = 0;

    /* ---- Fade-in: 5 frames × 100ms = 500ms total ----
     * Text is included from frame 1 onwards so it appears 200ms in,
     * not after the entire fade completes. The fill_rect black-wipe
     * at the start of each frame clears everything, so text must be
     * re-drawn after icon + dots in every frame where it's wanted. */
    static const uint8_t fade_levels[5] = { 51, 102, 153, 204, 255 };
    for (int fi = 0; fi < 5; fi++) {
        splash_fill_rect(0, 0, scr_w, scr_h, 0x000000);
        splash_draw_icon_faded(fade_levels[fi]);
        splash_draw_dots_faded(fade_levels[fi]);
        if (fi >= 1 && ttf_ready)
            splash_draw_text("Starting...", 0x00AAAAAA);
        fb_swap();
        sleep_ms(100);
    }
}

/* Called from main.c after pit_init() + sti to start animation */
void boot_splash_start_animation(void)
{
    if (!splash_on) return;
    pit_register_callback(splash_timer_callback, ANIM_TICK_DIVISOR);
}

void boot_splash_status(const char *msg)
{
    if (!splash_on) return;

    splash_draw_text(msg, 0x00AAAAAA);
    uint32_t area_x = (scr_w > g_text_area_w) ? (scr_w - g_text_area_w) / 2 : 0;
    uint32_t text_h = g_font_size + 8;
    fb_swap_rect(area_x, text_y, g_text_area_w, text_h);
}

void boot_splash_tick(void)
{
    /* No-op: animation is now timer-driven via PIT callback */
    (void)0;
}

void boot_splash_finish(void)
{
    if (!splash_on) return;

    /* Stop timer animation */
    pit_unregister_callback();

    splash_on = 0;

    /* ---- Fade-out: 5 frames × 67ms ≈ 330ms total ----
     * Dim splash to black before handing off to the desktop compositor.
     * PIT IS initialized by this point so sleep_ms() works correctly. */
    static const uint8_t fade_out[5] = { 204, 153, 102, 51, 0 };
    for (int fi = 0; fi < 5; fi++) {
        if (fade_out[fi] > 0) {
            splash_fill_rect(0, 0, scr_w, scr_h, 0x000000);
            splash_draw_icon_faded(fade_out[fi]);
            splash_draw_dots_faded(fade_out[fi]);
        } else {
            splash_fill_rect(0, 0, scr_w, scr_h, 0x000000);
        }
        fb_swap();
        sleep_ms(67);
    }

    /* NOTE: compositor remains LOCKED after this function returns.
     * fb_unlock_compositor() is called from main.c's first-frame compositor
     * path, after wm_composite() has painted the full desktop.  Unlocking
     * here would let printk() write to the screen during window creation,
     * producing the "[OK] Heap / Terminal / Gallery" bleed-through. */
}

int boot_splash_active(void)
{
    return splash_on;
}
