/* ============================================================================
 * boot_splash.c — Persistent boot splash screen (Windows 11-style)
 *
 * Displays:
 *   1. Black background
 *   2. Centered 48×48 icon at ~40% vertical
 *   3. Animated horizontal dots (5 dots, pulse wave)
 *   4. Status text below dots
 *
 * The splash owns the framebuffer from boot_splash_init() until
 * boot_splash_finish(). During this time, fb_putchar is locked so
 * printk output goes only to serial.
 * ============================================================================ */

#include "kernel/boot_splash.h"
#include "kernel/drivers/framebuffer.h"
#include "kernel/types.h"

/* Embedded icon pixel data (generated by tools/convert_icon.py) */
#include "boot_splash_icon.h"

/* ---- Layout constants (Windows 11 proportions on 1280×720) ---- */
#define ICON_Y_PCT      38      /* icon center at 38% vertical height */
#define DOT_Y_OFFSET    52      /* dots below icon bottom, in pixels */
#define TEXT_Y_OFFSET   36      /* text below dot center, in pixels */

#define NUM_DOTS        5
#define DOT_SPACING     20      /* px between dot centers */
#define DOT_MIN_R       2       /* small dot radius */
#define DOT_MAX_R       4       /* large dot radius */

/* Animation: each dot cycles through 8 frames of pulse */
#define PULSE_FRAMES    8

/* PSF font dimensions (must match framebuffer.c) */
#define FONT_W 8
#define FONT_H 16

/* ---- State ---- */
static uint8_t  splash_on;
static uint32_t scr_w, scr_h;
static uint32_t icon_x, icon_y;    /* top-left of icon */
static uint32_t dot_cx, dot_cy;    /* center of dot row */
static uint32_t text_y;            /* top of status text */
static uint32_t anim_frame;

static char     status_buf[64];    /* current status string */

/* ---- Framebuffer helpers (direct to back buffer) ---- */

static void splash_fill_rect(uint32_t x, uint32_t y,
                              uint32_t w, uint32_t h, uint32_t color)
{
    for (uint32_t py = y; py < y + h && py < scr_h; py++)
        for (uint32_t px = x; px < x + w && px < scr_w; px++)
            fb_put_pixel(px, py, color);
}

/* Draw a filled circle with soft anti-aliased edge */
static void splash_draw_dot(int32_t cx, int32_t cy, int32_t r, uint32_t color)
{
    uint8_t cr = (uint8_t)(color >> 16);
    uint8_t cg = (uint8_t)(color >> 8);
    uint8_t cb = (uint8_t)(color);
    int32_t ro = r + 1;  /* outer for AA */

    for (int32_t y = -ro; y <= ro; y++) {
        for (int32_t x = -ro; x <= ro; x++) {
            int32_t px = cx + x, py = cy + y;
            if (px < 0 || (uint32_t)px >= scr_w ||
                py < 0 || (uint32_t)py >= scr_h)
                continue;

            int32_t d2 = x * x + y * y;
            int32_t r2 = r * r;

            if (d2 <= (r - 1) * (r - 1)) {
                fb_put_pixel((uint32_t)px, (uint32_t)py, color | 0xFF000000);
            } else if (d2 <= (r + 1) * (r + 1)) {
                /* AA fringe */
                int32_t edge = r2 - d2;
                uint8_t alpha;
                if (edge > 0)
                    alpha = (uint8_t)(edge * 200 / (r * 2 + 1));
                else
                    alpha = 0;
                if (alpha < 15) continue;

                uint8_t ob = (uint8_t)((cb * alpha) / 255);
                uint8_t og = (uint8_t)((cg * alpha) / 255);
                uint8_t or_ = (uint8_t)((cr * alpha) / 255);
                fb_put_pixel((uint32_t)px, (uint32_t)py,
                    (uint32_t)ob | ((uint32_t)og << 8) | ((uint32_t)or_ << 16));
            }
        }
    }
}

/* Draw the 48×48 icon with alpha blending (on black bg → just multiply) */
static void splash_draw_icon(void)
{
    for (uint32_t py = 0; py < BOOT_ICON_H; py++) {
        for (uint32_t px = 0; px < BOOT_ICON_W; px++) {
            uint32_t pixel = boot_icon_pixels[py * BOOT_ICON_W + px];
            uint8_t a = (uint8_t)(pixel >> 24);
            if (a == 0) continue;

            uint32_t sx = icon_x + px;
            uint32_t sy = icon_y + py;
            if (sx >= scr_w || sy >= scr_h) continue;

            if (a == 255) {
                fb_put_pixel(sx, sy, pixel);
            } else {
                /* Blend on black: just scale by alpha */
                uint8_t b = (uint8_t)((pixel & 0xFF) * a / 255);
                uint8_t g = (uint8_t)(((pixel >> 8) & 0xFF) * a / 255);
                uint8_t r = (uint8_t)(((pixel >> 16) & 0xFF) * a / 255);
                fb_put_pixel(sx, sy,
                    (uint32_t)b | ((uint32_t)g << 8) | ((uint32_t)r << 16));
            }
        }
    }
}

/* Draw text string centered at (text_y) using direct pixel drawing.
 * We replicate the PSF font data approach from framebuffer.c. */

/* --- Minimal PSF glyph data for status text ---
 * We only need ASCII 32-122 (~printable). Rather than duplicating the full
 * font table, use fb_read_pixel to grab glyphs. But that's messy.
 * Instead, just use a simple approach: write to the back buffer directly
 * with the existing fb_putchar infrastructure temporarily. */

/* Simple strlen */
static uint32_t splash_strlen(const char *s)
{
    uint32_t n = 0;
    while (s[n]) n++;
    return n;
}

/* Draw a status string centered horizontally at text_y.
 * Uses a simple 1-bit font: just draw rectangles for each pixel. */
static void splash_draw_text(const char *text, uint32_t color)
{
    /* We'll use the framebuffer's built-in font by temporarily unlocking
     * the compositor, positioning the cursor, and drawing. But that's
     * complex. Instead, use a simpler approach: draw the text pixel by
     * pixel using a minimal embedded 8×16 font subset. */

    /* Actually the simplest + cleanest approach: draw text using the
     * framebuffer's existing glyph renderer. fb_draw_char_at() draws
     * a single character at arbitrary pixel coordinates. We don't have
     * that function, so let's just draw the text by calling fb_putchar
     * at the right position.
     *
     * BUT: fb_putchar works on a grid and advances cursor. Instead,
     * let's draw a simple sans-serif approximation using rectangles.
     * This is the bootloader — we don't need fancy fonts.
     *
     * BEST approach: just draw white-on-black text by manipulating
     * cursor position and temporarily unlocking. */

    /* Clear text area */
    uint32_t text_w = 400;
    uint32_t text_x = (scr_w - text_w) / 2;
    splash_fill_rect(text_x, text_y, text_w, FONT_H + 4, 0x000000);

    /* Draw using a simplified pixel font approach:
     * We can access the PSF font from framebuffer.c extern. */

    /* The framebuffer module exposes fb_draw_glyph_at() — let's check
     * if we can use it. If not, we'll use a very simple 1px-per-pixel
     * rendering of dots and dashes as placeholder. */

    /* Use the approach: temporarily unlock, set cursor pos, print, relock.
     * fb_putchar will write to the back buffer at the grid position. */
    uint32_t len = splash_strlen(text);
    uint32_t total_w = len * FONT_W;
    uint32_t sx = (scr_w - total_w) / 2;

    /* Draw character by character using fb_put_pixel.
     * Access the embedded PSF font data. */
    extern const uint8_t kernel_font_data[][16];  /* from framebuffer.c */

    for (uint32_t i = 0; i < len; i++) {
        uint8_t c = (uint8_t)text[i];
        if (c < 32 || c > 126) c = 32;

        const uint8_t *glyph = kernel_font_data[c - 32];
        uint32_t gx = sx + i * FONT_W;

        for (uint32_t gy = 0; gy < FONT_H; gy++) {
            uint8_t row = glyph[gy];
            for (uint32_t gxp = 0; gxp < FONT_W; gxp++) {
                if (row & (0x80 >> gxp)) {
                    uint32_t px = gx + gxp;
                    uint32_t py = text_y + gy;
                    if (px < scr_w && py < scr_h)
                        fb_put_pixel(px, py, color);
                }
            }
        }
    }
}

/* Draw the 5 horizontal dots with current animation state */
static void splash_draw_dots(void)
{
    /* Clear dot area */
    uint32_t area_w = NUM_DOTS * DOT_SPACING + DOT_MAX_R * 2 + 4;
    uint32_t area_x = dot_cx - area_w / 2;
    uint32_t area_h = DOT_MAX_R * 2 + 4;
    uint32_t area_y = dot_cy - DOT_MAX_R - 2;
    splash_fill_rect(area_x, area_y, area_w, area_h, 0x000000);

    /* Draw each dot.
     * The pulse wave: dot[i] size = f(anim_frame - i*2).
     * Each dot cycles: small → growing → large → shrinking → small
     * Phase offset creates a left→right traveling wave. */
    for (uint32_t i = 0; i < NUM_DOTS; i++) {
        int32_t x = (int32_t)dot_cx
                   + (int32_t)(i * DOT_SPACING)
                   - (int32_t)((NUM_DOTS - 1) * DOT_SPACING / 2);
        int32_t y = (int32_t)dot_cy;

        /* Phase for this dot (offset by i*2 frames) */
        int32_t phase = ((int32_t)anim_frame - (int32_t)i * 2 + 100) % PULSE_FRAMES;

        /* Size curve: 0→1→2→3→4→3→2→1 (triangle wave over 8 frames) */
        int32_t half = PULSE_FRAMES / 2;
        int32_t size_idx;
        if (phase < half)
            size_idx = phase;
        else
            size_idx = PULSE_FRAMES - 1 - phase;

        /* Map size_idx (0..3) to radius (DOT_MIN_R..DOT_MAX_R) */
        int32_t r = DOT_MIN_R + (DOT_MAX_R - DOT_MIN_R) * size_idx / (half - 1);

        /* Brightness also pulses: dim when small, bright when large */
        uint32_t brightness;
        if (size_idx == 0)      brightness = 0x44;
        else if (size_idx == 1) brightness = 0x88;
        else if (size_idx == 2) brightness = 0xCC;
        else                    brightness = 0xFF;

        uint32_t color = (brightness << 16) | (brightness << 8) | brightness;
        splash_draw_dot(x, y, r, color);
    }
}

/* ============================================================================
 * Public API
 * ============================================================================ */

void boot_splash_init(void)
{
    scr_w = fb_get_width();
    scr_h = fb_get_height();

    if (scr_w == 0 || scr_h == 0) return;

    /* Compute layout positions */
    uint32_t icon_center_y = scr_h * ICON_Y_PCT / 100;
    icon_x = (scr_w - BOOT_ICON_W) / 2;
    icon_y = icon_center_y - BOOT_ICON_H / 2;

    dot_cx = scr_w / 2;
    dot_cy = icon_y + BOOT_ICON_H + DOT_Y_OFFSET;

    text_y = dot_cy + TEXT_Y_OFFSET;

    anim_frame = 0;
    status_buf[0] = '\0';

    /* Lock compositor so printk doesn't draw to screen */
    fb_lock_compositor();

    splash_on = 1;

    /* Draw initial splash */
    splash_fill_rect(0, 0, scr_w, scr_h, 0x000000);
    splash_draw_icon();
    splash_draw_dots();
    splash_draw_text("Starting...", 0x00AAAAAA);
    fb_swap();
}

void boot_splash_status(const char *msg)
{
    if (!splash_on) return;

    /* Copy message */
    uint32_t i;
    for (i = 0; i < sizeof(status_buf) - 1 && msg[i]; i++)
        status_buf[i] = msg[i];
    status_buf[i] = '\0';

    splash_draw_text(status_buf, 0x00AAAAAA);
    fb_swap_rect((scr_w - 400) / 2, text_y, 400, FONT_H + 4);
}

void boot_splash_tick(void)
{
    if (!splash_on) return;

    anim_frame++;
    splash_draw_dots();

    /* Partial swap just the dot area */
    uint32_t area_w = NUM_DOTS * DOT_SPACING + DOT_MAX_R * 2 + 4;
    uint32_t area_x = dot_cx - area_w / 2;
    uint32_t area_h = DOT_MAX_R * 2 + 4;
    uint32_t area_y = dot_cy - DOT_MAX_R - 2;
    fb_swap_rect(area_x, area_y, area_w, area_h);
}

void boot_splash_finish(void)
{
    if (!splash_on) return;

    splash_on = 0;

    /* Clear screen for desktop */
    splash_fill_rect(0, 0, scr_w, scr_h, 0x000000);
    fb_swap();

    /* Unlock compositor for normal text/wm operations */
    fb_unlock_compositor();
}

int boot_splash_active(void)
{
    return splash_on;
}
