/* ============================================================================
 * uefi_runtime.c -- UEFI Runtime Services initialization and wrappers
 *
 * Calls SetVirtualAddressMap() to remap firmware runtime memory into the
 * kernel's virtual address space (identity-mapped: virt = phys), then
 * stores the runtime services function pointers for later use.
 *
 * All runtime service calls are serialized with a spinlock because
 * UEFI firmware runtime code is NOT reentrant.
 * ============================================================================ */

#include "kernel/uefi_runtime.h"
#include "kernel/uefi_vars.h"
#include "kernel/boot_info.h"
#include "kernel/boot_init.h"
#include "kernel/uefi_config.h"
#include "kernel/firmware_tables.h"
#include "kernel/nt/ssdt.h"
#include "kernel/nt/service_numbers.h"
#include "kernel/nt/ntstatus.h"
#include "kernel/nt/zw.h"
#include "kernel/cpu_security.h"
#include "kernel/mm/heap.h"
#include "kernel/ob/peb.h"
#include "kernel/drivers/lapic.h"
#include "kernel/klog.h"
#include "kernel/sched/spinlock.h"
#include "kernel/sched/mutex.h"
#include "kernel/system_state.h"
#include "kernel/fs/gpt.h"
#include "registry.h"
#include "shim_ca.h"  /* generated by scripts/extract-shim-ca.sh; defines SHIM_CA_YEAR */

/* EFI_RUNTIME_SERVICES table signature: "RUNTSERV" (UEFI Spec §4.5) */
#define EFI_RUNTIME_SERVICES_SIGNATURE 0x56524553544E5552ULL

/* ---- Kernel-side EFI_RUNTIME_SERVICES struct ----
 * Re-declared with kernel types + UEFI_EFIAPI calling convention.
 * Layout must exactly match the UEFI spec table. */
typedef uint64_t efi_status_t;
typedef uint64_t efi_phys_addr_t;

/* EFI_TABLE_HEADER (24 bytes) */
struct efi_table_header {
    uint64_t signature;
    uint32_t revision;
    uint32_t header_size;
    uint32_t crc32;
    uint32_t reserved;
};

/* EFI_MEMORY_DESCRIPTOR for SetVirtualAddressMap */
struct efi_memory_descriptor {
    uint32_t type;
    uint32_t pad;
    uint64_t physical_start;
    uint64_t virtual_start;
    uint64_t number_of_pages;
    uint64_t attribute;
};

/* Runtime services function pointer types */
typedef efi_status_t (UEFI_EFIAPI *efi_get_time_t)(void *time, void *caps);
typedef efi_status_t (UEFI_EFIAPI *efi_set_time_t)(void *time);
typedef efi_status_t (UEFI_EFIAPI *efi_get_wakeup_time_t)(
    uint8_t *enabled, uint8_t *pending, void *time);
typedef efi_status_t (UEFI_EFIAPI *efi_set_wakeup_time_t)(
    uint8_t enable, void *time);
typedef efi_status_t (UEFI_EFIAPI *efi_set_virtual_address_map_t)(
    uint64_t map_size, uint64_t desc_size, uint32_t desc_version,
    struct efi_memory_descriptor *virt_map);
typedef efi_status_t (UEFI_EFIAPI *efi_convert_pointer_t)(
    uint64_t debug_disposition, void **address);
typedef efi_status_t (UEFI_EFIAPI *efi_get_variable_t)(
    uint16_t *name, void *guid, uint32_t *attrs, uint64_t *size, void *data);
typedef efi_status_t (UEFI_EFIAPI *efi_get_next_variable_name_t)(
    uint64_t *name_size, uint16_t *name, void *guid);
typedef efi_status_t (UEFI_EFIAPI *efi_set_variable_t)(
    uint16_t *name, void *guid, uint32_t attrs, uint64_t size, void *data);
typedef efi_status_t (UEFI_EFIAPI *efi_get_next_high_mono_count_t)(
    uint32_t *count);
typedef void (UEFI_EFIAPI *efi_reset_system_t)(
    uint32_t reset_type, efi_status_t status, uint64_t data_size, void *data);
typedef efi_status_t (UEFI_EFIAPI *efi_update_capsule_t)(
    void **hdr_array, uint64_t count, efi_phys_addr_t scatter);
typedef efi_status_t (UEFI_EFIAPI *efi_query_capsule_caps_t)(
    void **hdr_array, uint64_t count, uint64_t *max_size, uint32_t *reset_type);
typedef efi_status_t (UEFI_EFIAPI *efi_query_variable_info_t)(
    uint32_t attrs, uint64_t *max_storage, uint64_t *remaining, uint64_t *max_var);

/* Kernel-side EFI_RUNTIME_SERVICES -- must match UEFI spec layout exactly */
struct efi_runtime_services {
    struct efi_table_header         hdr;
    efi_get_time_t                  get_time;
    efi_set_time_t                  set_time;
    efi_get_wakeup_time_t           get_wakeup_time;
    efi_set_wakeup_time_t           set_wakeup_time;
    efi_set_virtual_address_map_t   set_virtual_address_map;
    efi_convert_pointer_t           convert_pointer;
    efi_get_variable_t              get_variable;
    efi_get_next_variable_name_t    get_next_variable_name;
    efi_set_variable_t              set_variable;
    efi_get_next_high_mono_count_t  get_next_high_mono_count;
    efi_reset_system_t              reset_system;
    efi_update_capsule_t            update_capsule;
    efi_query_capsule_caps_t        query_capsule_capabilities;
    efi_query_variable_info_t       query_variable_info;
};

/* ---- Module state ---- */
static struct efi_runtime_services *s_rt;    /* pointer to firmware RT table */
static mutex_t s_rt_mutex = MUTEX_INIT("uefi_rt");  /* serialize RT calls (sleepable) */
static int s_available;                      /* 1 = RT services usable */
static uint32_t s_supported;                 /* EFI_RT_SUPPORTED_* bitmask */
static int s_init_done;                      /* 1 = uefi_runtime_init has run successfully (once-latch) */
static int s_svam_done;                      /* 1 = SVAM called this boot (kernel-side latch) */
static int s_rt_prop_mismatches;             /* count of supported-bit vs pointer-NULL disagreements */

/* ---- Internal helpers ---- */

/* Build virtual address map with identity mapping (virt = phys) and call
 * SetVirtualAddressMap().  Can only be called ONCE -- irreversible.
 * Returns 0 on success, -1 on failure. */
static int call_set_virtual_address_map(void)
{
    uint32_t count = g_boot_info.rt_mmap_count;
    uint32_t desc_version = g_boot_info.uefi_mmap_desc_version;

    if (count == 0) {
        klog(LOG_WARN, "UEFI", "No runtime memory regions -- skipping SVAM");
        return 0;  /* not a failure -- firmware may have no RT regions */
    }

    /* Codex Perf H1 (2026-04-27 re-review): bound count locally
     * before indexing into vmap[BOOT_RT_MMAP_MAX]. The downstream
     * boot_reserved_populate_from_info() validator rejects an
     * oversized rt_mmap_count, but it runs LATER in pmm_init --
     * uefi_runtime_init runs first, so a corrupted handoff would
     * stack-overwrite vmap and SVAM-call firmware with a poisoned
     * map before any validator caught it. Treat over-bound count
     * as a producer error and degrade. */
    if (count > BOOT_RT_MMAP_MAX) {
        klog(LOG_ERROR, "UEFI",
             "rt_mmap_count=%u exceeds BOOT_RT_MMAP_MAX=%u -- bootloader produced malformed handoff",
             count, (uint32_t)BOOT_RT_MMAP_MAX);
        return -1;
    }

    /* We build the virtual map ourselves, so the descriptor stride matches
     * our struct size.  The firmware's desc_size may be larger (extended
     * fields), but we don't include those -- use our own stride. */
    uint32_t desc_size = (uint32_t)sizeof(struct efi_memory_descriptor);

    /* Build the virtual map in a stack-local array.
     * 64 entries x 40 bytes = 2560 bytes -- fits on the kernel stack. */
    struct efi_memory_descriptor vmap[BOOT_RT_MMAP_MAX];

    uint32_t i;
    for (i = 0; i < count; i++) {
        vmap[i].type            = g_boot_info.rt_mmap[i].type;
        vmap[i].pad             = 0;
        vmap[i].physical_start  = g_boot_info.rt_mmap[i].phys_addr;
        vmap[i].virtual_start   = g_boot_info.rt_mmap[i].phys_addr; /* identity */
        vmap[i].number_of_pages = g_boot_info.rt_mmap[i].num_pages;
        vmap[i].attribute       = g_boot_info.rt_mmap[i].attribute;
    }

    uint64_t map_size = (uint64_t)count * desc_size;

    klog(LOG_INFO, "UEFI", "SetVirtualAddressMap: %u runtime regions, "
         "desc_size=%u, desc_ver=%u", count, desc_size, desc_version);

    /* Codex H2 (2026-04-27 re-review): per-service NULL validation
     * happens AFTER SVAM in uefi_runtime_init; the SVAM function
     * pointer itself was being dereferenced before any validation,
     * so a malformed RT table could null-deref Phase 0 instead of
     * degrading cleanly. Validate the pointer here before the call. */
    if (!s_rt->set_virtual_address_map) {
        klog(LOG_ERROR, "UEFI", "SetVirtualAddressMap: NULL function pointer");
        return -1;
    }

    /* Honor EFI_RT_PROPERTIES_TABLE: a UEFI 2.10 firmware can
     * legitimately advertise SVAM as unsupported even with a non-NULL
     * pointer. Calling SVAM in that state risks the irreversible call
     * landing in firmware that has explicitly said no. read_rt_properties
     * sets s_supported = 0xFFFFFFFF when the table is absent or rejected,
     * so a literal 0xFFFFFFFF means "no override", which keeps the bit
     * set; only an explicit clear bit gates this off. */
    if (s_supported != 0xFFFFFFFFu &&
        (s_supported & EFI_RT_SUPPORTED_SET_VIRTUAL_ADDRESS_MAP) == 0) {
        klog(LOG_WARN, "UEFI",
             "SetVirtualAddressMap: properties table marks unsupported -- "
             "skipping call, using physical RT pointers");
        return 0;
    }

    efi_status_t status = s_rt->set_virtual_address_map(
        map_size, (uint64_t)desc_size, desc_version, vmap);

    if (status != UEFI_SUCCESS) {
        klog(LOG_ERROR, "UEFI", "SetVirtualAddressMap FAILED: 0x%llx",
             (unsigned long long)status);
        return -1;
    }

    klog(LOG_INFO, "UEFI", "SetVirtualAddressMap OK");
    return 0;
}

/* Cross-check EFI_RT_PROPERTIES_TABLE supported bits against the actual
 * runtime-services-table function pointers. Either direction is a
 * firmware bug worth surfacing on serial:
 *   - bit set + pointer NULL -> firmware advertises a service it cannot
 *     actually invoke. Calling would null-deref.
 *   - bit clear + pointer non-NULL -> firmware says service is unsupported
 *     after SVAM, but left the (post-SVAM virtual) pointer non-NULL. The
 *     kernel must NOT call those pointers per UEFI 2.10 section 4.6.2.
 * Returns the number of mismatches; updates s_rt_prop_mismatches. */
static int rt_check_property_pointer_mismatch(void)
{
    if (!s_rt) return 0;

    /* Validate that the firmware-declared RT services header covers
     * every offset we are about to read. UEFI 2.10 sets the layout at
     * 24 (header) + 14 * 8 (function pointers) = 136 bytes. Older or
     * truncated firmware tables shorter than this would have us read
     * past the declared extent. Skip the mismatch check entirely on
     * such tables -- the 5-pointer init validation is enough. */
    if (s_rt->hdr.header_size < sizeof(struct efi_runtime_services)) {
        klog(LOG_WARN, "UEFI",
             "RT services header_size=%u below expected %u -- "
             "skipping property mismatch check",
             (uint32_t)s_rt->hdr.header_size,
             (uint32_t)sizeof(struct efi_runtime_services));
        return 0;
    }

    /* Mirrors the supported-bit -> pointer mapping for every named slot
     * in the RT properties table. UpdateCapsule and friends are
     * deliberately included even though they are not in the 5 critical
     * pointers checked above -- the firmware-table-platform-inventory
     * roadmap requires every service to be cross-checked. */
    struct rt_pp {
        uint32_t flag;
        const char *name;
        void *ptr;
    } svc[] = {
        { EFI_RT_SUPPORTED_GET_TIME,                "GetTime",                (void *)s_rt->get_time },
        { EFI_RT_SUPPORTED_SET_TIME,                "SetTime",                (void *)s_rt->set_time },
        { EFI_RT_SUPPORTED_GET_WAKEUP_TIME,         "GetWakeupTime",          (void *)s_rt->get_wakeup_time },
        { EFI_RT_SUPPORTED_SET_WAKEUP_TIME,         "SetWakeupTime",          (void *)s_rt->set_wakeup_time },
        { EFI_RT_SUPPORTED_GET_VARIABLE,            "GetVariable",            (void *)s_rt->get_variable },
        { EFI_RT_SUPPORTED_GET_NEXT_VARIABLE_NAME,  "GetNextVariableName",    (void *)s_rt->get_next_variable_name },
        { EFI_RT_SUPPORTED_SET_VARIABLE,            "SetVariable",            (void *)s_rt->set_variable },
        { EFI_RT_SUPPORTED_SET_VIRTUAL_ADDRESS_MAP, "SetVirtualAddressMap",   (void *)s_rt->set_virtual_address_map },
        { EFI_RT_SUPPORTED_CONVERT_POINTER,         "ConvertPointer",         (void *)s_rt->convert_pointer },
        { EFI_RT_SUPPORTED_GET_NEXT_HIGH_MONO,      "GetNextHighMonoCount",   (void *)s_rt->get_next_high_mono_count },
        { EFI_RT_SUPPORTED_RESET_SYSTEM,            "ResetSystem",            (void *)s_rt->reset_system },
        { EFI_RT_SUPPORTED_UPDATE_CAPSULE,          "UpdateCapsule",          (void *)s_rt->update_capsule },
        { EFI_RT_SUPPORTED_QUERY_CAPSULE_CAP, "QueryCapsuleCaps", (void *)s_rt->query_capsule_capabilities },
        { EFI_RT_SUPPORTED_QUERY_VARIABLE_INFO,     "QueryVariableInfo",      (void *)s_rt->query_variable_info },
    };

    int mismatches = 0;
    uint32_t n = (uint32_t)(sizeof(svc) / sizeof(svc[0]));
    for (uint32_t i = 0; i < n; i++) {
        int advertised = (s_supported & svc[i].flag) != 0;
        int present    = svc[i].ptr != 0;
        if (advertised != present) {
            klog(LOG_WARN, "UEFI",
                 "firmware: %s property mismatch (pointer=%s, supported=%d)",
                 svc[i].name, present ? "VALID" : "NULL", advertised);
            mismatches++;
            /* Make pointer NULLness authoritative for callable services.
             * Wrappers in this file gate on s_supported before
             * dereferencing s_rt->method, so a firmware that advertises
             * a service but leaves the pointer NULL would null-deref on
             * the first call. Clear the bit so wrappers fall through
             * to UEFI_UNSUPPORTED. The reverse direction (bit clear,
             * pointer non-NULL) is benign -- the kernel must NOT call
             * pointers UEFI 2.10 section 4.6.2 marks unsupported, and
             * the wrappers already refuse based on s_supported. */
            if (advertised && !present) {
                s_supported &= ~svc[i].flag;
            }
        }
    }
    s_rt_prop_mismatches = mismatches;
    return mismatches;
}

int uefi_rt_property_mismatches(void)
{
    return s_rt_prop_mismatches;
}

/* Read EFI_RT_PROPERTIES_TABLE from config table to determine which
 * runtime services are actually supported by this firmware. */
static void read_rt_properties(void)
{
    struct boot_uefi_guid rt_props_guid = UEFI_GUID_RT_PROPS;
    uintptr_t table_addr = uefi_find_config_table(&rt_props_guid);

    if (table_addr == 0) {
        /* Table absent -- assume all services supported (UEFI < 2.10) */
        s_supported = 0xFFFFFFFF;
        return;
    }

    /* Validate the EFI_RT_PROPERTIES_TABLE extent against the firmware
     * memory map BEFORE dereferencing any field, mirroring the MAT
     * pre-deref guard. A bogus VendorTable pointer would otherwise
     * fault or poison s_supported with bytes from unrelated memory. */
    if (!firmware_table_mmap_contains((uintptr_t)table_addr,
            sizeof(struct uefi_rt_properties_table))) {
        klog(LOG_WARN, "UEFI",
             "RT properties: header at 0x%lx not in firmware mmap -- "
             "treating table as absent", (uint64_t)table_addr);
        s_supported = 0xFFFFFFFF;
        return;
    }

    const struct uefi_rt_properties_table *props =
        (const struct uefi_rt_properties_table *)table_addr;

    /* Reject if the firmware-declared length is shorter than the spec
     * minimum (UEFI 2.10 section 4.6.1: 8 bytes). Treat as absent so the
     * fallback path (assume all services supported) runs. */
    if (props->length < sizeof(struct uefi_rt_properties_table)) {
        klog(LOG_WARN, "UEFI",
             "RT properties: declared length=%u below spec minimum %u "
             "-- treating table as absent", (uint32_t)props->length,
             (uint32_t)sizeof(struct uefi_rt_properties_table));
        s_supported = 0xFFFFFFFF;
        return;
    }

    s_supported = props->runtime_services_supported;

    klog(LOG_INFO, "UEFI", "RT properties: supported=0x%04x", s_supported);
}

/* ---- Public API ---- */

/* Clear advertised RT capability + legacy availability byte in
 * lockstep with s_available going to 0. Codex M1 (2026-04-27
 * re-review): without this, BOOT_DEGRADED paths leave
 * caps_present & BOOT_CAP_RUNTIME_SERVICES set and the legacy
 * uefi_rt_available byte at 1, so any later boot_caps_require
 * caller still treats RT as present after init has disabled it.
 *
 * Codex Consistency M1 (re-review): clearing caps_present is not
 * enough -- the boot_info contract (boot_info.h:510-518 / 1183-1187)
 * requires every known capability bit to live in EXACTLY ONE of
 * caps_present or caps_degraded, never neither. Clearing without
 * setting caps_degraded leaves the bit unclassified, which trips
 * later validators that walk the known-bit set. Mirror the
 * present->degraded transition that boot_caps_mark_present() does
 * in the opposite direction. */
static void rt_advertise_unavailable(void)
{
    s_available = 0;
    g_boot_info.uefi_rt_available = 0;
    g_boot_info.caps_present &= ~(uint64_t)BOOT_CAP_RUNTIME_SERVICES;
    g_boot_info.caps_degraded |= (uint64_t)BOOT_CAP_RUNTIME_SERVICES;
}

boot_result_t uefi_runtime_init(void)
{
    (void)s_rt_mutex;  /* initialized statically via MUTEX_INIT */

    /* Codex H1 (2026-04-27 re-review): once-latch -- if a duplicate
     * BOOT_STEP / re-init path calls us, return the cached state
     * instead of re-running SVAM (which UEFI permits ONLY ONCE per
     * boot per spec §7.4.2; a second call returns EFI_UNSUPPORTED
     * and would leave s_available=0, disabling previously-working
     * services). */
    if (s_init_done) {
        klog(LOG_INFO, "UEFI",
             "uefi_runtime_init: already initialised (s_available=%d, returning cached state)",
             s_available);
        return s_available ? BOOT_OK : BOOT_DEGRADED;
    }

    s_available = 0;
    s_supported = 0;

    /* Authoritative gate: capability negotiation decides whether
     * runtime services are available. A loader that reports
     * BOOT_CAP_RUNTIME_SERVICES as degraded MUST skip setup even if
     * the legacy uefi_rt_available byte is set (fail-closed semantic
     * from the capability-negotiation contract). Keep the legacy
     * check as a second gate to defend against the path where
     * boot_caps_validate has not yet run (early-boot callers). */
    if (!boot_caps_require(BOOT_CAP_RUNTIME_SERVICES) ||
        !g_boot_info.uefi_rt_available) {
        klog(LOG_WARN, "UEFI",
             "Runtime services: UNAVAILABLE (caps_present=0x%lx, legacy=%u)",
             (uint64_t)(g_boot_info.caps_present & BOOT_CAP_RUNTIME_SERVICES),
             (uint64_t)g_boot_info.uefi_rt_available);
        rt_advertise_unavailable();
        s_init_done = 1;
        return BOOT_DEGRADED;
    }

    s_rt = (struct efi_runtime_services *)g_boot_info.uefi_runtime_services;
    if (!s_rt) {
        klog(LOG_ERROR, "UEFI", "Runtime services pointer is NULL");
        rt_advertise_unavailable();
        s_init_done = 1;
        return BOOT_DEGRADED;
    }

    /* Validate RT table signature (UEFI Spec §4.5: "RUNTSERV") */
    if (s_rt->hdr.signature != EFI_RUNTIME_SERVICES_SIGNATURE) {
        klog(LOG_ERROR, "UEFI", "RT table signature mismatch: 0x%llx",
             (unsigned long long)s_rt->hdr.signature);
        s_rt = (struct efi_runtime_services *)0;
        rt_advertise_unavailable();
        s_init_done = 1;
        return BOOT_DEGRADED;
    }

    /* Validate CRC32 (zero the field, compute, compare, restore) */
    {
        uint32_t saved_crc = s_rt->hdr.crc32;
        uint32_t hdr_size = s_rt->hdr.header_size;
        if (hdr_size == 0 || hdr_size > 4096)
            hdr_size = sizeof(struct efi_table_header);
        s_rt->hdr.crc32 = 0;
        uint32_t computed = gpt_crc32(&s_rt->hdr, hdr_size);
        s_rt->hdr.crc32 = saved_crc;
        if (computed != saved_crc) {
            klog(LOG_WARN, "UEFI", "RT table CRC32 mismatch: "
                 "expected=0x%08x computed=0x%08x (proceeding with caution)",
                 saved_crc, computed);
            /* Warn but don't fail -- some firmware has stale CRC after SVAM.
             * Windows hal.dll also warns-and-continues on CRC mismatch. */
        }
    }

    /* Read supported services mask before SVAM (config table is still valid) */
    read_rt_properties();

    /* Call SetVirtualAddressMap.  Per UEFI spec §7.4.2 this must happen after
     * ExitBootServices().  The bootloader preserves pointers only; SVAM is
     * always the kernel's responsibility.  svam_called is kept as a safety
     * guard in case a future loader calls SVAM before handoff. The kernel-
     * side s_svam_done latch (Codex H1, 2026-04-27) is the same guard
     * within the kernel: even if uefi_runtime_init's once-latch is
     * bypassed somehow, we never call firmware SVAM twice. */
    if (g_boot_info.uefi_runtime.svam_called || s_svam_done) {
        klog(LOG_INFO, "UEFI", "SetVirtualAddressMap already called");
    } else {
        if (call_set_virtual_address_map() != 0) {
            klog(LOG_ERROR, "UEFI", "Runtime services: UNAVAILABLE (SVAM failed)");
            rt_advertise_unavailable();
            s_init_done = 1;
            return BOOT_DEGRADED;
        }
        s_svam_done = 1;
        /* Mirror the kernel-side latch into boot_info so anyone reading
         * the field post-handoff (e.g. a kexec replacement kernel
         * sharing the boot_info ABI) sees the correct state. */
        g_boot_info.uefi_runtime.svam_called = 1;
    }

    /* Validate critical function pointers */
    int missing = 0;

    if (!s_rt->get_time)     { klog(LOG_WARN, "UEFI", "RT GetTime: NULL");     missing++; }
    if (!s_rt->set_time)     { klog(LOG_WARN, "UEFI", "RT SetTime: NULL");     missing++; }
    if (!s_rt->get_variable) { klog(LOG_WARN, "UEFI", "RT GetVariable: NULL"); missing++; }
    if (!s_rt->set_variable) { klog(LOG_WARN, "UEFI", "RT SetVariable: NULL"); missing++; }
    if (!s_rt->reset_system) { klog(LOG_WARN, "UEFI", "RT ResetSystem: NULL"); missing++; }

    if (missing > 0) {
        klog(LOG_WARN, "UEFI", "Runtime services: UNAVAILABLE "
             "(firmware limitation, %d/%d pointers NULL)", missing, 5);
        rt_advertise_unavailable();
        s_init_done = 1;
        return BOOT_DEGRADED;
    }

    /* Mark available -- all critical pointers validated */
    s_available = 1;
    s_init_done = 1;

    /* Cross-check supported bitmask vs pointer presence for all named
     * RT services. Diagnostic only; does not gate availability. */
    rt_check_property_pointer_mismatch();

    /* Build human-readable service list for log */
    char services[128];
    uint32_t pos = 0;

    struct {
        uint32_t flag;
        const char *name;
    } svc_names[] = {
        { EFI_RT_SUPPORTED_GET_TIME,      "GetTime" },
        { EFI_RT_SUPPORTED_SET_TIME,      "SetTime" },
        { EFI_RT_SUPPORTED_GET_VARIABLE,  "GetVariable" },
        { EFI_RT_SUPPORTED_SET_VARIABLE,  "SetVariable" },
        { EFI_RT_SUPPORTED_RESET_SYSTEM,  "ResetSystem" },
        { EFI_RT_SUPPORTED_UPDATE_CAPSULE, "UpdateCapsule" },
    };

    uint32_t n = sizeof(svc_names) / sizeof(svc_names[0]);
    uint32_t i;
    for (i = 0; i < n; i++) {
        if (s_supported & svc_names[i].flag) {
            if (pos > 0 && pos < sizeof(services) - 1)
                services[pos++] = ' ';
            const char *nm = svc_names[i].name;
            uint32_t j;
            for (j = 0; nm[j] && pos < sizeof(services) - 1; j++)
                services[pos++] = nm[j];
        }
    }
    services[pos] = '\0';

    klog(LOG_INFO, "UEFI", "Runtime services: OK");
    klog(LOG_INFO, "UEFI", "Runtime services active: %s", services);

    return BOOT_OK;
}

int uefi_rt_available(void)
{
    return s_available;
}

uint32_t uefi_rt_supported(void)
{
    return s_supported;
}

/* ============================================================================
 * UEFI Variable Services (§1.2)
 *
 * GetVariable, SetVariable, GetNextVariableName wrappers.
 * All calls are serialized via s_rt_mutex (firmware is not reentrant).
 * LAPIC timer masked during all calls -- firmware SMI may enable interrupts.
 * ============================================================================ */

/* ---- Centralized RT call entry/exit ----
 * Mask LAPIC timer during ALL UEFI runtime calls -- firmware may enable
 * interrupts internally via SMI, causing timer to fire into wrong context.
 * Acquire the RT mutex to serialize (firmware is not reentrant).
 * Sleepable: threads yield on contention instead of spinning with IRQs off.
 * Emergency path (panic/reset): uses trylock to avoid blocking. */

/* TSC read for latency measurement */
static inline uint64_t rt_rdtsc(void)
{
    uint32_t lo, hi;
    __asm__ volatile("rdtsc" : "=a"(lo), "=d"(hi));
    return ((uint64_t)hi << 32) | lo;
}

/* Latency warning threshold: 50ms at ~3 GHz = 150M cycles.
 * Use boot_info.timing.tsc_freq for accurate conversion. */
#define RT_LATENCY_WARN_MS 50

struct rt_call_state {
    uint32_t saved_lvt;
    uint64_t tsc_start;
};

static void rt_call_enter(struct rt_call_state *state)
{
    state->saved_lvt = 0;
    mutex_lock(&s_rt_mutex);
    if (lapic_available() && kernel_subsystem_ready(SUBSYS_TIMER)) {
        uint32_t lvt = lapic_read(LAPIC_REG_LVT_TIMER);
        lapic_write(LAPIC_REG_LVT_TIMER, lvt | LVT_MASKED);
        state->saved_lvt = lvt;
    }
    state->tsc_start = rt_rdtsc();
}

static void rt_call_exit(struct rt_call_state *state, const char *svc_name)
{
    uint64_t elapsed = rt_rdtsc() - state->tsc_start;
    if (state->saved_lvt)
        lapic_write(LAPIC_REG_LVT_TIMER, state->saved_lvt);
    mutex_unlock(&s_rt_mutex);

    /* Log latency warning if RT call took > 50ms */
    uint64_t freq = g_boot_info.timing.tsc_freq;
    if (freq > 0) {
        uint64_t ms = (elapsed * 1000) / freq;
        if (ms >= RT_LATENCY_WARN_MS) {
            klog(LOG_WARN, "UEFI", "RT %s took %u ms (threshold %u ms)",
                 svc_name, (uint32_t)ms, (uint32_t)RT_LATENCY_WARN_MS);
        }
    }
}

/* Emergency RT call for panic/reset -- trylock, no sleep, no latency log */
static int rt_call_enter_emergency(struct rt_call_state *state)
{
    state->saved_lvt = 0;
    state->tsc_start = 0;
    if (!mutex_trylock(&s_rt_mutex))
        return 0;  /* contended -- caller proceeds without lock */
    if (lapic_available() && kernel_subsystem_ready(SUBSYS_TIMER)) {
        uint32_t lvt = lapic_read(LAPIC_REG_LVT_TIMER);
        lapic_write(LAPIC_REG_LVT_TIMER, lvt | LVT_MASKED);
        state->saved_lvt = lvt;
    }
    return 1;
}

static void rt_call_exit_emergency(struct rt_call_state *state)
{
    if (state->saved_lvt)
        lapic_write(LAPIC_REG_LVT_TIMER, state->saved_lvt);
    mutex_unlock(&s_rt_mutex);
}

uint64_t uefi_get_variable(const struct boot_uefi_guid *guid,
                           const uint16_t *name,
                           uint32_t *attributes,
                           uint64_t *data_size,
                           void *data)
{
    struct rt_call_state rcs;
    if (!s_available || !s_rt) return UEFI_UNSUPPORTED;
    if (!(s_supported & EFI_RT_SUPPORTED_GET_VARIABLE)) return UEFI_UNSUPPORTED;

    rt_call_enter(&rcs);
    efi_status_t status = s_rt->get_variable(
        (uint16_t *)name, (void *)guid, attributes, data_size, data);
    rt_call_exit(&rcs, "GetVariable");

    return status;
}

uint64_t uefi_set_variable(const struct boot_uefi_guid *guid,
                           const uint16_t *name,
                           uint32_t attributes,
                           uint64_t data_size,
                           const void *data)
{
    struct rt_call_state rcs;
    if (!s_available || !s_rt) return UEFI_UNSUPPORTED;
    if (!(s_supported & EFI_RT_SUPPORTED_SET_VARIABLE)) return UEFI_UNSUPPORTED;

    rt_call_enter(&rcs);
    efi_status_t status = s_rt->set_variable(
        (uint16_t *)name, (void *)guid, attributes, data_size, (void *)data);
    rt_call_exit(&rcs, "SetVariable");

    return status;
}

uint64_t uefi_query_variable_info(uint32_t attributes,
                                  uint64_t *max_storage,
                                  uint64_t *remaining,
                                  uint64_t *max_var_size)
{
    struct rt_call_state rcs;
    if (!s_available || !s_rt) return UEFI_UNSUPPORTED;
    if (!(s_supported & EFI_RT_SUPPORTED_QUERY_VARIABLE_INFO))
        return UEFI_UNSUPPORTED;
    if (!s_rt->query_variable_info) return UEFI_UNSUPPORTED;

    rt_call_enter(&rcs);
    efi_status_t status = s_rt->query_variable_info(
        attributes, max_storage, remaining, max_var_size);
    rt_call_exit(&rcs, "QueryVariableInfo");

    return status;
}

/* Counting callback for uefi_var_enumerate */
static void count_var_cb(const uint16_t *name, const struct boot_uefi_guid *guid,
                         void *ctx)
{
    (void)name; (void)guid;
    (*(uint32_t *)ctx)++;
}

uint64_t uefi_get_next_variable_name(uint64_t *name_size, uint16_t *name,
                                     struct boot_uefi_guid *guid)
{
    if (!s_available || !s_rt) return UEFI_UNSUPPORTED;
    if (!(s_supported & EFI_RT_SUPPORTED_GET_NEXT_VARIABLE_NAME))
        return UEFI_UNSUPPORTED;

    struct rt_call_state rcs;
    rt_call_enter(&rcs);
    efi_status_t status = s_rt->get_next_variable_name(name_size, name, guid);
    rt_call_exit(&rcs, "GetNextVariableName");

    return status;
}

boot_result_t uefi_vars_init(void)
{
    if (!s_available) {
        klog(LOG_INFO, "UEFI", "Variable services: unavailable");
        return BOOT_DEGRADED;
    }

    /* Enumerate all variables */
    uint32_t total = 0;
    uefi_var_enumerate(count_var_cb, &total);

    /* BootOrder and BootCurrent: use boot_info fields populated by the
     * bootloader pre-ExitBootServices instead of re-reading via runtime
     * services. Avoids duplicate firmware calls and works even if runtime
     * variable services are degraded. */
    {
        uint8_t count = g_boot_info.uefi_boot_order_count;
        if (count > 0) {
            char order_str[96];
            uint32_t pos = 0;
            uint8_t e;
            for (e = 0; e < count && pos < sizeof(order_str) - 6; e++) {
                if (e > 0 && pos < sizeof(order_str) - 1)
                    order_str[pos++] = ',';
                uint16_t val = g_boot_info.uefi_boot_order[e];
                order_str[pos++] = "0123456789ABCDEF"[(val >> 12) & 0xF];
                order_str[pos++] = "0123456789ABCDEF"[(val >> 8) & 0xF];
                order_str[pos++] = "0123456789ABCDEF"[(val >> 4) & 0xF];
                order_str[pos++] = "0123456789ABCDEF"[val & 0xF];
            }
            order_str[pos] = '\0';
            klog(LOG_INFO, "UEFI", "NVRAM: %u variables, BootOrder=[%s]",
                 total, order_str);
        } else {
            klog(LOG_INFO, "UEFI", "NVRAM: %u variables (BootOrder not available)",
                 total);
        }
    }

    if (g_boot_info.uefi_boot_current != 0xFFFF) {
        uint16_t bc = g_boot_info.uefi_boot_current;
        char bc_str[5];
        bc_str[0] = "0123456789ABCDEF"[(bc >> 12) & 0xF];
        bc_str[1] = "0123456789ABCDEF"[(bc >> 8) & 0xF];
        bc_str[2] = "0123456789ABCDEF"[(bc >> 4) & 0xF];
        bc_str[3] = "0123456789ABCDEF"[bc & 0xF];
        bc_str[4] = '\0';
        klog(LOG_INFO, "UEFI", "BootCurrent: Boot%s", bc_str);
    }

    return BOOT_OK;
}

/* ============================================================================
 * System Reset
 *
 * ResetSystem() is a UEFI runtime service that handles all platform-specific
 * details for shutdown, reboot, and power cycling.  Preferred over direct
 * ACPI register writes or keyboard controller reset.
 * ============================================================================ */

/* x86 port I/O for keyboard controller fallback */
static inline void outb(uint16_t port, uint8_t val)
{
    __asm__ volatile("outb %0, %1" : : "a"(val), "Nd"(port));
}

void uefi_reset(uint32_t reset_type)
{
    const char *type_names[] = { "Cold", "Warm", "Shutdown", "PlatformSpecific" };
    const char *name = (reset_type < 4) ? type_names[reset_type] : "Unknown";

    klog(LOG_INFO, "UEFI", "ResetSystem(%s)...", name);

    if (s_available && s_rt &&
        (s_supported & EFI_RT_SUPPORTED_RESET_SYSTEM)) {
        struct rt_call_state rcs;
        /* Emergency path: trylock to avoid sleeping in panic context.
         * If contended, another CPU is in firmware -- calling ResetSystem
         * concurrently risks firmware corruption, but the alternative is
         * hanging with no reset. A reboot attempt is better than certain hang. */
        int got_lock = rt_call_enter_emergency(&rcs);
        if (!got_lock)
            klog(LOG_WARN, "UEFI", "ResetSystem: mutex contended, proceeding without lock");
        /* ResetSystem() does NOT return on success */
        s_rt->reset_system(reset_type, UEFI_SUCCESS, 0, (void *)0);
        if (got_lock) rt_call_exit_emergency(&rcs);
        /* If we get here, it failed */
        klog(LOG_ERROR, "UEFI", "ResetSystem() returned -- falling back");
    }

    /* Fallback: keyboard controller reset (0x64/0xFE) */
    klog(LOG_WARN, "UEFI", "Fallback: keyboard controller reset");
    outb(0x64, 0xFE);

    /* If that failed too, halt */
    for (;;)
        __asm__ volatile("hlt");
}

/* ============================================================================
 * RTC Time Services
 *
 * GetTime/SetTime/GetWakeupTime wrappers.
 * ============================================================================ */

uint64_t uefi_get_time(struct efi_time *time,
                       struct efi_time_capabilities *caps)
{
    struct rt_call_state rcs;
    if (!s_available || !s_rt) return UEFI_UNSUPPORTED;
    if (!(s_supported & EFI_RT_SUPPORTED_GET_TIME)) return UEFI_UNSUPPORTED;

    rt_call_enter(&rcs);
    efi_status_t status = s_rt->get_time(time, caps);
    rt_call_exit(&rcs, "GetTime");

    return status;
}

uint64_t uefi_set_time(const struct efi_time *time)
{
    struct rt_call_state rcs;
    if (!s_available || !s_rt) return UEFI_UNSUPPORTED;
    if (!(s_supported & EFI_RT_SUPPORTED_SET_TIME)) return UEFI_UNSUPPORTED;

    rt_call_enter(&rcs);
    efi_status_t status = s_rt->set_time((void *)time);
    rt_call_exit(&rcs, "SetTime");

    return status;
}

uint64_t uefi_get_wakeup_time(uint8_t *enabled, uint8_t *pending,
                              struct efi_time *time)
{
    struct rt_call_state rcs;
    if (!s_available || !s_rt) return UEFI_UNSUPPORTED;
    if (!(s_supported & EFI_RT_SUPPORTED_GET_WAKEUP_TIME))
        return UEFI_UNSUPPORTED;

    rt_call_enter(&rcs);
    efi_status_t status = s_rt->get_wakeup_time(enabled, pending, time);
    rt_call_exit(&rcs, "GetWakeupTime");

    return status;
}

boot_result_t uefi_time_init(void)
{
    struct efi_time t;
    struct efi_time_capabilities caps;

    efi_status_t status = uefi_get_time(&t, &caps);
    if (status != UEFI_SUCCESS) {
        klog(LOG_WARN, "UEFI", "GetTime failed -- wall clock not seeded");
        return BOOT_DEGRADED;
    }

    /* Format: "YYYY-MM-DD HH:MM:SS" -- manual zero-padding (no %02u in klog) */
    char ts[20];
    uint16_t y = t.year;
    ts[0]  = '0' + (char)(y / 1000);
    ts[1]  = '0' + (char)((y / 100) % 10);
    ts[2]  = '0' + (char)((y / 10) % 10);
    ts[3]  = '0' + (char)(y % 10);
    ts[4]  = '-';
    ts[5]  = '0' + (char)(t.month / 10);
    ts[6]  = '0' + (char)(t.month % 10);
    ts[7]  = '-';
    ts[8]  = '0' + (char)(t.day / 10);
    ts[9]  = '0' + (char)(t.day % 10);
    ts[10] = ' ';
    ts[11] = '0' + (char)(t.hour / 10);
    ts[12] = '0' + (char)(t.hour % 10);
    ts[13] = ':';
    ts[14] = '0' + (char)(t.minute / 10);
    ts[15] = '0' + (char)(t.minute % 10);
    ts[16] = ':';
    ts[17] = '0' + (char)(t.second / 10);
    ts[18] = '0' + (char)(t.second % 10);
    ts[19] = '\0';

    klog(LOG_INFO, "UEFI", "RTC: %s", ts);

    /* Timezone info */
    if (t.timezone == (int16_t)EFI_UNSPECIFIED_TIMEZONE) {
        klog(LOG_INFO, "UEFI", "RTC: timezone unspecified (local time)");
    } else {
        int16_t tz = t.timezone;
        uint32_t abs_tz = (uint32_t)((tz >= 0) ? tz : -tz);
        klog(LOG_INFO, "UEFI", "RTC: UTC%s%u:%s%u",
             (tz >= 0) ? "+" : "-",
             abs_tz / 60,
             (abs_tz % 60 < 10) ? "0" : "",
             abs_tz % 60);
    }

    klog(LOG_INFO, "UEFI", "RTC: resolution=%u Hz, accuracy=%u ppm",
         caps.resolution, caps.accuracy);

    return BOOT_OK;
}

/* ============================================================================
 * Secure Boot State Detection
 *
 * Reads UEFI NVRAM variables to determine Secure Boot state.
 * ============================================================================ */

static int s_sb_enabled;      /* SecureBoot variable = 1 */
static int s_sb_state_valid;  /* 1 if SecureBoot var read returned authoritative
                                 value; 0 if read failed (state is unknown).
                                 Codex review 2026-04-28 H1: registry must NOT
                                 publish State when this is 0 -- consumers must
                                 see a separate StateValid=0 signal so the
                                 read-failure path is distinguishable from
                                 genuinely-disabled. */
static int s_sb_setup_mode;   /* SetupMode variable = 1 */
static int s_sb_deployed_mode;/* DeployedMode variable = 1 (UEFI 2.5+) */
static int s_sb_audit_mode;   /* AuditMode variable = 1 (UEFI 2.5+) */
static int s_sb_pk_present;   /* PK variable exists with data */
static int s_sb_kek_present;  /* KEK variable exists with data */

/* Helper: read a single-byte UEFI global variable. Returns the byte, or -1.
 *
 * Codex adversarial review 2026-04-28 M2: SUCCESS alone is not enough --
 * a buggy or hostile firmware can return SUCCESS with sz != 1, leaving
 * `val` at the zero-init or filling only part of the byte. Require both
 * SUCCESS AND sz == sizeof(val); anything else is a read failure. */
static int read_global_byte(const uint16_t *name)
{
    struct boot_uefi_guid global = EFI_GLOBAL_VARIABLE_GUID;
    uint8_t val = 0;
    uint64_t sz = sizeof(val);
    uint32_t attrs = 0;

    efi_status_t status = uefi_get_variable(&global, name, &attrs, &sz, &val);
    if (status != UEFI_SUCCESS || sz != sizeof(val))
        return -1;
    return (int)val;
}

/* Helper: check if a UEFI global variable exists with non-zero size.
 *
 * Codex adversarial review 2026-04-28 M3: SUCCESS-with-sz=0 must NOT
 * count as "exists" for PK/KEK enrollment checks. Empty PK/KEK
 * variables are firmware artifacts, not enrolled keys; reporting them
 * as enrolled would mislead Secure Boot status consumers. Require
 * sz > 0 on either SUCCESS or BUFFER_TOO_SMALL.
 */
static int global_var_exists(const uint16_t *name)
{
    struct boot_uefi_guid global = EFI_GLOBAL_VARIABLE_GUID;
    uint64_t sz = 0;
    uint32_t attrs = 0;

    /* Call with size=0 to get the actual size via BUFFER_TOO_SMALL */
    efi_status_t status = uefi_get_variable(
        &global, name, &attrs, &sz, (void *)0);

    /* BUFFER_TOO_SMALL is the canonical "exists with data" signal */
    if (status == UEFI_BUFFER_TOO_SMALL && sz > 0)
        return 1;
    /* SUCCESS with sz > 0 also counts (firmware sized the buffer for us) */
    if (status == UEFI_SUCCESS && sz > 0)
        return 1;
    return 0;
}

boot_result_t uefi_secureboot_init(void)
{
    s_sb_enabled = 0;
    s_sb_state_valid = 0;
    s_sb_setup_mode = 0;
    s_sb_deployed_mode = 0;
    s_sb_audit_mode = 0;
    s_sb_pk_present = 0;
    s_sb_kek_present = 0;

    if (!s_available) {
        klog(LOG_INFO, "UEFI", "Secure Boot: unknown (runtime unavailable)");
        return BOOT_DEGRADED;
    }

    /* Read SecureBoot variable (uint8_t: 0=off, 1=on) */
    static const uint16_t sb_name[] = {
        'S','e','c','u','r','e','B','o','o','t', 0
    };
    int sb_val = read_global_byte(sb_name);
    int sb_val_valid = (sb_val >= 0);
    if (sb_val_valid) {
        s_sb_enabled = (sb_val == 1) ? 1 : 0;
        s_sb_state_valid = 1;
    }

    /* Read SetupMode variable (uint8_t: 0=User Mode, 1=Setup Mode) */
    static const uint16_t sm_name[] = {
        'S','e','t','u','p','M','o','d','e', 0
    };
    int sm_val = read_global_byte(sm_name);
    if (sm_val >= 0)
        s_sb_setup_mode = (sm_val == 1) ? 1 : 0;

    /* Read DeployedMode variable (UEFI 2.5+: 0=not deployed, 1=deployed) */
    static const uint16_t dm_name[] = {
        'D','e','p','l','o','y','e','d','M','o','d','e', 0
    };
    int dm_val = read_global_byte(dm_name);
    if (dm_val >= 0)
        s_sb_deployed_mode = (dm_val == 1) ? 1 : 0;

    /* Read AuditMode variable (UEFI 2.5+: 0=off, 1=audit) */
    static const uint16_t am_name[] = {
        'A','u','d','i','t','M','o','d','e', 0
    };
    int am_val = read_global_byte(am_name);
    if (am_val >= 0)
        s_sb_audit_mode = (am_val == 1) ? 1 : 0;

    /* Check PK existence */
    static const uint16_t pk_name[] = { 'P','K', 0 };
    s_sb_pk_present = global_var_exists(pk_name);

    /* Check KEK existence */
    static const uint16_t kek_name[] = { 'K','E','K', 0 };
    s_sb_kek_present = global_var_exists(kek_name);

    /* Log summary. When the SecureBoot variable read FAILED we have
     * no authoritative state -- log UNKNOWN rather than "DISABLED"
     * so operators distinguish "read failure" from "keys not enrolled
     * + user turned it off". */
    if (!sb_val_valid) {
        klog(LOG_WARN, "UEFI",
             "Secure Boot: UNKNOWN (variable read failed; cap degraded)");
    } else if (s_sb_enabled) {
        klog(LOG_INFO, "UEFI", "Secure Boot: ENABLED (%s)",
             s_sb_setup_mode ? "Setup Mode" : "User Mode");
    } else {
        klog(LOG_INFO, "UEFI", "Secure Boot: DISABLED (%s)",
             s_sb_setup_mode ? "Setup Mode" : "User Mode");
    }

    klog(LOG_INFO, "UEFI", "Secure Boot keys: PK=%s, KEK=%s",
         s_sb_pk_present ? "enrolled" : "absent",
         s_sb_kek_present ? "enrolled" : "absent");

    /* Publish state to boot_info and global system state for
     * desktop/tray. Only publish when the read succeeded -- a failed
     * read leaves the fields at their zero-init values, but the
     * authoritative signal for downstream consumers is
     * caps_present & BOOT_CAP_SECURE_BOOT_STATE (which stays
     * degraded below when the read failed). */
    if (sb_val_valid) {
        g_boot_info.secure_boot_enabled = (uint8_t)s_sb_enabled;
        g_system_state.secure_boot       = (uint8_t)s_sb_enabled;
    }

    /* Promote BOOT_CAP_SECURE_BOOT_STATE from degraded to present ONLY
     * when the SecureBoot variable read actually succeeded. A failed
     * read leaves the state unknown -- publishing
     * secure_boot_enabled=0 alongside an "authoritative" cap bit would
     * turn an unreadable firmware query into a false "disabled"
     * answer for downstream attestation. Keep the cap degraded when
     * the read failed so consumers know to treat the state as
     * unknown. */
    if (sb_val_valid) {
        boot_caps_mark_present(BOOT_CAP_SECURE_BOOT_STATE);
    } else {
        klog(LOG_WARN, "UEFI",
             "SecureBoot variable read failed; cap stays degraded (state unknown)");
    }

    /* Canonical one-line summary consumed by monitoring tools */
    if (!sb_val_valid) {
        klog(LOG_WARN, "SecureBoot", "state=UNKNOWN (read failed)");
    } else if (s_sb_enabled) {
        klog(LOG_INFO, "SecureBoot", "state=ENABLED");
    } else {
        klog(LOG_INFO, "SecureBoot", "state=DISABLED (firmware or user override)");
    }

    /* Freeze the boot-time state vector so future revalidation passes
     * (S3 resume / periodic tick) can detect firmware drift. Capture
     * even on the unauthoritative path -- the revalidation logic gates
     * on snapshot.sb_state_valid before raising drift. */
    uefi_secureboot_snapshot();

    return BOOT_OK;
}

/* Called from registry_populate_defaults() after registry_init() -- writes
 * HKLM\SYSTEM\SecureBoot\State once the registry tree is ready. */
void uefi_secureboot_populate_registry(void)
{
    HKEY hKey;
    if (RegCreateKeyEx(HKEY_LOCAL_MACHINE, "SYSTEM\\SecureBoot", 0,
                       NULL, 0, KEY_WRITE, NULL, &hKey, NULL) == ERROR_SUCCESS) {
        const struct secureboot_db_info *dbi = secureboot_get_db_info();
        /* Codex review 2026-04-28 H1: gate State on read validity.
         * StateValid=0 means the SecureBoot variable read failed;
         * State is meaningless in that case. We write StateValid
         * always, but write State ONLY when valid. Re-adversarial
         * 2026-04-28 H1b: do NOT write a sentinel value for State on
         * the invalid path -- a truthy 0xFF would pollute the
         * existing State=0|1 boolean contract for legacy consumers.
         * Consumers MUST check StateValid first; if they read State
         * directly they get key-not-found (which they must handle
         * explicitly, not coerce to "false"). */
        RegSetDword(hKey, "StateValid",   (uint32_t)s_sb_state_valid);
        if (s_sb_state_valid) {
            RegSetDword(hKey, "State",    (uint32_t)s_sb_enabled);
        }
        RegSetDword(hKey, "SetupMode",   (uint32_t)s_sb_setup_mode);
        RegSetDword(hKey, "DeployedMode",(uint32_t)s_sb_deployed_mode);
        RegSetDword(hKey, "AuditMode",   (uint32_t)s_sb_audit_mode);
        RegSetDword(hKey, "PKEnrolled",  (uint32_t)s_sb_pk_present);
        RegSetDword(hKey, "KEKEnrolled", (uint32_t)s_sb_kek_present);
        /* Mirror db/dbx inventory from secureboot_keys_init() (S9) */
        if (dbi) {
            RegSetDword(hKey, "DbEntries",  dbi->db_entries);
            RegSetDword(hKey, "DbxEntries", dbi->dbx_entries);
            RegSetDword(hKey, "DbSha256",   dbi->db_sha256_count);
            RegSetDword(hKey, "DbxSha256",  dbi->dbx_sha256_count);
            RegSetDword(hKey, "DbX509",     dbi->db_x509_count);
        }
        /* MS UEFI CA generation tracking. ShimCA surfaces which
         * Microsoft Corporation UEFI CA the bundled shim binary is
         * signed against, for audit tools (msinfo32-equivalent /
         * security inventory / support diagnostics).
         *
         * Sentinel values (Codex design Q4 fix 2026-04-29):
         *   0          = shim binary not pinned in-tree (current
         *                state -- waiting on Microsoft to publish the
         *                2023-CA-signed shim)
         *   0xFFFFFFFF = shim present but sbverify could not identify
         *                the CA generation (build-time parse failure)
         *   2011|2023  = sbverify-confirmed CA year, embedded as a
         *                build-time constant SHA-bound to the pinned
         *                shim binary at image-build time
         *
         * Path forward when shim/shimx64.efi gets pinned: the build
         * script extracts the CA year via `sbverify --list` and writes
         * it into a generated header consumed here. See
         * docs/guides/secure-boot-keys.md "MS UEFI CA Lifecycle". */
        /* Codex adversarial H1 fix 2026-04-29: read the actual CA
         * year from the build-time generated header (extracted by
         * scripts/extract-shim-ca.sh from `sbverify --list shim/
         * shimx64.efi`). Reports 2011 / 2023 / 0xFFFFFFFF / 0 per
         * the sentinel doctrine above. */
        RegSetDword(hKey, "ShimCA", SHIM_CA_YEAR);
        RegCloseKey(hKey);
        klog(LOG_DEBUG, "SecureBoot",
             "HKLM\\SYSTEM\\SecureBoot: State=%u Db=%u Dbx=%u",
             (uint64_t)s_sb_enabled,
             dbi ? (uint64_t)dbi->db_entries : 0,
             dbi ? (uint64_t)dbi->dbx_entries : 0);
    }
}

int uefi_secureboot_enabled(void)  { return s_sb_enabled; }
int uefi_secureboot_setup_mode(void) { return s_sb_setup_mode; }
int uefi_secureboot_pk_present(void) { return s_sb_pk_present; }
int uefi_secureboot_kek_present(void) { return s_sb_kek_present; }

/* ----- Runtime Secure Boot revalidation (gap-audit 2026-05-01 M2) -----
 *
 * Boot-time snapshot of the authoritative SecureBoot state. After
 * uefi_secureboot_init() succeeds we freeze the state vector here;
 * uefi_secureboot_revalidate_tick() compares the current live values
 * against this snapshot and raises a LOG_FATAL + sets the registry
 * sentinel HKLM\SYSTEM\SecureBoot\Drift on any mismatch. A drift
 * signals firmware compromise, NVRAM corruption, or a physical
 * attacker clearing SetupMode while the OS slept.
 *
 * Concurrency: the s_sb_* statics are read/mutated by uefi_secureboot_*
 * paths only; uefi_secureboot_init() runs strictly before any thread
 * is created so the snapshot capture there does not race. After init,
 * uefi_secureboot_refresh() (S3 resume / periodic) can mutate and any
 * concurrent reader on another CPU could see a torn read. Serialize
 * the post-init refresh + comparison under s_sb_lock; the per-byte
 * accessors stay lock-free for legacy callers because torn reads on
 * a uint8_t-sized field are atomic on x86-64. */

struct sb_state_vector {
    int sb_state_valid; /* SecureBoot variable read succeeded */
    int sb_enabled;
    int setup_mode;
    int deployed_mode;
    int audit_mode;
    int pk_present;
    int kek_present;
};

static struct sb_state_vector s_sb_snapshot;
static int s_sb_snapshot_valid; /* 1 once uefi_secureboot_init captured the snapshot */

/* Drift detection is sticky once observed; registry publication is
 * tracked separately so a transient registry write failure on the
 * first tick does not permanently suppress the sentinel. Codex
 * adversarial 2026-05-01 H1 fix. */
static int s_sb_drift_detected;
static int s_sb_drift_published;
static DEFINE_SPINLOCK(s_sb_lock);

/* Tri-state byte read: returns 1 if `*out` was set from a definitive
 * SUCCESS read, 0 if the variable was definitively NOT_FOUND, -1 if
 * the read was indeterminate (UNSUPPORTED, transient firmware error,
 * SUCCESS with wrong size, etc.). Codex re-adversarial 2026-05-01 H2
 * fix: a -1 return must NOT be collapsed to "field is zero" by the
 * caller -- that would let a transient firmware hiccup trigger a
 * false drift event. */
static int read_global_byte_status(const uint16_t *name, uint8_t *out)
{
    struct boot_uefi_guid global = EFI_GLOBAL_VARIABLE_GUID;
    uint8_t val = 0;
    uint64_t sz = sizeof(val);
    uint32_t attrs = 0;

    efi_status_t status = uefi_get_variable(&global, name, &attrs, &sz, &val);
    if (status == UEFI_SUCCESS && sz == sizeof(val)) {
        *out = val;
        return 1;
    }
    if (status == UEFI_NOT_FOUND)
        return 0;
    return -1;
}

/* Tri-state existence check: returns 1 if the variable definitively
 * exists with non-zero data, 0 if it definitively does NOT exist
 * (UEFI_NOT_FOUND, or empty SUCCESS-with-sz=0 which the design
 * Codex review 2026-04-28 M3 treats as not-enrolled), -1 if the
 * result is indeterminate. Codex re-adversarial 2026-05-01 H2 fix:
 * distinguish NOT_FOUND from a read failure so drift detection can
 * not flip pk_present/kek_present from 1 to 0 on a transient
 * hiccup. */
static int global_var_exists_status(const uint16_t *name)
{
    struct boot_uefi_guid global = EFI_GLOBAL_VARIABLE_GUID;
    uint64_t sz = 0;
    uint32_t attrs = 0;

    efi_status_t status = uefi_get_variable(
        &global, name, &attrs, &sz, (void *)0);

    if (status == UEFI_BUFFER_TOO_SMALL && sz > 0) return 1;
    if (status == UEFI_SUCCESS && sz > 0)          return 1;
    if (status == UEFI_NOT_FOUND)                  return 0;
    if (status == UEFI_SUCCESS && sz == 0)         return 0;
    return -1;
}

/* Read every SecureBoot UEFI variable into a local state vector.
 * MUST be called WITHOUT s_sb_lock held -- uefi_get_variable()
 * acquires the sleepable s_rt_mutex via rt_call_enter(), and a
 * mutex must never be acquired under a spinlock with IRQs disabled
 * (Codex adversarial 2026-05-01 C1). The s_rt_mutex itself
 * serializes firmware calls. Returns 1 if EVERY tracked field was
 * read with a definitive status (vector is fully authoritative), 0
 * if any field's read was indeterminate (caller MUST skip drift
 * comparison and legacy accessor updates -- Codex re-adversarial
 * 2026-05-01 H2). */
static int uefi_secureboot_read_locked_state(struct sb_state_vector *out)
{
    static const uint16_t sb_name[]  = { 'S','e','c','u','r','e','B','o','o','t', 0 };
    static const uint16_t sm_name[]  = { 'S','e','t','u','p','M','o','d','e', 0 };
    static const uint16_t dm_name[]  = { 'D','e','p','l','o','y','e','d','M','o','d','e', 0 };
    static const uint16_t am_name[]  = { 'A','u','d','i','t','M','o','d','e', 0 };
    static const uint16_t pk_name[]  = { 'P','K', 0 };
    static const uint16_t kek_name[] = { 'K','E','K', 0 };

    uint8_t b;
    int s_sb, s_sm, s_dm, s_am, s_pk, s_kek;

    out->sb_state_valid = 0;
    out->sb_enabled     = 0;
    out->setup_mode     = 0;
    out->deployed_mode  = 0;
    out->audit_mode     = 0;
    out->pk_present     = 0;
    out->kek_present    = 0;

    s_sb = read_global_byte_status(sb_name, &b);
    if (s_sb == 1) {
        out->sb_enabled     = (b == 1) ? 1 : 0;
        out->sb_state_valid = 1;
    }

    s_sm = read_global_byte_status(sm_name, &b);
    if (s_sm == 1) out->setup_mode = (b == 1) ? 1 : 0;

    s_dm = read_global_byte_status(dm_name, &b);
    if (s_dm == 1) out->deployed_mode = (b == 1) ? 1 : 0;

    s_am = read_global_byte_status(am_name, &b);
    if (s_am == 1) out->audit_mode = (b == 1) ? 1 : 0;

    s_pk = global_var_exists_status(pk_name);
    if (s_pk >= 0) out->pk_present = s_pk;

    s_kek = global_var_exists_status(kek_name);
    if (s_kek >= 0) out->kek_present = s_kek;

    /* Authoritative iff every tracked read was definitive. Any
     * indeterminate read (-1) on any field disqualifies the vector
     * from drift comparison and legacy accessor publication. */
    if (s_sb < 0 || s_sm < 0 || s_dm < 0 || s_am < 0 ||
        s_pk < 0 || s_kek < 0)
        return 0;
    return 1;
}

void uefi_secureboot_snapshot(void)
{
    uint64_t flags;
    spin_lock_irqsave(&s_sb_lock, &flags);
    s_sb_snapshot.sb_state_valid = s_sb_state_valid;
    s_sb_snapshot.sb_enabled     = s_sb_enabled;
    s_sb_snapshot.setup_mode     = s_sb_setup_mode;
    s_sb_snapshot.deployed_mode  = s_sb_deployed_mode;
    s_sb_snapshot.audit_mode     = s_sb_audit_mode;
    s_sb_snapshot.pk_present     = s_sb_pk_present;
    s_sb_snapshot.kek_present    = s_sb_kek_present;
    s_sb_snapshot_valid          = 1;
    spin_unlock_irqrestore(&s_sb_lock, flags);
}

/* Write HKLM\SYSTEM\SecureBoot\Drift = 1 to flag firmware tampering
 * for monitoring tools. Returns 1 on success, 0 on failure -- the
 * caller uses the result to decide whether to retry on the next
 * tick (Codex adversarial 2026-05-01 H1: registry not yet ready
 * when the first drift is observed must not permanently suppress
 * the sentinel). */
static int uefi_secureboot_publish_drift(void)
{
    HKEY hKey;
    if (RegCreateKeyEx(HKEY_LOCAL_MACHINE, "SYSTEM\\SecureBoot", 0,
                       NULL, 0, KEY_WRITE, NULL, &hKey, NULL) != ERROR_SUCCESS)
        return 0;
    long err = RegSetDword(hKey, "Drift", 1);
    RegCloseKey(hKey);
    return err == ERROR_SUCCESS;
}

/* Read live UEFI state, compare against the boot snapshot, and
 * emit + publish a drift signal on first observed mismatch. Returns
 * 1 if drift was detected (this call OR any prior call -- the
 * detection is sticky), 0 otherwise. Returns 0 also when runtime
 * services are unavailable, the snapshot has not been captured, or
 * either read was unauthoritative -- those cases are silent so a
 * transient firmware hiccup does not raise a false alarm. */
static int uefi_secureboot_do_revalidate(void)
{
    struct sb_state_vector live;
    struct sb_state_vector snapshot_copy;
    uint64_t flags;
    int drifted_now = 0;
    int drift_was_already_detected;
    int needs_publish;
    int published_ok = 0;
    int live_authoritative;

    if (!s_available)
        return 0;

    /* Read firmware state OUTSIDE s_sb_lock. uefi_get_variable
     * acquires s_rt_mutex (sleepable) which must never run under a
     * spinlock with IRQs disabled. */
    live_authoritative = uefi_secureboot_read_locked_state(&live);

    spin_lock_irqsave(&s_sb_lock, &flags);

    if (!s_sb_snapshot_valid) {
        spin_unlock_irqrestore(&s_sb_lock, flags);
        return 0;
    }

    /* Publish live state to the legacy s_sb_* statics so
     * uefi_secureboot_enabled() etc. observe post-resume values --
     * but only when EVERY field was read with a definitive status
     * AND the SecureBoot variable read succeeded (Codex
     * re-adversarial 2026-05-01 H2: a transient firmware hiccup on
     * any non-SecureBoot field must not overwrite the previously
     * authoritative state). */
    if (live_authoritative && live.sb_state_valid) {
        s_sb_state_valid   = 1;
        s_sb_enabled       = live.sb_enabled;
        s_sb_setup_mode    = live.setup_mode;
        s_sb_deployed_mode = live.deployed_mode;
        s_sb_audit_mode    = live.audit_mode;
        s_sb_pk_present    = live.pk_present;
        s_sb_kek_present   = live.kek_present;
    }

    /* Boot snapshot was unauthoritative, live read had any
     * indeterminate field, or the live SecureBoot read failed: no
     * baseline / no comparable state -- skip the drift comparison.
     * The sticky s_sb_drift_detected flag is returned unchanged so
     * a real drift latched on a previous tick stays latched. */
    if (!s_sb_snapshot.sb_state_valid || !live_authoritative ||
        !live.sb_state_valid) {
        int sticky = s_sb_drift_detected;
        spin_unlock_irqrestore(&s_sb_lock, flags);
        return sticky;
    }

    if (live.sb_enabled      != s_sb_snapshot.sb_enabled    ||
        live.setup_mode      != s_sb_snapshot.setup_mode    ||
        live.deployed_mode   != s_sb_snapshot.deployed_mode ||
        live.audit_mode      != s_sb_snapshot.audit_mode    ||
        live.pk_present      != s_sb_snapshot.pk_present    ||
        live.kek_present     != s_sb_snapshot.kek_present) {
        drifted_now = 1;
    }

    drift_was_already_detected = s_sb_drift_detected;
    if (drifted_now)
        s_sb_drift_detected = 1;

    /* Retry registry publication on every call where drift is
     * latched but the sentinel write has not yet been confirmed.
     * Codex H1 fix 2026-05-01: prior version published only on the
     * detection edge; if that one write failed (e.g. registry not
     * yet ready) the sentinel was never retried. */
    needs_publish = s_sb_drift_detected && !s_sb_drift_published;
    snapshot_copy = s_sb_snapshot;

    spin_unlock_irqrestore(&s_sb_lock, flags);

    if (drifted_now && !drift_was_already_detected) {
        klog(LOG_FATAL, "SecureBoot",
             "DRIFT detected: boot snapshot SB=%u SM=%u DM=%u AM=%u PK=%u KEK=%u "
             "vs live SB=%u SM=%u DM=%u AM=%u PK=%u KEK=%u "
             "(firmware compromise, NVRAM corruption, or physical attack)",
             (uint64_t)snapshot_copy.sb_enabled,
             (uint64_t)snapshot_copy.setup_mode,
             (uint64_t)snapshot_copy.deployed_mode,
             (uint64_t)snapshot_copy.audit_mode,
             (uint64_t)snapshot_copy.pk_present,
             (uint64_t)snapshot_copy.kek_present,
             (uint64_t)live.sb_enabled,
             (uint64_t)live.setup_mode,
             (uint64_t)live.deployed_mode,
             (uint64_t)live.audit_mode,
             (uint64_t)live.pk_present,
             (uint64_t)live.kek_present);
    }

    if (needs_publish) {
        published_ok = uefi_secureboot_publish_drift();
        if (published_ok) {
            spin_lock_irqsave(&s_sb_lock, &flags);
            s_sb_drift_published = 1;
            spin_unlock_irqrestore(&s_sb_lock, flags);
        } else {
            klog(LOG_WARN, "SecureBoot",
                 "drift detected but registry publish failed; will retry next tick");
        }
    }

    return s_sb_drift_detected;
}

int uefi_secureboot_revalidate_tick(void)
{
    return uefi_secureboot_do_revalidate();
}

int uefi_secureboot_refresh(void)
{
    return uefi_secureboot_do_revalidate();
}

int uefi_secureboot_drift_detected(void)
{
    return s_sb_drift_detected;
}

/* Surface QueryVariableInfo() results to HKLM\SYSTEM\SecureBoot\Vars
 * so post-boot tools can see the firmware variable storage quota
 * (production firmware enforces ~64 KB per machine total). The
 * non-volatile + boot-services + runtime attribute combination is
 * the production-relevant slice (BS-only and runtime-only counters
 * are not separately tracked because Win32 GetFirmwareEnvironmentVariable
 * always uses the NV+BS+RT slice).
 *
 * Codex design review F3 (2026-04-29) drove the validity contract:
 * mirror the HKLM\SYSTEM\SecureBoot\State pattern -- always write
 * VarsValid (DWORD 0/1), write the size fields ONLY when QueryVariableInfo
 * succeeded. A missing size key is "did not query"; a present size
 * key is "this is the firmware-reported value". Consumers MUST check
 * VarsValid first. Sizes use REG_QWORD because the spec is UINT64.
 */
void uefi_runtime_populate_vars_registry(void)
{
    HKEY hKey;
    long rc = RegCreateKeyEx(HKEY_LOCAL_MACHINE,
                              "SYSTEM\\SecureBoot\\Vars", 0,
                              NULL, 0, KEY_WRITE, NULL, &hKey, NULL);
    if (rc != ERROR_SUCCESS) {
        klog(LOG_WARN, "UEFI",
             "Vars registry: RegCreateKeyEx failed");
        return;
    }

    uint64_t max_storage = 0;
    uint64_t remaining = 0;
    uint64_t max_var_size = 0;
    uint32_t attrs = EFI_VARIABLE_NON_VOLATILE |
                     EFI_VARIABLE_BOOTSERVICE_ACCESS |
                     EFI_VARIABLE_RUNTIME_ACCESS;
    uint64_t status = uefi_query_variable_info(attrs, &max_storage,
                                                &remaining, &max_var_size);

    if (status == UEFI_SUCCESS) {
        RegSetDword(hKey, "VarsValid", 1);
        RegSetQword(hKey, "MaxStorageSize",   max_storage);
        RegSetQword(hKey, "RemainingSize",    remaining);
        RegSetQword(hKey, "MaxVariableSize",  max_var_size);
        RegSetDword(hKey, "Attributes",       attrs);
        klog(LOG_INFO, "UEFI",
             "Vars registry: max=%u remain=%u max_var=%u",
             (uint32_t)max_storage, (uint32_t)remaining,
             (uint32_t)max_var_size);
    } else {
        RegSetDword(hKey, "VarsValid", 0);
        klog(LOG_INFO, "UEFI",
             "Vars registry: QueryVariableInfo unavailable (status=0x%x)",
             (uint64_t)status);
    }
    RegCloseKey(hKey);
}

/* ============================================================================
 * Secure Boot Key Management
 *
 * Reads and parses db/dbx/dbt signature databases.
 * Walking EFI_SIGNATURE_LIST chains to enumerate trust entries.
 * Authenticated writes (dbx update) deferred until crypto stack available.
 * ============================================================================ */

static struct secureboot_db_info s_db_info;

/* GUID comparison helper (reuse from uefi_config.c pattern) */
static int sb_guid_equal(const struct boot_uefi_guid *a,
                         const struct boot_uefi_guid *b)
{
    const uint8_t *pa = (const uint8_t *)a;
    const uint8_t *pb = (const uint8_t *)b;
    uint32_t i;
    for (i = 0; i < 16; i++)
        if (pa[i] != pb[i]) return 0;
    return 1;
}

/* Walk an EFI_SIGNATURE_LIST chain in a buffer, counting entries by type. */
static void count_sig_entries(const uint8_t *buf, uint64_t buf_sz,
                              uint32_t *total,
                              uint32_t *sha256_count,
                              uint32_t *x509_count)
{
    struct boot_uefi_guid sha256_type = EFI_CERT_SHA256_GUID;
    struct boot_uefi_guid x509_type   = EFI_CERT_X509_GUID;

    *total = 0;
    *sha256_count = 0;
    *x509_count = 0;

    uint64_t offset = 0;
    while (offset + sizeof(struct efi_signature_list) <= buf_sz) {
        const struct efi_signature_list *sl =
            (const struct efi_signature_list *)(buf + offset);

        if (sl->signature_list_size == 0) break;
        if (offset + sl->signature_list_size > buf_sz) break;

        /* Codex M1 (2026-04-27 re-review): firmware/NVRAM-supplied
         * sizes are untrusted. signature_list_size could be smaller
         * than header + signature_header_size, which would underflow
         * the subtraction below and fabricate a huge entries count.
         * Compute header_total as uint64 so a hostile
         * signature_header_size near UINT32_MAX cannot wrap before
         * the comparison. */
        uint64_t header_total = (uint64_t)sizeof(struct efi_signature_list)
            + (uint64_t)sl->signature_header_size;
        if ((uint64_t)sl->signature_list_size < header_total) break;
        if (sl->signature_size < sizeof(struct efi_signature_data)) break;
        uint32_t data_size = sl->signature_list_size - (uint32_t)header_total;
        /* data_size must be an exact multiple of signature_size for
         * a well-formed list -- treat any remainder as malformed. */
        if (data_size % sl->signature_size != 0) break;
        uint32_t entries = data_size / sl->signature_size;

        *total += entries;

        if (sb_guid_equal(&sl->signature_type, &sha256_type))
            *sha256_count += entries;
        else if (sb_guid_equal(&sl->signature_type, &x509_type))
            *x509_count += entries;

        offset += sl->signature_list_size;
    }
}

/* Read a security database variable and count its entries. */
static void read_security_db(const uint16_t *name,
                             uint32_t *total,
                             uint32_t *sha256_count,
                             uint32_t *x509_count)
{
    struct boot_uefi_guid db_guid = EFI_IMAGE_SECURITY_DATABASE_GUID;
    uint32_t attrs = 0;

    *total = 0;
    *sha256_count = 0;
    *x509_count = 0;

    /* First call with size=0 to get actual size */
    uint64_t sz = 0;
    efi_status_t status = uefi_get_variable(
        &db_guid, name, &attrs, &sz, (void *)0);

    if (status != UEFI_BUFFER_TOO_SMALL || sz == 0)
        return;  /* Variable doesn't exist or is empty */

    /* Use a static buffer -- security DBs are typically 1-4 KB in OVMF,
     * up to ~32 KB on real hardware with many entries.
     * We cap at 8 KB to avoid stack overflow. */
    if (sz > 8192) sz = 8192;

    uint8_t dbuf[8192];
    status = uefi_get_variable(&db_guid, name, &attrs, &sz, dbuf);
    if (status != UEFI_SUCCESS)
        return;

    count_sig_entries(dbuf, sz, total, sha256_count, x509_count);
}

void secureboot_keys_init(void)
{
    uint32_t i;
    uint8_t *p = (uint8_t *)&s_db_info;
    for (i = 0; i < (uint32_t)sizeof(s_db_info); i++)
        p[i] = 0;

    if (!s_available) return;

    /* Read db (Authorized Signature Database) */
    static const uint16_t db_name[] = { 'd','b', 0 };
    uint32_t db_sha = 0, db_x509 = 0;
    read_security_db(db_name, &s_db_info.db_entries, &db_sha, &db_x509);
    s_db_info.db_sha256_count = db_sha;
    s_db_info.db_x509_count = db_x509;

    /* Read dbx (Forbidden Signature Database) */
    static const uint16_t dbx_name[] = { 'd','b','x', 0 };
    uint32_t dbx_sha = 0, dbx_x509 = 0;
    read_security_db(dbx_name, &s_db_info.dbx_entries, &dbx_sha, &dbx_x509);
    s_db_info.dbx_sha256_count = dbx_sha;

    /* Read dbt (Timestamp Database) */
    static const uint16_t dbt_name[] = { 'd','b','t', 0 };
    uint32_t dbt_sha = 0, dbt_x509 = 0;
    read_security_db(dbt_name, &s_db_info.dbt_entries, &dbt_sha, &dbt_x509);

    /* Log summary */
    klog(LOG_INFO, "UEFI", "Secure Boot db: %u entries "
         "(%u X.509, %u SHA-256)",
         s_db_info.db_entries,
         s_db_info.db_x509_count,
         s_db_info.db_sha256_count);

    klog(LOG_INFO, "UEFI", "Secure Boot dbx: %u revocations "
         "(%u SHA-256)",
         s_db_info.dbx_entries,
         s_db_info.dbx_sha256_count);

    if (s_db_info.dbt_entries > 0) {
        klog(LOG_INFO, "UEFI", "Secure Boot dbt: %u timestamp entries",
             s_db_info.dbt_entries);
    }
}

const struct secureboot_db_info *secureboot_get_db_info(void)
{
    return &s_db_info;
}

/* ============================================================================
 * Crypto Agility (§5.3 -- UEFI 2.10)
 *
 * Reads the CryptoIndication variables to determine firmware algorithm
 * capabilities and active negotiated set.  These variables enable OS-driven
 * algorithm upgrades (e.g., SHA-256 → SHA-384) without firmware reflash.
 *
 * Variable names (all under EFI_GLOBAL_VARIABLE GUID):
 *   "CryptoIndicationsSupported" -- firmware lists everything it can do
 *   "CryptoIndications"          -- OS writes what it wants for next boot
 *   "CryptoIndicationsActivated" -- firmware confirms what's active now
 *
 * OVMF/EDK2 does not currently implement these (UEFI 2.10 is new), so
 * this will gracefully report "not available" on most test platforms.
 * ============================================================================ */

static struct crypto_agility_info s_crypto_info;

/* Read a uint32_t UEFI variable by UCS-2 name (global GUID). */
static uint32_t read_crypto_var(const uint16_t *name)
{
    struct boot_uefi_guid global = EFI_GLOBAL_VARIABLE_GUID;
    uint32_t attrs = 0;
    uint32_t val = 0;
    uint64_t sz = sizeof(val);
    efi_status_t status = uefi_get_variable(
        &global, name, &attrs, &sz, &val);
    if (status != UEFI_SUCCESS) return 0;
    return val;
}

/* Append algorithm name to buffer if bitmask bit is set. */
static int append_algo(char *buf, int pos, int max,
                       uint32_t mask, uint32_t bit, const char *name)
{
    if (!(mask & bit)) return pos;
    if (pos > 0 && pos < max - 1)
        buf[pos++] = '+';
    int i = 0;
    while (name[i] && pos < max - 1)
        buf[pos++] = name[i++];
    buf[pos] = '\0';
    return pos;
}

void uefi_crypto_agility_init(void)
{
    uint32_t i;
    uint8_t *p = (uint8_t *)&s_crypto_info;
    for (i = 0; i < (uint32_t)sizeof(s_crypto_info); i++)
        p[i] = 0;

    if (!s_available) return;

    /* Read CryptoIndicationsSupported (firmware-owned) */
    static const uint16_t name_sup[] = {
        'C','r','y','p','t','o','I','n','d','i','c','a','t','i','o','n','s',
        'S','u','p','p','o','r','t','e','d', 0 };
    s_crypto_info.supported = read_crypto_var(name_sup);

    /* If firmware doesn't support CryptoIndications, skip the rest */
    if (s_crypto_info.supported == 0) {
        klog(LOG_INFO, "UEFI",
             "Crypto agility: not available "
             "(firmware lacks UEFI 2.10 CryptoIndications)");
        return;
    }

    s_crypto_info.available = 1;

    /* Read CryptoIndications (OS-owned -- what we previously requested) */
    static const uint16_t name_req[] = {
        'C','r','y','p','t','o','I','n','d','i','c','a','t','i','o','n','s',
        0 };
    s_crypto_info.requested = read_crypto_var(name_req);

    /* Read CryptoIndicationsActivated (firmware-owned -- what's active now) */
    static const uint16_t name_act[] = {
        'C','r','y','p','t','o','I','n','d','i','c','a','t','i','o','n','s',
        'A','c','t','i','v','a','t','e','d', 0 };
    s_crypto_info.activated = read_crypto_var(name_act);

    /* Log what's active */
    char active_str[64];
    int pos = 0;
    active_str[0] = '\0';
    pos = append_algo(active_str, pos, 64,
                      s_crypto_info.activated,
                      CRYPTO_IND_RSA_4096_SHA512, "RSA-4096");
    pos = append_algo(active_str, pos, 64,
                      s_crypto_info.activated,
                      CRYPTO_IND_RSA_3072_SHA384, "RSA-3072");
    pos = append_algo(active_str, pos, 64,
                      s_crypto_info.activated,
                      CRYPTO_IND_ECDSA_P384, "ECDSA-P384");
    pos = append_algo(active_str, pos, 64,
                      s_crypto_info.activated,
                      CRYPTO_IND_ECDSA_P256, "ECDSA-P256");
    pos = append_algo(active_str, pos, 64,
                      s_crypto_info.activated,
                      CRYPTO_IND_RSA_2048_SHA256, "RSA-2048");
    pos = append_algo(active_str, pos, 64,
                      s_crypto_info.activated,
                      CRYPTO_IND_SHA384, "SHA-384");
    pos = append_algo(active_str, pos, 64,
                      s_crypto_info.activated,
                      CRYPTO_IND_SHA256, "SHA-256");
    (void)pos;

    if (active_str[0] != '\0') {
        klog(LOG_INFO, "UEFI",
             "Crypto agility: active [%s], %u supported, %u requested",
             active_str,
             s_crypto_info.supported,
             s_crypto_info.requested);
    } else {
        klog(LOG_INFO, "UEFI",
             "Crypto agility: supported=0x%x, none activated yet",
             s_crypto_info.supported);
    }

    /* TODO: When crypto policy engine is built, implement:
     *   1. Analyze supported bitmask to find strongest common set
     *   2. Write CryptoIndications to request upgrade (e.g., SHA-384 + RSA-3072)
     *   3. On next boot, firmware reads our request and activates it
     *   4. Check CryptoIndicationsActivated to confirm upgrade took effect */
}

const struct crypto_agility_info *uefi_crypto_agility_info(void)
{
    return &s_crypto_info;
}

/* ============================================================================
 * Capsule Firmware Update
 *
 * ╔══════════════════════════════════════════════════════════════════════╗
 * ║  ⚠️  DANGER -- READ EVERY WORD BEFORE MODIFYING THIS SECTION  ⚠️     ║
 * ╠══════════════════════════════════════════════════════════════════════╣
 * ║                                                                    ║
 * ║  UpdateCapsule() writes to SPI flash.  A bad capsule BRICKS the   ║
 * ║  motherboard.  There is NO software recovery -- you need a $5      ║
 * ║  CH341A SPI programmer and steady hands to solder an SOIC clip.   ║
 * ║                                                                    ║
 * ║  Real-world bricking scenarios:                                    ║
 * ║    • Wrong CapsuleGuid → firmware interprets data as wrong type   ║
 * ║    • Truncated capsule → partial flash write, CMOS gone           ║
 * ║    • Power loss mid-flash → half-written firmware image           ║
 * ║    • Unsigned capsule → attacker reflashes with rootkit firmware  ║
 * ║    • Version < LowestSupported → firmware rejects but may corrupt ║
 * ║                                                                    ║
 * ║  PREREQUISITES for safe UpdateCapsule() implementation:            ║
 * ║    1. OEM-signed capsule (PKCS#7/CMS with RSA-2048+ signature)   ║
 * ║    2. Kernel crypto stack for signature verification               ║
 * ║    3. ESRT FwClass GUID matching to verify capsule target         ║
 * ║    4. Version check against ESRT LowestSupportedFwVersion         ║
 * ║    5. AC power detection (ACPI battery/power supply status)       ║
 * ║    6. Explicit user confirmation with countdown timer             ║
 * ║    7. Pre-update NVRAM backup of current firmware settings        ║
 * ║                                                                    ║
 * ║  This implementation provides QUERY ONLY.                          ║
 * ║  UpdateCapsule() is NOT called, NOT exposed, NOT stubbed.          ║
 * ╚══════════════════════════════════════════════════════════════════════╝
 * ============================================================================ */

static struct capsule_capability_info s_capsule_info;

void uefi_capsule_init(void)
{
    uint32_t i;
    uint8_t *p = (uint8_t *)&s_capsule_info;
    for (i = 0; i < (uint32_t)sizeof(s_capsule_info); i++)
        p[i] = 0;

    if (!s_available || !s_rt) {
        klog(LOG_INFO, "UEFI",
             "Capsule updates: not available (no runtime services)");
        return;
    }

    /* Check if firmware advertises capsule support via the
     * EFI_RT_PROPERTIES_TABLE supported bitmask.
     *
     * This is the SAFE way to probe -- it only reads a previously-cached
     * bitmask (s_supported), no firmware calls are made.
     *
     * We deliberately do NOT call QueryCapsuleCapabilities() here because:
     *   • It requires a valid EFI_CAPSULE_HEADER array with a real CapsuleGuid
     *   • Using a dummy/zero GUID may confuse or crash some firmware
     *   • The RT_SUPPORTED flag tells us everything we need for capability
     *     reporting without any risk */
    if (s_supported & EFI_RT_SUPPORTED_UPDATE_CAPSULE) {
        s_capsule_info.supported = 1;

        /* Log with appropriate warnings */
        klog(LOG_INFO, "UEFI",
             "Capsule updates: firmware supports UpdateCapsule()");
        klog(LOG_DEBUG, "UEFI",
             "Capsule updates: write path not yet implemented "
             "(planned -- requires signed capsules + crypto verification)");

        /* TODO: When we have ESRT parsing + crypto stack, implement:
         *
         * Phase 1 -- Query (SAFE, read-only):
         *   For each ESRT entry, build a minimal EFI_CAPSULE_HEADER with
         *   the FwClass GUID and call QueryCapsuleCapabilities() to get
         *   max_capsule_size and reset_type for that firmware component.
         *
         * Phase 2 -- Validate (SAFE, no flash writes):
         *   Given a capsule file:
         *   a. Parse the capsule header (CapsuleGuid, size, flags)
         *   b. Verify CapsuleGuid matches an ESRT FwClass entry
         *   c. Extract embedded PKCS#7 signature
         *   d. Verify signature against db (Authorized Signature Database)
         *   e. Check capsule version >= ESRT LowestSupportedFwVersion
         *   f. Check AC power via ACPI
         *
         * Phase 3 -- Apply (DANGEROUS, writes firmware flash):
         *   a. Display user confirmation with 10-second countdown
         *   b. Allocate capsule in EfiRuntimeServicesData memory
         *   c. Set CAPSULE_FLAGS_PERSIST_ACROSS_RESET
         *   d. Call UpdateCapsule() -- firmware stages for next reboot
         *   e. Call ResetSystem(EfiResetCold) to trigger firmware update
         *   f. On next boot, read CapsuleResultVariable for status
         *
         * NEVER implement Phase 3 without Phase 2.  An unsignated capsule
         * write is a firmware rootkit delivery mechanism. */
    } else {
        klog(LOG_INFO, "UEFI",
             "Capsule updates: not supported by this firmware");
    }
}

int uefi_capsule_supported(void)
{
    return s_capsule_info.supported;
}

const struct capsule_capability_info *uefi_capsule_info(void)
{
    return &s_capsule_info;
}

/* ---- SSDT handlers: NtQuerySystemEnvironmentValue[Ex] / NtSetSystemEnvironmentValue[Ex] ---- */

/* User-marshalling bounds. UEFI variable names are short (typical
 * < 64 wide chars); UEFI 2.x permits values up to ~64 KiB but
 * production firmware caps the per-variable max around 32-64 KiB.
 * Codex Perf H1 (2026-04-27 re-review): the prior implementation
 * passed user pointers directly to firmware while holding the
 * global s_rt_mutex. A slow / unmapped / huge user buffer stalled
 * every other RT call. The marshalling cap below makes the firmware
 * call run against bounded kernel memory, so mutex hold time is a
 * function of the firmware itself + a bounded copy, not user
 * memory latency. */
#define UEFI_NAME_MAX_BYTES   1024  /* 512 wide chars + slack */
#define UEFI_VALUE_MAX_BYTES  (64 * 1024)
#define UEFI_KMALLOC_CAP      4096  /* CLAUDE.md kmalloc <=4 KB rule */

/* Codex H1 (2026-04-27 re-review): value buffers can reach 64 KiB;
 * kmalloc has no internal cap and would happily carve large blocks
 * out of the kernel heap, opening a DoS / fragmentation vector for
 * unprivileged firmware-variable syscalls. Route value buffers
 * through pmm_alloc_contiguous when they exceed the kmalloc-safe
 * ceiling. PMM frames are identity-mapped in the kernel range, so
 * the physical address doubles as a usable kernel pointer. The
 * allocated-frame count is recovered from size on free. */
#include "kernel/mm/pmm.h"

static void *uefi_value_alloc(uint32_t size)
{
    if (size == 0) return (void *)0;
    if (size <= UEFI_KMALLOC_CAP)
        return kmalloc(size);
    uint64_t frames = (size + PMM_FRAME_SIZE - 1) / PMM_FRAME_SIZE;
    uintptr_t phys = pmm_alloc_contiguous(frames);
    if (!phys) return (void *)0;
    return (void *)phys;
}

static void uefi_value_free(void *ptr, uint32_t size)
{
    if (!ptr) return;
    if (size <= UEFI_KMALLOC_CAP) {
        kfree(ptr);
        return;
    }
    uint64_t frames = (size + PMM_FRAME_SIZE - 1) / PMM_FRAME_SIZE;
    uintptr_t phys = (uintptr_t)ptr;
    for (uint64_t i = 0; i < frames; i++)
        pmm_free_frame(phys + i * PMM_FRAME_SIZE);
}

/* Marshal a user-supplied PWSTR (null-terminated wide string used
 * by the Ex variants). Probes for read, scans for the NUL within
 * UEFI_NAME_MAX_BYTES, kmallocs a kernel copy with explicit NUL.
 * Returns kernel buffer on success, sets *out_status; returns NULL
 * on any error (out_status carries the NTSTATUS). Caller frees. */
static uint16_t *marshal_user_pwstr_name(uint64_t user_ptr,
                                          NTSTATUS *out_status)
{
    if (!user_ptr) {
        *out_status = STATUS_INVALID_PARAMETER;
        return (uint16_t *)0;
    }
    /* Probe a small head region; we'll scan for NUL up to the cap. */
    if (ProbeForReadIfUser((const void *)user_ptr,
                            sizeof(uint16_t), sizeof(uint16_t)) != 0) {
        *out_status = STATUS_ACCESS_VIOLATION;
        return (uint16_t *)0;
    }
    /* Allocate the kernel copy at the cap; copy in chunks then NUL. */
    uint16_t *kbuf = (uint16_t *)kmalloc(UEFI_NAME_MAX_BYTES);
    if (!kbuf) {
        *out_status = STATUS_INSUFFICIENT_RESOURCES;
        return (uint16_t *)0;
    }
    /* Probe + copy the full cap; firmware tolerates an over-long
     * scan because we re-NUL-terminate based on the user's NUL. */
    if (ProbeForReadIfUser((const void *)user_ptr,
                            UEFI_NAME_MAX_BYTES,
                            sizeof(uint16_t)) != 0) {
        /* Codex H2 (2026-04-27 re-review): the prior fallback copied
         * 64-byte chunks without re-probing each chunk, so a name
         * pointer ending near the user/kernel boundary could pass
         * the head probe, fail the full probe, then have copy_from_user
         * read past MM_USER_PROBE_ADDRESS into kernel memory. Probe
         * EACH chunk before copy; reject if any chunk fails (NUL was
         * not within mapped user range). */
        uint32_t off;
        for (off = 0; off < UEFI_NAME_MAX_BYTES; off += 64) {
            uint32_t chunk = 64;
            if (off + chunk > UEFI_NAME_MAX_BYTES)
                chunk = UEFI_NAME_MAX_BYTES - off;
            if (ProbeForReadIfUser((const void *)(user_ptr + off),
                                     chunk, sizeof(uint16_t)) != 0)
                break;
            if (copy_from_user((char *)kbuf + off,
                               (const char *)user_ptr + off, chunk) != 0)
                break;
            /* Look for NUL within this chunk. */
            uint16_t *p = (uint16_t *)((char *)kbuf + off);
            uint32_t i;
            for (i = 0; i < chunk / 2; i++) {
                if (p[i] == 0) {
                    *out_status = STATUS_SUCCESS;
                    return kbuf;  /* found user NUL -- string complete */
                }
            }
        }
        /* No NUL within mapped range -- reject (avoids reading past
         * the user/kernel boundary). */
        kfree(kbuf);
        *out_status = STATUS_ACCESS_VIOLATION;
        return (uint16_t *)0;
    }
    /* Full region readable -- single copy, then verify NUL exists. */
    if (copy_from_user(kbuf, (const void *)user_ptr,
                       UEFI_NAME_MAX_BYTES) != 0) {
        kfree(kbuf);
        *out_status = STATUS_ACCESS_VIOLATION;
        return (uint16_t *)0;
    }
    uint32_t i;
    for (i = 0; i < UEFI_NAME_MAX_BYTES / 2; i++) {
        if (kbuf[i] == 0) {
            *out_status = STATUS_SUCCESS;
            return kbuf;
        }
    }
    kfree(kbuf);
    *out_status = STATUS_BUFFER_OVERFLOW;
    return (uint16_t *)0;
}

/* Marshal a user-supplied UNICODE_STRING (legacy NT variant).
 * Probes the descriptor for read, validates Length within
 * UEFI_NAME_MAX_BYTES, kmallocs a kernel copy of Length+2 bytes
 * (room for an explicit NUL since UNICODE_STRING is NOT
 * null-terminated by spec), copies the wide-char buffer in,
 * appends NUL. Returns kernel buffer; caller frees. */
static uint16_t *marshal_user_unicode_string(uint64_t user_ptr,
                                              uint32_t cap,
                                              NTSTATUS *out_status)
{
    if (!user_ptr) {
        *out_status = STATUS_INVALID_PARAMETER;
        return (uint16_t *)0;
    }
    UNICODE_STRING us;
    if (ProbeForReadIfUser((const void *)user_ptr, sizeof(us), 8) != 0) {
        *out_status = STATUS_ACCESS_VIOLATION;
        return (uint16_t *)0;
    }
    if (copy_from_user(&us, (const void *)user_ptr, sizeof(us)) != 0) {
        *out_status = STATUS_ACCESS_VIOLATION;
        return (uint16_t *)0;
    }
    if (us.Length == 0 || (us.Length & 1) != 0 || us.Length > cap) {
        *out_status = STATUS_INVALID_PARAMETER;
        return (uint16_t *)0;
    }
    if (!us.Buffer) {
        *out_status = STATUS_INVALID_PARAMETER;
        return (uint16_t *)0;
    }
    if (ProbeForReadIfUser(us.Buffer, us.Length, sizeof(uint16_t)) != 0) {
        *out_status = STATUS_ACCESS_VIOLATION;
        return (uint16_t *)0;
    }
    uint16_t *kbuf = (uint16_t *)kmalloc(us.Length + 2);
    if (!kbuf) {
        *out_status = STATUS_INSUFFICIENT_RESOURCES;
        return (uint16_t *)0;
    }
    if (copy_from_user(kbuf, us.Buffer, us.Length) != 0) {
        kfree(kbuf);
        *out_status = STATUS_ACCESS_VIOLATION;
        return (uint16_t *)0;
    }
    kbuf[us.Length / 2] = 0;
    *out_status = STATUS_SUCCESS;
    return kbuf;
}

/* NtQuerySystemEnvironmentValueEx(Name, VendorGuid, Value, ValueLength, Attributes)
 * SSDT 0x00D4 -- Win32 GetFirmwareEnvironmentVariableExW maps here.
 * Codex Perf H1 fix (2026-04-27 re-review): all user pointers are
 * marshalled into kernel-bounded copies BEFORE entering the
 * firmware path. Only the firmware call itself runs while
 * uefi_get_variable holds s_rt_mutex; user memory access happens
 * outside the lock window. */
static NTSTATUS nt_query_env_value_ex(uint64_t name_ptr, uint64_t guid_ptr,
                                       uint64_t value_ptr, uint64_t length_ptr,
                                       uint64_t attrs_ptr, uint64_t a6)
{
    NTSTATUS s;
    uint32_t requested_len;
    uint64_t actual_len;
    uint32_t attrs = 0;
    uint64_t efi_status;
    uint16_t *kname = (uint16_t *)0;
    void *kvalue = (void *)0;
    struct boot_uefi_guid kguid;
    NTSTATUS rc;

    (void)a6;
    if (!name_ptr || !guid_ptr || !value_ptr || !length_ptr)
        return STATUS_INVALID_PARAMETER;

    /* Probe + copy GUID (16 bytes) */
    if (ProbeForReadIfUser((const void *)guid_ptr, sizeof(kguid), 4) != 0)
        return STATUS_ACCESS_VIOLATION;
    if (copy_from_user(&kguid, (const void *)guid_ptr, sizeof(kguid)) != 0)
        return STATUS_ACCESS_VIOLATION;

    /* Probe + copy length (uint32_t, in/out) */
    if (ProbeForReadIfUser((const void *)length_ptr, sizeof(uint32_t), 4) != 0)
        return STATUS_ACCESS_VIOLATION;
    if (copy_from_user(&requested_len, (const void *)length_ptr,
                        sizeof(requested_len)) != 0)
        return STATUS_ACCESS_VIOLATION;
    if (requested_len > UEFI_VALUE_MAX_BYTES)
        return STATUS_INVALID_PARAMETER;

    /* Marshal name (PWSTR null-terminated wide string, Ex form) */
    kname = marshal_user_pwstr_name(name_ptr, &s);
    if (!kname)
        return s;

    /* Probe write capacity for the value buffer */
    if (requested_len > 0) {
        if (ProbeForWriteIfUser((void *)value_ptr, requested_len,
                                  sizeof(uint8_t)) != 0) {
            kfree(kname);
            return STATUS_ACCESS_VIOLATION;
        }
        kvalue = uefi_value_alloc(requested_len);
        if (!kvalue) {
            kfree(kname);
            return STATUS_INSUFFICIENT_RESOURCES;
        }
    }

    /* Probe write of length output (also handled by attrs probe below) */
    if (ProbeForWriteIfUser((void *)length_ptr, sizeof(uint32_t),
                              sizeof(uint32_t)) != 0) {
        uefi_value_free(kvalue, requested_len);
        kfree(kname);
        return STATUS_ACCESS_VIOLATION;
    }
    if (attrs_ptr) {
        if (ProbeForWriteIfUser((void *)attrs_ptr, sizeof(uint32_t),
                                  sizeof(uint32_t)) != 0) {
            uefi_value_free(kvalue, requested_len);
            kfree(kname);
            return STATUS_ACCESS_VIOLATION;
        }
    }

    /* Firmware call against kernel-bounded buffers */
    actual_len = requested_len;
    efi_status = uefi_get_variable(&kguid, kname, &attrs, &actual_len, kvalue);

    /* Codex (2026-04-27 final-adversarial): defend against buggy or
     * hostile firmware returning SUCCESS while inflating DataSize.
     * The kernel buffer is exactly requested_len bytes; if firmware
     * claims more, do NOT copy -- publish the size for the caller
     * to retry and downgrade to BUFFER_TOO_SMALL. */
    if (efi_status == UEFI_SUCCESS && actual_len > requested_len)
        efi_status = UEFI_BUFFER_TOO_SMALL;

    /* Copy results back */
    if (efi_status == UEFI_SUCCESS && kvalue && actual_len > 0) {
        if (copy_to_user((void *)value_ptr, kvalue, (uint32_t)actual_len) != 0)
            efi_status = UEFI_DEVICE_ERROR;
    }
    {
        uint32_t out_len = (uint32_t)actual_len;
        if (copy_to_user((void *)length_ptr, &out_len, sizeof(out_len)) != 0)
            efi_status = UEFI_DEVICE_ERROR;
    }
    if (attrs_ptr) {
        if (copy_to_user((void *)attrs_ptr, &attrs, sizeof(attrs)) != 0)
            efi_status = UEFI_DEVICE_ERROR;
    }
    rc = efi_status_to_ntstatus(efi_status);
    uefi_value_free(kvalue, requested_len);
    kfree(kname);
    return rc;
}

/* NtSetSystemEnvironmentValueEx(Name, VendorGuid, Value, ValueLength, Attributes)
 * SSDT 0x00D5 -- Win32 SetFirmwareEnvironmentVariableExW maps here. */
static NTSTATUS nt_set_env_value_ex(uint64_t name_ptr, uint64_t guid_ptr,
                                     uint64_t value_ptr, uint64_t length,
                                     uint64_t attrs, uint64_t a6)
{
    NTSTATUS s;
    uint16_t *kname = (uint16_t *)0;
    void *kvalue = (void *)0;
    struct boot_uefi_guid kguid;
    uint64_t efi_status;
    NTSTATUS rc;

    (void)a6;
    if (!name_ptr || !guid_ptr)
        return STATUS_INVALID_PARAMETER;
    if (length > UEFI_VALUE_MAX_BYTES)
        return STATUS_INVALID_PARAMETER;
    if (length > 0 && !value_ptr)
        return STATUS_INVALID_PARAMETER;

    if (ProbeForReadIfUser((const void *)guid_ptr, sizeof(kguid), 4) != 0)
        return STATUS_ACCESS_VIOLATION;
    if (copy_from_user(&kguid, (const void *)guid_ptr, sizeof(kguid)) != 0)
        return STATUS_ACCESS_VIOLATION;

    kname = marshal_user_pwstr_name(name_ptr, &s);
    if (!kname)
        return s;

    if (length > 0) {
        if (ProbeForReadIfUser((const void *)value_ptr, (uint32_t)length,
                                 sizeof(uint8_t)) != 0) {
            kfree(kname);
            return STATUS_ACCESS_VIOLATION;
        }
        kvalue = uefi_value_alloc((uint32_t)length);
        if (!kvalue) {
            kfree(kname);
            return STATUS_INSUFFICIENT_RESOURCES;
        }
        if (copy_from_user(kvalue, (const void *)value_ptr, (uint32_t)length) != 0) {
            uefi_value_free(kvalue, (uint32_t)length);
            kfree(kname);
            return STATUS_ACCESS_VIOLATION;
        }
    }

    efi_status = uefi_set_variable(&kguid, kname, (uint32_t)attrs,
                                    length, kvalue);
    rc = efi_status_to_ntstatus(efi_status);
    uefi_value_free(kvalue, (uint32_t)length);
    kfree(kname);
    return rc;
}

/* NtQuerySystemEnvironmentValue(VariableName, VariableValue, ValueLength, ReturnLength)
 * SSDT 0x00D2 -- legacy native NT ABI. VariableName is a PUNICODE_STRING
 * (Length / MaximumLength / Buffer triplet, NOT null-terminated by spec).
 * VariableValue is a raw output buffer of `length` bytes. ReturnLength is
 * an OUT USHORT pointer with the actual size. Implicit
 * EFI_GLOBAL_VARIABLE_GUID namespace (legacy form predates per-variable
 * GUIDs; Win32 callers wanting the GUID parameter use the Ex variant). */
static NTSTATUS nt_query_env_value(uint64_t name_ptr, uint64_t value_ptr,
                                    uint64_t length, uint64_t return_length_ptr,
                                    uint64_t a5, uint64_t a6)
{
    static const struct boot_uefi_guid global_guid = EFI_GLOBAL_VARIABLE_GUID;
    NTSTATUS s;
    uint16_t *kname;
    void *kvalue = (void *)0;
    uint64_t actual_len;
    uint32_t attrs = 0;
    uint64_t efi_status;
    NTSTATUS rc;

    (void)a5; (void)a6;
    if (!name_ptr || !return_length_ptr)
        return STATUS_INVALID_PARAMETER;
    if (length > UEFI_VALUE_MAX_BYTES || length > 0xFFFF)
        return STATUS_INVALID_PARAMETER;
    if (length > 0 && !value_ptr)
        return STATUS_INVALID_PARAMETER;

    kname = marshal_user_unicode_string(name_ptr, UEFI_NAME_MAX_BYTES, &s);
    if (!kname)
        return s;

    if (length > 0) {
        if (ProbeForWriteIfUser((void *)value_ptr, (uint32_t)length,
                                  sizeof(uint8_t)) != 0) {
            kfree(kname);
            return STATUS_ACCESS_VIOLATION;
        }
        kvalue = uefi_value_alloc((uint32_t)length);
        if (!kvalue) {
            kfree(kname);
            return STATUS_INSUFFICIENT_RESOURCES;
        }
    }
    if (ProbeForWriteIfUser((void *)return_length_ptr,
                              sizeof(uint16_t), sizeof(uint16_t)) != 0) {
        uefi_value_free(kvalue, (uint32_t)length);
        kfree(kname);
        return STATUS_ACCESS_VIOLATION;
    }

    actual_len = length;
    efi_status = uefi_get_variable(&global_guid, kname, &attrs,
                                     &actual_len, kvalue);

    /* Same firmware-trust defense as the Ex variant. */
    if (efi_status == UEFI_SUCCESS && actual_len > length)
        efi_status = UEFI_BUFFER_TOO_SMALL;

    if (efi_status == UEFI_SUCCESS && kvalue && actual_len > 0) {
        if (copy_to_user((void *)value_ptr, kvalue,
                          (uint32_t)actual_len) != 0)
            efi_status = UEFI_DEVICE_ERROR;
    }
    {
        uint16_t out_len = (uint16_t)(actual_len > 0xFFFF ? 0xFFFF
                                                          : actual_len);
        if (copy_to_user((void *)return_length_ptr, &out_len,
                          sizeof(out_len)) != 0)
            efi_status = UEFI_DEVICE_ERROR;
    }
    rc = efi_status_to_ntstatus(efi_status);
    uefi_value_free(kvalue, (uint32_t)length);
    kfree(kname);
    return rc;
}

/* NtSetSystemEnvironmentValue(VariableName, VariableValue) -- SSDT 0x00D3.
 * Both args are PUNICODE_STRING (the value's Length carries the bytes-to-write
 * count). Legacy form uses EFI_GLOBAL_VARIABLE_GUID and NV+BS+RT attrs (per
 * Windows native NT firmware-variable defaults). */
static NTSTATUS nt_set_env_value(uint64_t name_ptr, uint64_t value_ptr,
                                  uint64_t a3, uint64_t a4,
                                  uint64_t a5, uint64_t a6)
{
    static const struct boot_uefi_guid global_guid = EFI_GLOBAL_VARIABLE_GUID;
    /* NV (1) | BS (2) | RT (4) = 7 -- Windows native default for legacy
     * SetSystemEnvironmentValue per ntoskrnl convention. */
    static const uint32_t legacy_attrs = 7;
    NTSTATUS s;
    uint16_t *kname;
    void *kvalue = (void *)0;
    UNICODE_STRING value_us;
    uint64_t efi_status;
    NTSTATUS rc;

    (void)a3; (void)a4; (void)a5; (void)a6;
    if (!name_ptr || !value_ptr)
        return STATUS_INVALID_PARAMETER;

    kname = marshal_user_unicode_string(name_ptr, UEFI_NAME_MAX_BYTES, &s);
    if (!kname)
        return s;

    /* The legacy Set takes a UNICODE_STRING value, not a raw PWSTR.
     * The bytes-to-write are value_us.Length; treat them as opaque
     * UEFI variable bytes (which is what firmware expects). */
    if (ProbeForReadIfUser((const void *)value_ptr, sizeof(value_us), 8) != 0) {
        kfree(kname);
        return STATUS_ACCESS_VIOLATION;
    }
    if (copy_from_user(&value_us, (const void *)value_ptr,
                        sizeof(value_us)) != 0) {
        kfree(kname);
        return STATUS_ACCESS_VIOLATION;
    }
    /* value_us.Length is uint16_t (max 65535); UEFI_VALUE_MAX_BYTES
     * is 65536, so the type already enforces the strict cap. */
    if (value_us.Length > 0) {
        if (!value_us.Buffer) {
            kfree(kname);
            return STATUS_INVALID_PARAMETER;
        }
        if (ProbeForReadIfUser(value_us.Buffer, value_us.Length,
                                 sizeof(uint8_t)) != 0) {
            kfree(kname);
            return STATUS_ACCESS_VIOLATION;
        }
        kvalue = uefi_value_alloc(value_us.Length);
        if (!kvalue) {
            kfree(kname);
            return STATUS_INSUFFICIENT_RESOURCES;
        }
        if (copy_from_user(kvalue, value_us.Buffer, value_us.Length) != 0) {
            uefi_value_free(kvalue, value_us.Length);
            kfree(kname);
            return STATUS_ACCESS_VIOLATION;
        }
    }

    efi_status = uefi_set_variable(&global_guid, kname, legacy_attrs,
                                     value_us.Length, kvalue);
    rc = efi_status_to_ntstatus(efi_status);
    uefi_value_free(kvalue, value_us.Length);
    kfree(kname);
    return rc;
}

void uefi_register_ssdt(void)
{
    ssdt_register(SSDT_NtQuerySystemEnvironmentValue,
                  (SSDT_HANDLER)nt_query_env_value);
    ssdt_register(SSDT_NtSetSystemEnvironmentValue,
                  (SSDT_HANDLER)nt_set_env_value);
    ssdt_register(SSDT_NtQuerySystemEnvironmentValueEx,
                  (SSDT_HANDLER)nt_query_env_value_ex);
    ssdt_register(SSDT_NtSetSystemEnvironmentValueEx,
                  (SSDT_HANDLER)nt_set_env_value_ex);

    klog(LOG_INFO, "uefi",
         "Firmware variable syscalls registered (SSDT 0x%03X-0x%03X); "
         "user pointers marshalled to kernel buffers before firmware",
         (uint64_t)SSDT_NtQuerySystemEnvironmentValue,
         (uint64_t)SSDT_NtSetSystemEnvironmentValueEx);
}
