/* ============================================================================
 * version.c -- Kernel version information
 *
 * Provides runtime access to version strings from include/build_info.h,
 * which is auto-generated by the Makefile's build-info target.
 * ============================================================================ */

#include "kernel/version.h"
#include "kernel/klog.h"

/* Static version strings -- computed at compile time from macros */
static const char ver_full[]    = KERNEL_VERSION_STRING;
static const char ver_short[]   = KERNEL_VERSION_SHORT;
static const char ver_git[]     = BUILD_COMMIT;
static const char ver_branch[]  = BUILD_BRANCH;
static const char ver_time[]    = BUILD_TIMESTAMP;

const char *version_string(void)
{
    return ver_full;
}

const char *version_short(void)
{
    return ver_short;
}

const char *version_git_hash(void)
{
    return ver_git;
}

const char *version_branch(void)
{
    return ver_branch;
}

const char *version_timestamp(void)
{
    return ver_time;
}

uint32_t version_build_number(void)
{
    return VERSION_BUILD;
}

void version_print(void)
{
    klog(LOG_INFO, "kernel", "Impossible OS v%s (build %u, %s@%s, %s)",
         ver_short, (uint64_t)VERSION_BUILD, ver_branch, ver_git, ver_time);
}
