# ============================================================================
# Impossible OS — Root Makefile
# Target: x86-64, UEFI-only (GRUB + Multiboot2)
# ============================================================================

# Tools (LLVM toolchain — Clang is a universal cross-compiler via --target)
CC      := clang-19
HOST_CC := gcc
AS      := nasm
LD      := ld.lld-19
OBJCOPY := llvm-objcopy-19
AR      := llvm-ar-19

# --- Compiler / Linker Flags ---
CFLAGS  := --target=x86_64-elf \
           -Wall -Wextra -Werror \
           -ffreestanding -nostdlib -nostdinc \
           -fno-stack-protector -fno-pie \
           -mno-red-zone -mno-mmx -mno-sse -mno-sse2 \
           -mcmodel=kernel -std=gnu11 -O2 -g \
           -MMD -MP \
           -DCONFIG_SMP \
           -DKERNEL_TESTS
ASFLAGS := -f elf64 -g
LDFLAGS := -nostdlib -static -z max-page-size=0x1000

# --- Directories ---
SRC_DIR    := src
BUILD_DIR  := build
INCLUDE    := include
BOOT_DIR   := $(SRC_DIR)/boot
KERNEL_DIR := $(SRC_DIR)/kernel
LIBC_DIR   := $(SRC_DIR)/libc
DESKTOP_DIR:= $(SRC_DIR)/desktop

ISO_DIR    := $(BUILD_DIR)/isodir
ISO_FILE   := $(BUILD_DIR)/os-build.iso
KERNEL_BIN := $(BUILD_DIR)/kernel.exe
LINKER_SCRIPT := $(SRC_DIR)/boot/linker.ld

# --- QEMU Configuration (UEFI via OVMF) ---
QEMU        := qemu-system-x86_64
OVMF_CODE   := /usr/share/OVMF/OVMF_CODE_4M.fd
OVMF_VARS   := /usr/share/OVMF/OVMF_VARS_4M.fd
OVMF_VARS_CP:= $(BUILD_DIR)/OVMF_VARS_4M.fd

# --- Version Information ---
# CalVer: YY.M.D (auto-generated from build date, no manual bumps needed)
BUILD_NUM_FILE := .build_number
VERSION_MAJOR  := $(shell date -u '+%y')
VERSION_MINOR  := $(shell date -u '+%-m')
VERSION_PATCH  := $(shell date -u '+%-d')
VERSION_RAW    := $(VERSION_MAJOR).$(VERSION_MINOR).$(VERSION_PATCH)
BUILD_NUMBER   := $(or $(shell cat $(BUILD_NUM_FILE) 2>/dev/null | tr -d '[:space:]'),0)
GIT_HASH       := $(shell git rev-parse --short=8 HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH     := $(shell git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
BUILD_TIME     := $(shell date -u '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null || echo "unknown")

# Generated header with all version/build metadata
BUILD_INFO_H   := include/build_info.h

# Generate include/build_info.h — always run the recipe (.FORCE), but only
# overwrite the file when contents change (cmp -s) to avoid full recompilation.
.FORCE:
$(BUILD_INFO_H): .FORCE
	@mkdir -p $(dir $(BUILD_INFO_H))
	@echo '/* Auto-generated by Makefile — DO NOT EDIT */' > $(BUILD_INFO_H).tmp
	@echo '#pragma once' >> $(BUILD_INFO_H).tmp
	@echo '' >> $(BUILD_INFO_H).tmp
	@echo '#define VERSION_MAJOR   $(VERSION_MAJOR)' >> $(BUILD_INFO_H).tmp
	@echo '#define VERSION_MINOR   $(VERSION_MINOR)' >> $(BUILD_INFO_H).tmp
	@echo '#define VERSION_PATCH   $(VERSION_PATCH)' >> $(BUILD_INFO_H).tmp
	@echo '#define VERSION_BUILD   $(BUILD_NUMBER)' >> $(BUILD_INFO_H).tmp
	@echo '#define BUILD_NUMBER    $(BUILD_NUMBER)' >> $(BUILD_INFO_H).tmp
	@echo '#define BUILD_VERSION   "$(VERSION_RAW)"' >> $(BUILD_INFO_H).tmp
	@echo '#define BUILD_COMMIT    "$(GIT_HASH)"' >> $(BUILD_INFO_H).tmp
	@echo '#define BUILD_BRANCH    "$(GIT_BRANCH)"' >> $(BUILD_INFO_H).tmp
	@echo '#define BUILD_TIMESTAMP "$(BUILD_TIME)"' >> $(BUILD_INFO_H).tmp
	@echo '#define VERSION_GIT_HASH "$(GIT_HASH)"' >> $(BUILD_INFO_H).tmp
	@if ! cmp -s $(BUILD_INFO_H).tmp $(BUILD_INFO_H) 2>/dev/null; then \
		mv $(BUILD_INFO_H).tmp $(BUILD_INFO_H); \
		echo "[GEN] $(BUILD_INFO_H) (v$(VERSION_RAW) build $(BUILD_NUMBER), $(GIT_BRANCH)@$(GIT_HASH))"; \
	else \
		rm -f $(BUILD_INFO_H).tmp; \
	fi

# --- Source Discovery ---
# Assembly sources (boot + kernel) — exclude ap_trampoline.asm (built separately as flat binary)
ASM_SRCS := $(shell find $(BOOT_DIR) $(KERNEL_DIR) -name '*.asm' ! -name 'ap_trampoline.asm' 2>/dev/null)
ASM_OBJS := $(patsubst $(SRC_DIR)/%.asm, $(BUILD_DIR)/%.o, $(ASM_SRCS))

# AP trampoline: assembled as flat binary, then converted to linkable ELF object
AP_TRAMPOLINE_BIN := $(BUILD_DIR)/kernel/smp/ap_trampoline.bin
AP_TRAMPOLINE_OBJ := $(BUILD_DIR)/kernel/smp/ap_trampoline.o

# C sources (kernel + libc + vendored libs)
LIBS_DIR   := $(SRC_DIR)/libs
C_SRCS   := $(shell find $(KERNEL_DIR) $(LIBC_DIR) $(LIBS_DIR) $(DESKTOP_DIR) -name '*.c' 2>/dev/null)
C_OBJS   := $(patsubst $(SRC_DIR)/%.c, $(BUILD_DIR)/%.o, $(C_SRCS))

# All objects
OBJS     := $(ASM_OBJS) $(C_OBJS) $(AP_TRAMPOLINE_OBJ)

# Generated headers — must exist before any C compilation starts (-j safe)
GENERATED_HDRS := include/build_info.h include/kernel/os_logo.h src/kernel/bsod_icon.h src/kernel/boot_splash_font_data.h

# ============================================================================
# Targets
# ============================================================================

.PHONY: all _increment_build boot boot-icon boot-font kernel host-tools sysroot userland iso uefi-boot sign-efi system-disk test-disks run run-test run-debug run-log run-usb-ci run-nvme run-nvme-ci clean assets validate-assets sysroot-dirs sysroot-fonts sysroot-wallpapers sysroot-cursors sysroot-icons test-mm test-fs test-ob test-security test-ipc test-sched test-boot test-abi test-storage test-exec test-x86 test-desktop test-visual update-ui-refs boot-info-abi test-boot-info-abi test-tooling test-ai-system

## all: Build everything (kernel + userland + system disk + boot_info ABI manifest)
all: _increment_build check-abi assets kernel userland uefi-boot boot-info-abi post16-manifest system-disk
	@echo "[VERSION] Impossible OS v$(VERSION_RAW).$(BUILD_NUMBER) ($(GIT_BRANCH)@$(GIT_HASH), $(BUILD_TIME))"

## assets: Unified asset pipeline — validate + generate headers + populate sysroot
assets: validate-assets os-logo bsod-icon boot-font sysroot-fonts sysroot-wallpapers sysroot-cursors sysroot-icons
	@echo "[ASSETS] All assets up to date"

## validate-assets: Check all source assets are well-formed before conversion
validate-assets:
	@python3 tools/validate-assets.py

## _increment_build: Auto-increment the build number
_increment_build:
	@expr $$(cat $(BUILD_NUM_FILE) 2>/dev/null || echo 0) + 1 > $(BUILD_NUM_FILE)
	@echo "[BUILD] #$$(cat $(BUILD_NUM_FILE))"

## uefi-boot: Build custom UEFI bootloader (replaces GRUB)
UEFI_EFI := $(BUILD_DIR)/tools/BOOTX64.EFI

uefi-boot: $(UEFI_EFI)

$(UEFI_EFI): src/boot/uefi/bootx64.c src/boot/uefi/efi.h src/boot/uefi/uefi.lds
	@mkdir -p $(BUILD_DIR)/tools
	$(MAKE) -C src/boot/uefi OUTDIR=$(CURDIR)/$(BUILD_DIR)/tools
	@echo "[EFI] $@ created ($$(wc -c < $@ | tr -d ' ') bytes)"

## sign-efi: Sign BOOTX64.EFI with MOK private key (skipped if keys/MOK.key absent)
MOK_KEY := keys/MOK.key
MOK_CRT := keys/MOK.cer

sign-efi: $(UEFI_EFI)
	@if [ -f "$(MOK_KEY)" ]; then \
		echo "[SIGN] Signing $(UEFI_EFI) with MOK..."; \
		sbsign --key $(MOK_KEY) --cert $(MOK_CRT) \
			--output $(UEFI_EFI).tmp $(UEFI_EFI); \
		sbverify --cert $(MOK_CRT) $(UEFI_EFI).tmp \
			&& echo "[SIGN] Signature verified OK" \
			|| { rm -f $(UEFI_EFI).tmp; echo "[SIGN] ERROR: signature verification FAILED"; exit 1; }; \
		mv $(UEFI_EFI).tmp $(UEFI_EFI); \
	else \
		echo "[SIGN] keys/MOK.key not found -- skipping signing (dev build)"; \
	fi

## os-logo: Generate shared OS logo header from PNG
os-logo: include/kernel/os_logo.h

include/kernel/os_logo.h: $(wildcard resources/logo/os_logo_*.png) tools/convert_icon.py
	@python3 tools/convert_icon.py

## bsod-icon: Generate BSOD icon header from PNG
bsod-icon: src/kernel/bsod_icon.h

src/kernel/bsod_icon.h: resources/system/bsod.png tools/convert_bsod_icon.py
	@python3 tools/convert_bsod_icon.py

## boot-font: Generate embedded TTF font header for boot splash
boot-font: src/kernel/boot_splash_font_data.h

src/kernel/boot_splash_font_data.h: resources/fonts/selawksb.ttf tools/convert_boot_font.py
	@python3 tools/convert_boot_font.py

## boot: Assemble the bootloader
boot: $(ASM_OBJS)
	@echo "[BOOT] Bootloader objects built"

## kernel: Compile and link the kernel ELF
kernel: $(KERNEL_BIN)
	@echo "[KERNEL] $(KERNEL_BIN) built"

$(KERNEL_BIN): os-logo bsod-icon boot-font $(OBJS) $(LINKER_SCRIPT)
	@mkdir -p $(dir $@)
	$(LD) $(LDFLAGS) -T $(LINKER_SCRIPT) -o $@ $(OBJS)
	@echo "[LD] Linked $@"
	@llvm-nm-19 -n $@ > $(BUILD_DIR)/kernel.map
	@python3 tools/convert_symmap.py $(BUILD_DIR)/kernel.map $(BUILD_DIR)/kernel.sym
	@echo "[NM] Symbol map: $(BUILD_DIR)/kernel.map"

## host-tools: Build host utility programs (jpg2raw, irespack, etc.)
host-tools: $(BUILD_DIR)/tools/jpg2raw $(BUILD_DIR)/tools/irespack

$(BUILD_DIR)/tools/jpg2raw: tools/jpg2raw.c
	@mkdir -p $(BUILD_DIR)/tools
	$(HOST_CC) -O2 -o $@ $< -lm -Itools
	@echo "[TOOL] $@ built"

$(BUILD_DIR)/tools/irespack: tools/irespack.c
	@mkdir -p $(BUILD_DIR)/tools
	$(HOST_CC) -O2 -o $@ $< -lm -Itools
	@echo "[TOOL] $@ built"

## boot-info-abi: Build kernel + mirror ABI manifest dumpers, emit JSON, and
##                diff them. Fails the build on any field / offset / size drift
##                between include/kernel/boot_info.h and
##                src/boot/uefi/boot_info_mirror.h. The static asserts in those
##                headers remain as the compile-time first line of defense;
##                this target catches same-size reorders the asserts miss.
BOOT_ABI_KERNEL_JSON := $(BUILD_DIR)/boot-info-abi.kernel.json
BOOT_ABI_MIRROR_JSON := $(BUILD_DIR)/boot-info-abi.mirror.json
BOOT_ABI_DUMPER_K    := $(BUILD_DIR)/tools/dump-boot-info-kernel
BOOT_ABI_DUMPER_M    := $(BUILD_DIR)/tools/dump-boot-info-mirror
BOOT_ABI_HEADERS     := include/kernel/boot_info.h include/kernel/types.h \
                        include/kernel/boot_init.h src/boot/uefi/boot_info_mirror.h

$(BOOT_ABI_DUMPER_K): tools/boot-info-manifest/dump-kernel.c \
                      tools/boot-info-manifest/dump-common.h \
                      tools/boot-info-manifest/dump-fields.inc \
                      include/kernel/boot_info.h include/kernel/types.h \
                      include/kernel/boot_init.h
	@mkdir -p $(BUILD_DIR)/tools
	$(HOST_CC) -O2 -I include -I tools/boot-info-manifest -o $@ $<
	@echo "[TOOL] $@ built"

$(BOOT_ABI_DUMPER_M): tools/boot-info-manifest/dump-mirror.c \
                      tools/boot-info-manifest/dump-common.h \
                      tools/boot-info-manifest/dump-fields.inc \
                      src/boot/uefi/boot_info_mirror.h
	@mkdir -p $(BUILD_DIR)/tools
	$(HOST_CC) -O2 -I src/boot/uefi -I tools/boot-info-manifest -o $@ $<
	@echo "[TOOL] $@ built"

boot-info-abi: $(BOOT_ABI_KERNEL_JSON) $(BOOT_ABI_MIRROR_JSON)
	@bash tools/boot-info-manifest/compare.sh $(BOOT_ABI_KERNEL_JSON) $(BOOT_ABI_MIRROR_JSON)

$(BOOT_ABI_KERNEL_JSON): $(BOOT_ABI_DUMPER_K)
	@$< > $@

$(BOOT_ABI_MIRROR_JSON): $(BOOT_ABI_DUMPER_M)
	@$< > $@

## test-boot-info-abi: Regress-test the drift detector itself. Builds
##                    intentionally-mutated mirror fixtures and verifies
##                    compare.sh reports the expected first-mismatch field.
##                    Depends on the real kernel JSON being up to date.
test-boot-info-abi: $(BOOT_ABI_KERNEL_JSON)
	@bash tools/boot-info-manifest/test-drift-detection.sh

## test-tooling: Run scripts/test-tooling.sh -- the host-side developer
##               tooling regression pack (wrapper --help contract, hook
##               lifecycle on a throwaway git repo, workflow YAML sanity,
##               stale-command rejection in operator docs, supported-host
##               profile matrix, build/test sentinel contract). Fast; no
##               OS build or kernel test-run required.
test-tooling:
	@bash scripts/test-tooling.sh

## test-ai-system: Run scripts/test-ai-system.sh -- AI workflow regression
##                 pack (Authority Hierarchy, Claude-Code-only declaration,
##                 AGENTS.md file contract, zero-trailer commit policy,
##                 autonomous-agent boundary, skill catalog sync, doctrine
##                 presence, index-link integrity, no-Cursor-residue, no-
##                 parallel-skill-trees, settings.json JSON parse, Copilot
##                 subordinate-role check). Fast; docs + git-log scans only.
test-ai-system:
	@bash scripts/test-ai-system.sh

## post16-manifest: Emit build/post16-manifest.env listing every POST16_*
##                  #define from include/kernel/boot_init.h + src/boot/uefi/
##                  bootx64.c, plus a POST16_REQUIRED array of codes the
##                  smoke test asserts on serial. Fails the build on name
##                  collisions or stale required-set entries. Sourced by
##                  scripts/test-smoke.sh.
POST16_MANIFEST := $(BUILD_DIR)/post16-manifest.env
POST16_SOURCES  := include/kernel/boot_init.h src/boot/uefi/bootx64.c \
                   tools/post16-manifest/generate.sh

post16-manifest: $(POST16_MANIFEST)

$(POST16_MANIFEST): $(POST16_SOURCES)
	@BUILD_DIR=$(BUILD_DIR) bash tools/post16-manifest/generate.sh

## sysroot: Populate build/sysroot/ with system files and assets
SYSROOT := $(BUILD_DIR)/sysroot
sysroot: sysroot-dirs sysroot-fonts sysroot-wallpapers sysroot-cursors sysroot-icons

# --- Cursor source files (Adwaita XCursor format) ---
CURSOR_SRCS := resources/cursors/default resources/cursors/pointer \
               resources/cursors/text resources/cursors/fleur \
               resources/cursors/sb_v_double_arrow resources/cursors/sb_h_double_arrow \
               resources/cursors/bd_double_arrow resources/cursors/fd_double_arrow \
               resources/cursors/progress resources/cursors/crosshair \
               resources/cursors/not-allowed

# --- Font source files (TTF only, skip LICENSE-*) ---
FONT_SRCS := $(wildcard resources/fonts/*.ttf)

# --- Icon PNG sources (48px used as IRES trigger) ---
ICON_SRCS := $(wildcard resources/icons/color/48/*.png)

## sysroot-dirs: Create the standard directory tree + static files
$(SYSROOT)/.dirs-stamp:
	@mkdir -p $(SYSROOT)
	@mkdir -p $(SYSROOT)/Impossible/System/Config/Registry
	@mkdir -p $(SYSROOT)/Impossible/System32
	@mkdir -p $(SYSROOT)/Impossible/Fonts
	@mkdir -p $(SYSROOT)/Impossible/Icons
	@mkdir -p $(SYSROOT)/Impossible/Web/Wallpaper
	@mkdir -p $(SYSROOT)/Impossible/System/Cursors
	@mkdir -p $(SYSROOT)/Impossible/Media
	@mkdir -p $(SYSROOT)/Impossible/Temp
	@mkdir -p $(SYSROOT)/Users/Default/Desktop
	@mkdir -p $(SYSROOT)/Users/Default/Documents
	@mkdir -p $(SYSROOT)/Users/Default/Downloads
	@mkdir -p $(SYSROOT)/Users/Default/Pictures
	@mkdir -p $(SYSROOT)/Recycle
	@mkdir -p "$(SYSROOT)/Program Files"
	@mkdir -p $(SYSROOT)/tests
	@echo -n "Hello from Impossible OS!" > $(SYSROOT)/hello.txt
	@echo -n "IXFS root filesystem" > $(SYSROOT)/readme.txt
	@touch $@
	@echo "[SYSROOT] Directory tree created"

sysroot-dirs: $(SYSROOT)/.dirs-stamp

## sysroot-fonts: Copy bundled TrueType fonts → sysroot/Impossible/Fonts/
$(SYSROOT)/Impossible/Fonts/.stamp: $(FONT_SRCS) | $(SYSROOT)/.dirs-stamp
	@cp resources/fonts/*.ttf $(SYSROOT)/Impossible/Fonts/
	@touch $@
	@echo "[ASSETS] Fonts copied ($(words $(FONT_SRCS)) TTF files)"

sysroot-fonts: $(SYSROOT)/Impossible/Fonts/.stamp

## sysroot-wallpapers: Copy wallpaper JPEG → sysroot (decoded at runtime)
$(SYSROOT)/Impossible/Web/Wallpaper/default.jpg: resources/backgrounds/background.jpg | $(SYSROOT)/.dirs-stamp
	@cp $< $@
	@echo "[ASSETS] Wallpaper copied"

sysroot-wallpapers: $(SYSROOT)/Impossible/Web/Wallpaper/default.jpg

## sysroot-cursors: Copy Adwaita XCursor files → sysroot
$(SYSROOT)/Impossible/System/Cursors/.stamp: $(CURSOR_SRCS) | $(SYSROOT)/.dirs-stamp
	@cp $(CURSOR_SRCS) $(SYSROOT)/Impossible/System/Cursors/
	@touch $@
	@echo "[ASSETS] Cursors copied ($(words $(CURSOR_SRCS)) Adwaita XCursor)"

sysroot-cursors: $(SYSROOT)/Impossible/System/Cursors/.stamp

## sysroot-icons: Pack color icons into IRES archive → sysroot
$(SYSROOT)/Impossible/Icons/icons.ires: $(ICON_SRCS) host-tools | $(SYSROOT)/.dirs-stamp
	@if [ -n "$(ICON_SRCS)" ]; then \
		$(BUILD_DIR)/tools/irespack $(BUILD_DIR)/icons.ires resources/icons/color 2>&1; \
		cp $(BUILD_DIR)/icons.ires $@; \
		echo "[ASSETS] icons.ires packed and copied"; \
	else \
		echo "[ASSETS] No color icons found — skipping icons.ires"; \
	fi

sysroot-icons: $(SYSROOT)/Impossible/Icons/icons.ires

## userland: Build user-mode programs and copy into sysroot
USER_CFLAGS := --target=x86_64-elf \
               -Wall -Wextra -Werror -ffreestanding -nostdlib -nostdinc \
               -fno-stack-protector -fno-pie -mno-red-zone \
               -mno-mmx -mno-sse -mno-sse2 -std=gnu11 -O2 -g \
               -MMD -MP

userland: $(SYSROOT)/hello.exe $(SYSROOT)/cmd.exe $(SYSROOT)/test_harness_smoke.exe $(SYSROOT)/test_syscall.exe $(SYSROOT)/test_faultinject.exe $(SYSROOT)/test_smoke_boot.exe $(SYSROOT)/test_stress_libc.exe $(SYSROOT)/test_perf_syscall.exe $(SYSROOT)/test_libc.exe $(SYSROOT)/test_ipc.exe $(SYSROOT)/test_process.exe $(SYSROOT)/test_fileio.exe $(SYSROOT)/test_win32.exe $(SYSROOT)/test_loader_elf.exe $(SYSROOT)/test_loader_pe.exe $(SYSROOT)/test_loader_eif.exe $(SYSROOT)/test_fastpath.exe $(SYSROOT)/test_fastpath_fuzz.exe

$(SYSROOT)/hello.exe $(SYSROOT)/cmd.exe $(SYSROOT)/test_harness_smoke.exe $(SYSROOT)/test_syscall.exe $(SYSROOT)/test_faultinject.exe $(SYSROOT)/test_smoke_boot.exe $(SYSROOT)/test_stress_libc.exe $(SYSROOT)/test_perf_syscall.exe $(SYSROOT)/test_libc.exe $(SYSROOT)/test_ipc.exe $(SYSROOT)/test_process.exe $(SYSROOT)/test_fileio.exe $(SYSROOT)/test_win32.exe $(SYSROOT)/test_loader_elf.exe $(SYSROOT)/test_loader_pe.exe $(SYSROOT)/test_loader_eif.exe $(SYSROOT)/test_fastpath.exe $(SYSROOT)/test_fastpath_fuzz.exe &: sysroot user/hello.c user/cmd.c \
                                                                              user/test/test_harness_smoke.c \
                                                                              user/test/test_syscall.c \
                                                                              user/test/test_faultinject.c \
                                                                              user/test/test_smoke_boot.c \
                                                                              user/test/test_stress_libc.c \
                                                                              user/test/test_perf_syscall.c \
                                                                              user/test/test_libc.c \
                                                                              user/test/test_ipc.c \
                                                                              user/test/test_process.c \
                                                                              user/test/test_fileio.c \
                                                                              user/test/test_win32.c \
                                                                              user/test/test_loader_elf.c \
                                                                              user/test/test_loader_pe.c \
                                                                              user/test/test_loader_eif.asm \
                                                                              user/test/test_fastpath.c \
                                                                              user/test/test_fastpath_fuzz.c \
                                                                              scripts/build-eif.py \
                                                                              user/include/test.h \
                                                                              user/include/syscall.h \
                                                                              user/include/abi_numbers.h \
                                                                              user/include/teb.h \
                                                                              user/include/kusd.h \
                                                                              user/include/win32.h \
                                                                              user/lib/crt0.asm \
                                                                              user/lib/string.c user/lib/stdlib.c user/lib/stdio.c \
                                                                              user/lib/ctype.c user/lib/math.c \
                                                                              user/lib/win32.c user/lib/crt_init.c user/user.ld
	@mkdir -p $(BUILD_DIR)/user/lib $(BUILD_DIR)/user/test
	$(AS) -f elf64 -g user/lib/crt0.asm -o $(BUILD_DIR)/user/lib/crt0.o
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/lib/string.c -o $(BUILD_DIR)/user/lib/string.o
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/lib/stdlib.c -o $(BUILD_DIR)/user/lib/stdlib.o
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/lib/stdio.c -o $(BUILD_DIR)/user/lib/stdio.o
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/lib/ctype.c -o $(BUILD_DIR)/user/lib/ctype.o
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/lib/math.c -o $(BUILD_DIR)/user/lib/math.o
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/lib/win32.c -o $(BUILD_DIR)/user/lib/win32.o
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/lib/crt_init.c -o $(BUILD_DIR)/user/lib/crt_init.o
	$(AR) rcs $(BUILD_DIR)/user/libc.a \
		$(BUILD_DIR)/user/lib/string.o \
		$(BUILD_DIR)/user/lib/stdlib.o \
		$(BUILD_DIR)/user/lib/stdio.o \
		$(BUILD_DIR)/user/lib/ctype.o \
		$(BUILD_DIR)/user/lib/math.o \
		$(BUILD_DIR)/user/lib/win32.o \
		$(BUILD_DIR)/user/lib/crt_init.o
	@echo "[LIBC] $(BUILD_DIR)/user/libc.a created"
	@# Build user-mode ELF programs (linked against crt0 + libc)
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/hello.c -o $(BUILD_DIR)/user/hello.o
	$(LD) -nostdlib -static -T user/user.ld -o $(BUILD_DIR)/user/hello.exe \
		$(BUILD_DIR)/user/lib/crt0.o $(BUILD_DIR)/user/hello.o $(BUILD_DIR)/user/libc.a
	$(CC) $(USER_CFLAGS) -Iuser/include -Iinclude -c user/cmd.c -o $(BUILD_DIR)/user/cmd.o
	$(LD) -nostdlib -static -T user/user.ld -o $(BUILD_DIR)/user/cmd.exe \
		$(BUILD_DIR)/user/lib/crt0.o $(BUILD_DIR)/user/cmd.o $(BUILD_DIR)/user/libc.a
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/test/test_harness_smoke.c -o $(BUILD_DIR)/user/test/test_harness_smoke.o
	$(LD) -nostdlib -static -T user/user.ld -o $(BUILD_DIR)/user/test/test_harness_smoke.exe \
		$(BUILD_DIR)/user/lib/crt0.o $(BUILD_DIR)/user/test/test_harness_smoke.o $(BUILD_DIR)/user/libc.a
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/test/test_syscall.c -o $(BUILD_DIR)/user/test/test_syscall.o
	$(LD) -nostdlib -static -T user/user.ld -o $(BUILD_DIR)/user/test/test_syscall.exe \
		$(BUILD_DIR)/user/lib/crt0.o $(BUILD_DIR)/user/test/test_syscall.o $(BUILD_DIR)/user/libc.a
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/test/test_faultinject.c -o $(BUILD_DIR)/user/test/test_faultinject.o
	$(LD) -nostdlib -static -T user/user.ld -o $(BUILD_DIR)/user/test/test_faultinject.exe \
		$(BUILD_DIR)/user/lib/crt0.o $(BUILD_DIR)/user/test/test_faultinject.o $(BUILD_DIR)/user/libc.a
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/test/test_smoke_boot.c -o $(BUILD_DIR)/user/test/test_smoke_boot.o
	$(LD) -nostdlib -static -T user/user.ld -o $(BUILD_DIR)/user/test/test_smoke_boot.exe \
		$(BUILD_DIR)/user/lib/crt0.o $(BUILD_DIR)/user/test/test_smoke_boot.o $(BUILD_DIR)/user/libc.a
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/test/test_stress_libc.c -o $(BUILD_DIR)/user/test/test_stress_libc.o
	$(LD) -nostdlib -static -T user/user.ld -o $(BUILD_DIR)/user/test/test_stress_libc.exe \
		$(BUILD_DIR)/user/lib/crt0.o $(BUILD_DIR)/user/test/test_stress_libc.o $(BUILD_DIR)/user/libc.a
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/test/test_perf_syscall.c -o $(BUILD_DIR)/user/test/test_perf_syscall.o
	$(LD) -nostdlib -static -T user/user.ld -o $(BUILD_DIR)/user/test/test_perf_syscall.exe \
		$(BUILD_DIR)/user/lib/crt0.o $(BUILD_DIR)/user/test/test_perf_syscall.o $(BUILD_DIR)/user/libc.a
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/test/test_libc.c -o $(BUILD_DIR)/user/test/test_libc.o
	$(LD) -nostdlib -static -T user/user.ld -o $(BUILD_DIR)/user/test/test_libc.exe \
		$(BUILD_DIR)/user/lib/crt0.o $(BUILD_DIR)/user/test/test_libc.o $(BUILD_DIR)/user/libc.a
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/test/test_ipc.c -o $(BUILD_DIR)/user/test/test_ipc.o
	$(LD) -nostdlib -static -T user/user.ld -o $(BUILD_DIR)/user/test/test_ipc.exe \
		$(BUILD_DIR)/user/lib/crt0.o $(BUILD_DIR)/user/test/test_ipc.o $(BUILD_DIR)/user/libc.a
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/test/test_process.c -o $(BUILD_DIR)/user/test/test_process.o
	$(LD) -nostdlib -static -T user/user.ld -o $(BUILD_DIR)/user/test/test_process.exe \
		$(BUILD_DIR)/user/lib/crt0.o $(BUILD_DIR)/user/test/test_process.o $(BUILD_DIR)/user/libc.a
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/test/test_fileio.c -o $(BUILD_DIR)/user/test/test_fileio.o
	$(LD) -nostdlib -static -T user/user.ld -o $(BUILD_DIR)/user/test/test_fileio.exe \
		$(BUILD_DIR)/user/lib/crt0.o $(BUILD_DIR)/user/test/test_fileio.o $(BUILD_DIR)/user/libc.a
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/test/test_win32.c -o $(BUILD_DIR)/user/test/test_win32.o
	$(LD) -nostdlib -static -T user/user.ld -o $(BUILD_DIR)/user/test/test_win32.exe \
		$(BUILD_DIR)/user/lib/crt0.o $(BUILD_DIR)/user/test/test_win32.o $(BUILD_DIR)/user/libc.a
	@# Binary-format loader coverage binaries (one per registered format).
	@# ELF: the existing crt0+libc+main pattern -- proves the ELF loader
	@# path runs end-to-end independently of the smoke binary.
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/test/test_loader_elf.c -o $(BUILD_DIR)/user/test/test_loader_elf.o
	$(LD) -nostdlib -static -T user/user.ld -o $(BUILD_DIR)/user/test/test_loader_elf.exe \
		$(BUILD_DIR)/user/lib/crt0.o $(BUILD_DIR)/user/test/test_loader_elf.o $(BUILD_DIR)/user/libc.a
	@# PE32+: clang --target=x86_64-pc-windows-msvc + lld-link (no ELF
	@# toolchain). Entry point is _start; no CRT, no Windows runtime.
	@# --subsystem:console + /nodefaultlib keep the binary self-contained.
	clang-19 --target=x86_64-pc-windows-msvc -ffreestanding -nostdlib \
		-fno-stack-protector -mno-red-zone -O2 \
		-fuse-ld=lld-link -Wl,/entry:_start -Wl,/subsystem:console \
		-Wl,/nodefaultlib -o $(BUILD_DIR)/user/test/test_loader_pe.exe \
		user/test/test_loader_pe.c
	@# EIF: NASM -f bin emits raw x86-64 code, then scripts/build-eif.py
	@# wraps it in a 64-byte EIF header + 32-byte segment descriptor.
	@# No CRT, no linker -- the EIF format is its own container.
	$(AS) -f bin user/test/test_loader_eif.asm -o $(BUILD_DIR)/user/test/test_loader_eif.bin
	python3 scripts/build-eif.py \
		$(BUILD_DIR)/user/test/test_loader_eif.bin \
		$(BUILD_DIR)/user/test/test_loader_eif.exe
	@# Fast-path transport hardening probe (-17). ELF crt0+libc, five
	@# isolated probes; exit code is OR of FAIL bits so a drifted probe
	@# names itself in the launcher's exit-code verdict.
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/test/test_fastpath.c -o $(BUILD_DIR)/user/test/test_fastpath.o
	$(LD) -nostdlib -static -T user/user.ld -o $(BUILD_DIR)/user/test/test_fastpath.exe \
		$(BUILD_DIR)/user/lib/crt0.o $(BUILD_DIR)/user/test/test_fastpath.o $(BUILD_DIR)/user/libc.a
	@# -19 3-way transport fuzz (INT 0x80 + SYSCALL + INT 0x2E).
	$(CC) $(USER_CFLAGS) -Iuser/include -c user/test/test_fastpath_fuzz.c -o $(BUILD_DIR)/user/test/test_fastpath_fuzz.o
	$(LD) -nostdlib -static -T user/user.ld -o $(BUILD_DIR)/user/test/test_fastpath_fuzz.exe \
		$(BUILD_DIR)/user/lib/crt0.o $(BUILD_DIR)/user/test/test_fastpath_fuzz.o $(BUILD_DIR)/user/libc.a
	@cp -f $(BUILD_DIR)/user/hello.exe $(SYSROOT)/hello.exe
	@cp -f $(BUILD_DIR)/user/cmd.exe $(SYSROOT)/cmd.exe
	@cp -f $(BUILD_DIR)/user/test/test_harness_smoke.exe $(SYSROOT)/test_harness_smoke.exe
	@cp -f $(BUILD_DIR)/user/test/test_syscall.exe $(SYSROOT)/test_syscall.exe
	@cp -f $(BUILD_DIR)/user/test/test_faultinject.exe $(SYSROOT)/test_faultinject.exe
	@cp -f $(BUILD_DIR)/user/test/test_smoke_boot.exe $(SYSROOT)/test_smoke_boot.exe
	@cp -f $(BUILD_DIR)/user/test/test_stress_libc.exe $(SYSROOT)/test_stress_libc.exe
	@cp -f $(BUILD_DIR)/user/test/test_perf_syscall.exe $(SYSROOT)/test_perf_syscall.exe
	@cp -f $(BUILD_DIR)/user/test/test_libc.exe $(SYSROOT)/test_libc.exe
	@cp -f $(BUILD_DIR)/user/test/test_ipc.exe $(SYSROOT)/test_ipc.exe
	@cp -f $(BUILD_DIR)/user/test/test_process.exe $(SYSROOT)/test_process.exe
	@cp -f $(BUILD_DIR)/user/test/test_fileio.exe $(SYSROOT)/test_fileio.exe
	@cp -f $(BUILD_DIR)/user/test/test_win32.exe $(SYSROOT)/test_win32.exe
	@cp -f $(BUILD_DIR)/user/test/test_loader_elf.exe $(SYSROOT)/test_loader_elf.exe
	@cp -f $(BUILD_DIR)/user/test/test_loader_pe.exe  $(SYSROOT)/test_loader_pe.exe
	@cp -f $(BUILD_DIR)/user/test/test_loader_eif.exe $(SYSROOT)/test_loader_eif.exe
	@cp -f $(BUILD_DIR)/user/test/test_fastpath.exe $(SYSROOT)/test_fastpath.exe
	@cp -f $(BUILD_DIR)/user/test/test_fastpath_fuzz.exe $(SYSROOT)/test_fastpath_fuzz.exe
	@mkdir -p $(SYSROOT)/tests
	@cp -f tests/usermode.manifest $(SYSROOT)/tests/usermode.manifest
	@cp -f tests/usermode-cleanup.manifest $(SYSROOT)/tests/usermode-cleanup.manifest
	@cp -f tests/perf-baseline.json $(SYSROOT)/tests/perf-baseline.json
	@echo "[USER] hello/cmd + test_{harness_smoke,syscall,faultinject,smoke_boot,stress_libc,perf_syscall,libc,ipc,process,fileio,win32,loader_{elf,pe,eif}}.exe + manifests -> sysroot"

## iso: Package kernel + sysroot into a bootable UEFI ISO via GRUB (optional)
iso: $(ISO_FILE)

$(ISO_FILE): $(KERNEL_BIN) $(BOOT_DIR)/grub.cfg userland
	@mkdir -p $(ISO_DIR)/boot/grub
	cp $(KERNEL_BIN) $(ISO_DIR)/boot/kernel.exe
	cp $(BOOT_DIR)/grub.cfg $(ISO_DIR)/boot/grub/grub.cfg
	grub-mkrescue -o $(ISO_FILE) $(ISO_DIR) 2>/dev/null
	@echo "[ISO] $(ISO_FILE) created"

## system-disk: Create bootable GPT system disk with EFI + IXFS partitions
SYSTEM_DISK := $(BUILD_DIR)/system-disk.img
SYSTEM_DISK_SIZE := 512M
EFI_SIZE := 64M
# Shim binaries — built by bash scripts/secure-boot/build-shim.sh
SHIM_DIR := shim
# Partition offsets (must match make-system-disk defaults)
# EFI:      LBA 2048     = byte 1048576,   size 64M
# BlackBox: LBA 133120   = byte 68157440,  size 128M
# IXFS:     LBA 395264   = byte 202375168, fills remaining space
EFI_OFFSET  := 1048576
BB_OFFSET   := 68157440
BB_SIZE     := 128M
IXFS_OFFSET := 202375168
IXFS_PART_SIZE := $(shell echo $$(( (512*1024*1024 - 202375168 - 34*512) )) )

system-disk: $(SYSTEM_DISK)

$(SYSTEM_DISK): $(KERNEL_BIN) $(UEFI_EFI) sign-efi \
                tools/make-system-disk.c tools/mkfs-ixfs.c \
                $(SYSROOT)/hello.exe
	@echo "[DISK] Building system disk..."
	@mkdir -p $(BUILD_DIR)/tools
	$(HOST_CC) -O2 -o $(BUILD_DIR)/tools/make-system-disk tools/make-system-disk.c
	$(HOST_CC) -O2 -o $(BUILD_DIR)/tools/mkfs-ixfs tools/mkfs-ixfs.c
	@# Step 1: Create GPT image with partition table (EFI + BlackBox + IXFS)
	$(BUILD_DIR)/tools/make-system-disk -o $@ -s $(SYSTEM_DISK_SIZE) --efi-size $(EFI_SIZE)
	@# Step 2: Format EFI partition as FAT32 and copy boot files
	mkfs.fat -F 32 --offset $$(( $(EFI_OFFSET) / 512 )) $@
	@mkdir -p $(BUILD_DIR)/efi_staging/EFI/BOOT
	@mkdir -p $(BUILD_DIR)/efi_staging/boot
	@# --- EFI chain-load layout ---
	@# Shim chain-load (Secure Boot path): shim -> grubx64.efi -> kernel
	@# Fallback (dev/no-shim builds):      BOOTX64.EFI directly -> kernel
	@SHIM="$(SHIM_DIR)/shimx64.efi"; MM="$(SHIM_DIR)/mmx64.efi"; \
	if [ -f "$$SHIM" ] && [ -f "$$MM" ]; then \
		echo "[DISK] Shim found -- using Secure Boot chain-load layout"; \
		if [ -f "$(SHIM_DIR)/SHA256SUMS" ]; then \
			(cd $(SHIM_DIR) && sha256sum -c SHA256SUMS) \
				|| { echo "[ERROR] Shim hash verification FAILED"; exit 1; }; \
		fi; \
		cp $$SHIM $(BUILD_DIR)/efi_staging/EFI/BOOT/BOOTX64.EFI; \
		cp $(UEFI_EFI) $(BUILD_DIR)/efi_staging/EFI/BOOT/grubx64.efi; \
		cp $$MM $(BUILD_DIR)/efi_staging/EFI/BOOT/mmx64.efi; \
		cp $$MM $(BUILD_DIR)/efi_staging/mmx64.efi; \
		if [ -f "$(MOK_CRT)" ]; then \
			openssl x509 -in $(MOK_CRT) -outform DER -out $(BUILD_DIR)/efi_staging/MOK.cer; \
			echo "[DISK] MOK.cer (DER) copied to ESP root (for MokManager enrollment)"; \
		fi; \
	elif [ -f "$$SHIM" ] || [ -f "$$MM" ]; then \
		echo "[ERROR] Partial shim directory -- need both shimx64.efi and mmx64.efi"; \
		exit 1; \
	else \
		echo "[DISK] No shim -- using direct boot (run scripts/secure-boot/build-shim.sh for Secure Boot)"; \
		cp $(UEFI_EFI) $(BUILD_DIR)/efi_staging/EFI/BOOT/BOOTX64.EFI; \
	fi
	@cp $(KERNEL_BIN) $(BUILD_DIR)/efi_staging/boot/kernel.exe
	@mkdir -p $(BUILD_DIR)/efi_staging/EFI/ImpossibleOS
	@cp resources/boot/boot.conf $(BUILD_DIR)/efi_staging/EFI/ImpossibleOS/boot.conf
	mcopy -i $@@@$(EFI_OFFSET) -s $(BUILD_DIR)/efi_staging/* ::
	@rm -rf $(BUILD_DIR)/efi_staging
	@# Step 2b: Format BlackBox partition as FAT32 (128M = 131072 x 1024-byte blocks)
	mkfs.fat -F 32 -n "BLACKBOX" --offset $$(( $(BB_OFFSET) / 512 )) $@ 131072
	mmd -i $@@@$(BB_OFFSET) ::Logs ::Boot ::Crash ::Perf ::Diag ::Tools
	mmd -i $@@@$(BB_OFFSET) ::Crash/WER ::Logs/Serial
	@# Step 3: Format IXFS partition and populate with system files
	@mkdir -p $(BUILD_DIR)/sysroot/Impossible/System/Logs/Serial
	@cp $(BUILD_DIR)/kernel.sym $(BUILD_DIR)/sysroot/Impossible/System/kernel.sym
	$(BUILD_DIR)/tools/mkfs-ixfs \
		-o $@ \
		-s $(IXFS_PART_SIZE) \
		-l "Impossible OS" \
		--offset $(IXFS_OFFSET) \
		--populate $(BUILD_DIR)/sysroot
	@echo "[DISK] $@ created ($(SYSTEM_DISK_SIZE) GPT: EFI + BlackBox + IXFS)"

## run: Launch QEMU booting from system disk (UEFI via OVMF)
run: all
	@cp -n $(OVMF_VARS) $(OVMF_VARS_CP) 2>/dev/null || true
	@cp -n $(OVMF_CODE) $(BUILD_DIR)/OVMF_CODE_4M.fd 2>/dev/null || true
	$(QEMU) \
		-cpu Haswell \
		-smp 2 \
		-drive if=pflash,format=raw,readonly=on,file=$(OVMF_CODE) \
		-drive if=pflash,format=raw,file=$(OVMF_VARS_CP) \
		-drive id=disk0,file=$(SYSTEM_DISK),format=raw,if=none \
		-device ich9-ahci,id=ahci0 \
		-device ide-hd,drive=disk0,bus=ahci0.0 \
		-m 2G \
		-serial stdio \
		-vga none \
		-device VGA,xres=1280,yres=720 \
		-device rtl8139,netdev=net0 \
		-netdev user,id=net0 \
		-device virtio-tablet-pci \
		-rtc base=localtime \
		-no-reboot

## run-debug: Build + boot with debug=1 (unit tests + boot tests run)
run-debug: all
	@bash scripts/patch-boot-conf.sh debug 1
	@$(MAKE) --no-print-directory run
	@bash scripts/patch-boot-conf.sh reset

## run-test: Build + boot with test=1 (unit tests only, then shutdown)
run-test: all
	@bash scripts/patch-boot-conf.sh test 1
	@$(MAKE) --no-print-directory run
	@bash scripts/patch-boot-conf.sh reset

## test: Build, boot QEMU headless, run unit tests, report pass/fail, exit code
##   Usage: make test                  # all suites
##          make test SUITE=mm         # only Memory Management suites
##          make test QUIET=1          # summary only
##          make test TIMEOUT=120      # longer timeout
test: all
	@bash scripts/test.sh $(if $(SUITE),SUITE=$(SUITE)) $(if $(QUIET),QUIET=$(QUIET))

## check-abi: Verify user/include/abi_numbers.h is in sync with kernel
## source (include/kernel/sched/syscall.h + nt/service_numbers.h + nt/ntstatus.h).
## Fails the build when a kernel-side SYS_*/SSDT_*/STATUS_* renumber forgot
## to regenerate the user header -- silent drift was TODO-04 -17's original
## root cause. Safe to run standalone or chain in front of `make test`.
check-abi:
	@python3 scripts/gen-user-abi.py --check

## Per-category test targets
test-mm: all
	@bash scripts/test.sh SUITE=mm
test-fs: all
	@bash scripts/test.sh SUITE=fs
test-ob: all
	@bash scripts/test.sh SUITE=ob
test-security: all
	@bash scripts/test.sh SUITE=security
test-ipc: all
	@bash scripts/test.sh SUITE=ipc
test-sched: all
	@bash scripts/test.sh SUITE=sched
test-boot: all
	@bash scripts/test.sh SUITE=boot
test-abi: all
	@bash scripts/test.sh SUITE=abi
test-storage: all
	@bash scripts/test.sh SUITE=storage
test-exec: all
	@bash scripts/test.sh SUITE=exec

test-x86: all
	@bash scripts/test.sh SUITE=x86

test-desktop: all
	@bash scripts/test.sh SUITE=desktop

## test-visual: Run the visual regression suite (compare live captures vs tests/references/)
test-visual: all
	@bash scripts/test-visual-regression.sh

## update-ui-refs: Re-seed tests/references/ from a live boot (review + commit manually)
update-ui-refs: all
	@bash scripts/test-visual-regression.sh --update-refs

## run-1080p: Test at 1920×1080 — HiDPI scale stays 1× (≤1080p) but different from 720p
## test-usb-img: Create a 64 MiB FAT32 test USB disk image
USB_TEST_IMG := $(BUILD_DIR)/test-usb.img
test-usb-img: $(USB_TEST_IMG)
$(USB_TEST_IMG):
	@echo "[USB] Creating 64 MiB FAT32 test USB disk..."
	@mkdir -p $(BUILD_DIR)
	dd if=/dev/zero of=$@ bs=1M count=64 status=none
	mkfs.fat -F 32 -n "USB_TEST" $@
	@echo "Hello from USB!" > /tmp/usb_test.txt
	mcopy -i $@ /tmp/usb_test.txt ::
	@rm -f /tmp/usb_test.txt
	@echo "[USB] $@ ready (64 MiB FAT32)"

## run-usb: Launch QEMU with xHCI controller + 64 MiB USB mass storage device
## Use this to develop and test the xHCI + USB MSC driver (TODO-040.20)
run-usb: all $(USB_TEST_IMG)
	@cp -n $(OVMF_VARS) $(OVMF_VARS_CP) 2>/dev/null || true
	@echo "[TEST] Launching QEMU with xHCI + USB storage device"
	$(QEMU) \
		-cpu Haswell \
		-smp 2 \
		-drive if=pflash,format=raw,readonly=on,file=$(OVMF_CODE) \
		-drive if=pflash,format=raw,file=$(OVMF_VARS_CP) \
		-drive id=disk0,file=$(SYSTEM_DISK),format=raw,if=none \
		-device ich9-ahci,id=ahci0 \
		-device ide-hd,drive=disk0,bus=ahci0.0 \
		-device qemu-xhci,id=xhci0 \
		-drive id=usbdisk0,file=$(USB_TEST_IMG),format=raw,if=none \
		-device usb-storage,bus=xhci0.0,drive=usbdisk0 \
		-m 2G \
		-serial stdio \
		-vga none \
		-device VGA,xres=1280,yres=720 \
		-device rtl8139,netdev=net0 \
		-netdev user,id=net0 \
		-device virtio-tablet-pci \
		-rtc base=localtime \
		-no-reboot

## run-usb-ci: Headless USB test — no display, serial to file, auto-timeout
##   Usage: make run-usb-ci [TIMEOUT=20]
##   Output: build/serial.log (filtered USB lines printed on exit)
QEMU_TIMEOUT ?= 30
run-usb-ci: all $(USB_TEST_IMG)
	@cp -n $(OVMF_VARS) $(OVMF_VARS_CP) 2>/dev/null || true
	@echo "[TEST] Launching headless QEMU with xHCI + USB storage ($(QEMU_TIMEOUT)s timeout)"
	@timeout $(QEMU_TIMEOUT) $(QEMU) \
		-cpu Haswell \
		-smp 2 \
		-drive if=pflash,format=raw,readonly=on,file=$(OVMF_CODE) \
		-drive if=pflash,format=raw,file=$(OVMF_VARS_CP) \
		-drive id=disk0,file=$(SYSTEM_DISK),format=raw,if=none \
		-device ich9-ahci,id=ahci0 \
		-device ide-hd,drive=disk0,bus=ahci0.0 \
		-device qemu-xhci,id=xhci0 \
		-drive id=usbdisk0,file=$(USB_TEST_IMG),format=raw,if=none \
		-device usb-storage,bus=xhci0.0,drive=usbdisk0 \
		-m 2G \
		-serial file:build/serial.log \
		-display none \
		-device rtl8139,netdev=net0 \
		-netdev user,id=net0 \
		-device virtio-tablet-pci \
		-rtc base=localtime \
		-no-reboot 2>/dev/null; true
	@echo ""
	@echo "───── Serial output (USB) ─────"
	@grep -E 'xhci|usb' build/serial.log 2>/dev/null || echo "(no USB output found)"
	@echo "────────────────────────────────"

## clean-usb: Remove test USB disk image
clean-usb:
	rm -f $(USB_TEST_IMG)

## ── NVMe test targets ────────────────────────────────────────────────────────

NVME_TEST_IMG := $(BUILD_DIR)/test-nvme.img
test-nvme-img: $(NVME_TEST_IMG)
$(NVME_TEST_IMG):
	@echo "[NVMe] Creating 128 MiB FAT32 test NVMe disk..."
	@mkdir -p $(BUILD_DIR)
	dd if=/dev/zero of=$@ bs=1M count=128 status=none
	mkfs.fat -F 32 -n "NVME_TEST" $@
	@echo "Hello from NVMe!" > /tmp/nvme_test.txt
	mcopy -i $@ /tmp/nvme_test.txt ::
	@rm -f /tmp/nvme_test.txt
	@echo "[NVMe] $@ ready (128 MiB FAT32)"

## run-nvme: Launch QEMU with NVMe controller + 128 MiB NVMe drive
## Use this to develop and test the NVMe storage driver (TODO-08)
run-nvme: all $(NVME_TEST_IMG)
	@cp -n $(OVMF_VARS) $(OVMF_VARS_CP) 2>/dev/null || true
	@echo "[TEST] Launching QEMU with NVMe storage device"
	$(QEMU) \
		-cpu Haswell \
		-smp 2 \
		-drive if=pflash,format=raw,readonly=on,file=$(OVMF_CODE) \
		-drive if=pflash,format=raw,file=$(OVMF_VARS_CP) \
		-drive id=disk0,file=$(SYSTEM_DISK),format=raw,if=none \
		-device ich9-ahci,id=ahci0 \
		-device ide-hd,drive=disk0,bus=ahci0.0 \
		-drive id=nvme0,file=$(NVME_TEST_IMG),format=raw,if=none \
		-device nvme,serial=ImpOS-NVMe-Test,drive=nvme0 \
		-m 2G \
		-serial stdio \
		-vga none \
		-device VGA,xres=1280,yres=720 \
		-device rtl8139,netdev=net0 \
		-netdev user,id=net0 \
		-device virtio-tablet-pci \
		-rtc base=localtime \
		-no-reboot

## run-nvme-ci: Headless NVMe test — no display, serial to file, auto-timeout
run-nvme-ci: all $(NVME_TEST_IMG)
	@cp -n $(OVMF_VARS) $(OVMF_VARS_CP) 2>/dev/null || true
	@echo "[TEST] Launching headless QEMU with NVMe storage ($(QEMU_TIMEOUT)s timeout)"
	@timeout $(QEMU_TIMEOUT) $(QEMU) \
		-cpu Haswell \
		-smp 2 \
		-drive if=pflash,format=raw,readonly=on,file=$(OVMF_CODE) \
		-drive if=pflash,format=raw,file=$(OVMF_VARS_CP) \
		-drive id=disk0,file=$(SYSTEM_DISK),format=raw,if=none \
		-device ich9-ahci,id=ahci0 \
		-device ide-hd,drive=disk0,bus=ahci0.0 \
		-drive id=nvme0,file=$(NVME_TEST_IMG),format=raw,if=none \
		-device nvme,serial=ImpOS-NVMe-Test,drive=nvme0 \
		-m 2G \
		-serial file:build/serial.log \
		-display none \
		-device rtl8139,netdev=net0 \
		-netdev user,id=net0 \
		-device virtio-tablet-pci \
		-rtc base=localtime \
		-no-reboot 2>/dev/null; true
	@echo ""
	@echo "───── Serial output (NVMe) ─────"
	@grep -iE 'nvme|01:08' build/serial.log 2>/dev/null || echo "(no NVMe output found)"
	@echo "─────────────────────────────────"

## clean-nvme: Remove test NVMe disk image
clean-nvme:
	rm -f $(NVME_TEST_IMG)

## run-1080p: Test at 1920×1080 — HiDPI scale stays 1× (≤1080p) but different from 720p
## Serial output: [SPLASH] 1920x1080  scale=1x  font=16px
run-1080p: all
	@cp -n $(OVMF_VARS) $(OVMF_VARS_CP) 2>/dev/null || true
	@echo "[TEST] Launching QEMU at 1920×1080 (scale=1×)"
	$(QEMU) \
		-cpu Haswell \
		-drive if=pflash,format=raw,readonly=on,file=$(OVMF_CODE) \
		-drive if=pflash,format=raw,file=$(OVMF_VARS_CP) \
		-drive id=disk0,file=$(SYSTEM_DISK),format=raw,if=none \
		-device ich9-ahci,id=ahci0 \
		-device ide-hd,drive=disk0,bus=ahci0.0 \
		-m 2G \
		-serial stdio \
		-vga none \
		-device VGA,vgamem_mb=16,xres=1920,yres=1080 \
		-device rtl8139,netdev=net0 \
		-netdev user,id=net0 \
		-device virtio-tablet-pci \
		-rtc base=localtime \
		-no-reboot

## run-1440p: Test at 2560×1440 — HiDPI scale=2× (>1080p)
## Serial output: [SPLASH] 2560x1440  scale=2x  font=32px
run-1440p: all
	@cp -n $(OVMF_VARS) $(OVMF_VARS_CP) 2>/dev/null || true
	@echo "[TEST] Launching QEMU at 2560×1440 (scale=2×)"
	$(QEMU) \
		-cpu Haswell \
		-drive if=pflash,format=raw,readonly=on,file=$(OVMF_CODE) \
		-drive if=pflash,format=raw,file=$(OVMF_VARS_CP) \
		-drive id=disk0,file=$(SYSTEM_DISK),format=raw,if=none \
		-device ich9-ahci,id=ahci0 \
		-device ide-hd,drive=disk0,bus=ahci0.0 \
		-m 2G \
		-serial stdio \
		-vga none \
		-device VGA,vgamem_mb=32,xres=2560,yres=1440 \
		-device rtl8139,netdev=net0 \
		-netdev user,id=net0 \
		-device virtio-tablet-pci \
		-rtc base=localtime \
		-no-reboot

## run-4k: Test at 3840×2160 using bochs-display (VGA caps out at 4K)
## bochs-display avoids the VGA PCI BAR limitation that causes FrameBufferBase=0
## Requires QEMU 4.0+; serial: [??] SPLASH  3840x2160  scale=2x
run-4k: all
	@cp -n $(OVMF_VARS) $(OVMF_VARS_CP) 2>/dev/null || true
	@echo "[TEST] Launching QEMU at 3840×2160 via bochs-display (scale=2×)"
	$(QEMU) \
		-cpu Haswell \
		-drive if=pflash,format=raw,readonly=on,file=$(OVMF_CODE) \
		-drive if=pflash,format=raw,file=$(OVMF_VARS_CP) \
		-drive id=disk0,file=$(SYSTEM_DISK),format=raw,if=none \
		-device ich9-ahci,id=ahci0 \
		-device ide-hd,drive=disk0,bus=ahci0.0 \
		-m 2G \
		-serial stdio \
		-vga none \
		-device bochs-display,xres=3840,yres=2160 \
		-device rtl8139,netdev=net0 \
		-netdev user,id=net0 \
		-device virtio-tablet-pci \
		-rtc base=localtime \
		-no-reboot

## vbox: Build, convert to VDI, and launch in VirtualBox
vbox: all
	@echo "Converting raw disk to VDI..."
	@rm -f $(BUILD_DIR)/system-disk.vdi
	@qemu-img convert -f raw -O vdi $(SYSTEM_DISK) $(BUILD_DIR)/system-disk.vdi
	@echo "VDI created: $(BUILD_DIR)/system-disk.vdi"
	@echo ""
	@echo "To launch in VirtualBox, run:  scripts/machines/run-vbox.bat"

## run-test: Launch QEMU with a secondary test disk on AHCI port 1
##   Usage: make run-test DISK=fat32       (loads build/test-disks/fat32.img)
##          make run-test DISK=ext4        (loads build/test-disks/ext4.img)
##          make run-test DISK=optical/iso9660  (loads optical ISO via -cdrom)
DISK ?= fat32
TEST_DISK_PATH := $(BUILD_DIR)/test-disks/$(DISK)

run-test: all test-disks
	@if echo "$(DISK)" | grep -q "optical/"; then \
		TEST_FILE="$(TEST_DISK_PATH).iso"; \
	else \
		TEST_FILE="$(TEST_DISK_PATH).img"; \
	fi; \
	if [ ! -f "$$TEST_FILE" ]; then \
		echo "[ERROR] Test disk not found: $$TEST_FILE"; \
		echo "  Available disks:"; \
		ls $(BUILD_DIR)/test-disks/*.img 2>/dev/null | sed 's|.*/||;s|\.img||' | sed 's/^/    /'; \
		ls $(BUILD_DIR)/test-disks/optical/*.iso 2>/dev/null | sed "s|$(BUILD_DIR)/test-disks/||;s|\.iso||" | sed 's/^/    /'; \
		exit 1; \
	fi; \
	cp $(OVMF_VARS) $(OVMF_VARS_CP); \
	if echo "$(DISK)" | grep -q "optical/"; then \
		echo "[TEST] Attaching $$TEST_FILE as ATAPI CD-ROM on AHCI port 1"; \
		$(QEMU) \
			-drive if=pflash,format=raw,readonly=on,file=$(OVMF_CODE) \
			-drive if=pflash,format=raw,file=$(OVMF_VARS_CP) \
			-drive id=disk0,file=$(SYSTEM_DISK),format=raw,if=none \
			-drive id=cdrom0,file=$$TEST_FILE,format=raw,if=none,media=cdrom \
			-device ich9-ahci,id=ahci0 \
			-device ide-hd,drive=disk0,bus=ahci0.0 \
			-device ide-cd,drive=cdrom0,bus=ahci0.1 \
			-m 2G -serial stdio -vga none \
			-device VGA,xres=1280,yres=720 \
			-device rtl8139,netdev=net0 -netdev user,id=net0 \
			-device virtio-tablet-pci -rtc base=localtime -no-reboot; \
	else \
		echo "[TEST] Attaching $$TEST_FILE on AHCI port 1"; \
		$(QEMU) \
			-drive if=pflash,format=raw,readonly=on,file=$(OVMF_CODE) \
			-drive if=pflash,format=raw,file=$(OVMF_VARS_CP) \
			-drive id=disk0,file=$(SYSTEM_DISK),format=raw,if=none \
			-drive id=testdisk,file=$$TEST_FILE,format=raw,if=none \
			-device ich9-ahci,id=ahci0 \
			-device ide-hd,drive=disk0,bus=ahci0.0 \
			-device ide-hd,drive=testdisk,bus=ahci0.1 \
			-m 2G -serial stdio -vga none \
			-device VGA,xres=1280,yres=720 \
			-device rtl8139,netdev=net0 -netdev user,id=net0 \
			-device virtio-tablet-pci -rtc base=localtime -no-reboot; \
	fi

## run-debug: Launch QEMU paused, waiting for GDB on port 1234
run-debug: all
	@cp -n $(OVMF_VARS) $(OVMF_VARS_CP) 2>/dev/null || true
	$(QEMU) \
		-drive if=pflash,format=raw,readonly=on,file=$(OVMF_CODE) \
		-drive if=pflash,format=raw,file=$(OVMF_VARS_CP) \
		-drive id=disk0,file=$(SYSTEM_DISK),format=raw,if=none \
		-device ich9-ahci,id=ahci0 \
		-device ide-hd,drive=disk0,bus=ahci0.0 \
		-m 2G \
		-serial stdio \
		-vga none \
		-device VGA,xres=1280,yres=720 \
		-device rtl8139,netdev=net0 \
		-netdev user,id=net0 \
		-device virtio-tablet-pci \
		-rtc base=localtime \
		-no-reboot \
		-s -S -d int,cpu_reset

## run-log: Launch QEMU with serial output captured to serial.log
run-log: all
	@cp -n $(OVMF_VARS) $(OVMF_VARS_CP) 2>/dev/null || true
	$(QEMU) \
		-drive if=pflash,format=raw,readonly=on,file=$(OVMF_CODE) \
		-drive if=pflash,format=raw,file=$(OVMF_VARS_CP) \
		-drive id=disk0,file=$(SYSTEM_DISK),format=raw,if=none \
		-device ich9-ahci,id=ahci0 \
		-device ide-hd,drive=disk0,bus=ahci0.0 \
		-m 2G \
		-serial file:serial.log \
		-vga none \
		-device VGA,xres=1280,yres=720 \
		-device rtl8139,netdev=net0 \
		-netdev user,id=net0 \
		-device virtio-tablet-pci \
		-rtc base=localtime \
		-no-reboot
	@echo "[LOG] Serial output saved to serial.log"

## test-disks: Generate test disk images for filesystem driver testing
test-disks: system-disk
	@bash tools/make-test-disks.sh $(BUILD_DIR)/test-disks $(BUILD_DIR)

## clean: Remove all build artifacts
clean:
	rm -rf $(BUILD_DIR)
	rm -f $(BUILD_INFO_H)
	$(MAKE) -C src/boot/uefi clean
	@echo "[CLEAN] Build directory removed"

# ============================================================================
# Pattern Rules
# ============================================================================

# AP trampoline — assembled as flat binary, then embedded as linkable object
# We cd into the bin directory so objcopy generates clean symbol names:
#   _binary_ap_trampoline_bin_start / _binary_ap_trampoline_bin_end
$(AP_TRAMPOLINE_OBJ): $(SRC_DIR)/kernel/smp/ap_trampoline.asm
	@mkdir -p $(dir $@)
	$(AS) -f bin $< -o $(AP_TRAMPOLINE_BIN)
	cd $(dir $(AP_TRAMPOLINE_BIN)) && \
		$(OBJCOPY) -I binary -O elf64-x86-64 -B i386:x86-64 \
		--rename-section .data=.rodata,alloc,load,readonly,data,contents \
		$(notdir $(AP_TRAMPOLINE_BIN)) $(CURDIR)/$@
	@echo "[AS/BIN] $< (AP trampoline)"

# SSE2 SIMD module -- compiled with -msse2 (overrides -mno-sse from CFLAGS)
SIMD_CFLAGS := $(filter-out -mno-mmx -mno-sse -mno-sse2, $(CFLAGS)) -msse2
# AVX2 module -- compiled with -mavx2 (memops.c only)
AVX2_CFLAGS := $(SIMD_CFLAGS) -mavx2
# AVX-512 module -- compiled with -mavx512f (memops_avx512.c, gfx_simd_avx512.c)
AVX512_CFLAGS := $(SIMD_CFLAGS) -mavx512f
$(BUILD_DIR)/kernel/gfx/gfx_simd.o: $(SRC_DIR)/kernel/gfx/gfx_simd.c | $(GENERATED_HDRS)
	@mkdir -p $(dir $@)
	$(CC) $(SIMD_CFLAGS) -I$(INCLUDE) -I$(KERNEL_DIR) -c $< -o $@
	@echo "[CC/SSE2] $<"

# AVX-512 SIMD -- fb_blit_avx512/fb_fill_avx512 + throttle burst (AVX-512 ONLY)
$(BUILD_DIR)/kernel/gfx/gfx_simd_avx512.o: $(SRC_DIR)/kernel/gfx/gfx_simd_avx512.c | $(GENERATED_HDRS)
	@mkdir -p $(dir $@)
	$(CC) $(AVX512_CFLAGS) -I$(INCLUDE) -I$(KERNEL_DIR) -c $< -o $@
	@echo "[CC/AVX512] $<"

# AVX2 memops -- memcpy_avx/memset_avx with vzeroupper (AVX2 ONLY)
$(BUILD_DIR)/kernel/mm/memops.o: $(SRC_DIR)/kernel/mm/memops.c | $(GENERATED_HDRS)
	@mkdir -p $(dir $@)
	$(CC) $(AVX2_CFLAGS) -I$(INCLUDE) -I$(KERNEL_DIR) -c $< -o $@
	@echo "[CC/AVX2] $<"

# AVX-512 memops -- memcpy_avx512/memset_avx512 (AVX-512 ONLY)
$(BUILD_DIR)/kernel/mm/memops_avx512.o: $(SRC_DIR)/kernel/mm/memops_avx512.c | $(GENERATED_HDRS)
	@mkdir -p $(dir $@)
	$(CC) $(AVX512_CFLAGS) -I$(INCLUDE) -I$(KERNEL_DIR) -c $< -o $@
	@echo "[CC/AVX512] $<"

# SSE2 memops + dispatch -- must NOT use -mavx2 (VEX instructions crash TCG)
$(BUILD_DIR)/kernel/mm/memops_sse.o: $(SRC_DIR)/kernel/mm/memops_sse.c | $(GENERATED_HDRS)
	@mkdir -p $(dir $@)
	$(CC) $(SIMD_CFLAGS) -I$(INCLUDE) -I$(KERNEL_DIR) -c $< -o $@
	@echo "[CC/SSE2] $< (dispatch)"

# stb_truetype implementation — needs SSE2 for floating-point math
$(BUILD_DIR)/kernel/gfx/stb_truetype_impl.o: $(SRC_DIR)/kernel/gfx/stb_truetype_impl.c | $(GENERATED_HDRS)
	@mkdir -p $(dir $@)
	$(CC) $(SIMD_CFLAGS) -Wno-unused-function -Wno-sign-compare -I$(INCLUDE) -I$(KERNEL_DIR) -c $< -o $@
	@echo "[CC/SSE2] $< (stb_truetype)"

# Font manager + text rendering — needs SSE2 for stb_truetype API calls
$(BUILD_DIR)/kernel/gfx/gfx_text.o: $(SRC_DIR)/kernel/gfx/gfx_text.c | $(GENERATED_HDRS)
	@mkdir -p $(dir $@)
	$(CC) $(SIMD_CFLAGS) -I$(INCLUDE) -I$(KERNEL_DIR) -c $< -o $@
	@echo "[CC/SSE2] $< (fonts)"

# stb_image implementation — needs SSE2 for floating-point math
# -isystem include/freestanding provides shims for <stdlib.h>, <string.h>, etc.
$(BUILD_DIR)/kernel/image.o: $(SRC_DIR)/kernel/image.c | $(GENERATED_HDRS)
	@mkdir -p $(dir $@)
	$(CC) $(SIMD_CFLAGS) -Wno-unused-function -Wno-sign-compare -isystem include/freestanding -I$(INCLUDE) -I$(KERNEL_DIR) -c $< -o $@
	@echo "[CC/SSE2] $< (stb_image)"

# stb_image_write implementation — same flags as stb_image
$(BUILD_DIR)/kernel/image_save.o: $(SRC_DIR)/kernel/image_save.c | $(GENERATED_HDRS)
	@mkdir -p $(dir $@)
	$(CC) $(SIMD_CFLAGS) -Wno-unused-function -Wno-sign-compare -isystem include/freestanding -I$(INCLUDE) -I$(KERNEL_DIR) -c $< -o $@
	@echo "[CC/SSE2] $< (stb_image_write)"

# Icon store — uses stb_truetype for glyph rasterization
$(BUILD_DIR)/kernel/icon_store.o: $(SRC_DIR)/kernel/icon_store.c | $(GENERATED_HDRS)
	@mkdir -p $(dir $@)
	$(CC) $(SIMD_CFLAGS) -Wno-unused-function -Wno-sign-compare -isystem include/freestanding -I$(INCLUDE) -I$(KERNEL_DIR) -c $< -o $@
	@echo "[CC/SSE2] $< (icon_store)"

# cJSON + json wrapper: need SSE2 for float (JSON number values use double)
$(BUILD_DIR)/libs/cjson/cJSON.o: $(SRC_DIR)/libs/cjson/cJSON.c | $(GENERATED_HDRS)
	@mkdir -p $(dir $@)
	$(CC) $(SIMD_CFLAGS) -Wno-unused-function -Wno-sign-compare -Wno-float-conversion -Wno-implicit-float-conversion -I$(INCLUDE) -I$(KERNEL_DIR) -I$(SRC_DIR) -c $< -o $@
	@echo "[CC/SSE2] $< (cJSON)"

$(BUILD_DIR)/kernel/json.o: $(SRC_DIR)/kernel/json.c | $(GENERATED_HDRS)
	@mkdir -p $(dir $@)
	$(CC) $(SIMD_CFLAGS) -I$(INCLUDE) -I$(KERNEL_DIR) -I$(SRC_DIR) -c $< -o $@
	@echo "[CC/SSE2] $< (json wrapper)"

# Compile C source files (64-bit)
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c | $(GENERATED_HDRS)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -I$(INCLUDE) -I$(KERNEL_DIR) -I$(SRC_DIR) -c $< -o $@
	@echo "[CC] $<"

# Assemble NASM source files
# entry.asm is multi-format (starts 32-bit, transitions to 64-bit)
# multiboot2_header.asm is format-agnostic (data only)
# Both assembled as elf64 since the linker expects elf64 objects
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.asm
	@mkdir -p $(dir $@)
	$(AS) $(ASFLAGS) $< -o $@
	@echo "[AS] $<"

# ============================================================================
# Auto-generated dependency files (-MMD -MP)
# ============================================================================
DEP_FILES := $(shell find $(BUILD_DIR) -name '*.d' 2>/dev/null)
-include $(DEP_FILES)
