#!/usr/bin/env python3
"""Generate resources/icons/src/recycle_bin_full.svg: the empty bin's glass
holding crumpled paper. Original artwork, GPL-3.0-only.

The paper is modelled rather than drawn: each ball has a lumpy outline (16
points, short curve handles so folds keep a slight corner) and is split into
small flat facets by a Delaunay triangulation of the outline plus scattered
interior points; each facet is tilted at random but biased toward the light
(top left), and some shared edges show as creases. The balls rest on each
other from the bottom up to the brim, and the top one sits in the opening,
in front of the back rim and behind the front rim. Seeds are fixed, so the
output is reproducible.

    python3 scripts/site/gen_recycle_bin_full.py && bash scripts/convert-icons.sh
Needs scipy (Delaunay).
"""
import math, random, sys
from pathlib import Path
OUT = Path(__file__).resolve().parents[2] / "resources" / "icons" / "src" / "recycle_bin_full.svg"
P = "recycle_bin_full"
LIGHT = math.atan2(-1, -1)          # light from the top left
CLIPS = []


def outline(cx, cy, r, seed):
    """A lumpy crumpled outline: 11 points at irregular radii joined with SHORT
    Catmull-Rom handles, so corners are soft but still read as folds."""
    rnd = random.Random(seed)
    n = 16
    pts = []
    for i in range(n):
        a = 2 * math.pi * (i + rnd.uniform(-.3, .3)) / n
        rr = r * rnd.uniform(.9, 1.07)
        pts.append((cx + rr * math.cos(a), cy + rr * .92 * math.sin(a)))
    d = f"M{pts[0][0]:.2f} {pts[0][1]:.2f}"
    for i in range(n):
        p0, p1, p2, p3 = pts[i - 1], pts[i], pts[(i + 1) % n], pts[(i + 2) % n]
        k = 8.0                       # 6 = fully smooth; larger keeps a crease at each point
        c1 = (p1[0] + (p2[0] - p0[0]) / k, p1[1] + (p2[1] - p0[1]) / k)
        c2 = (p2[0] - (p3[0] - p1[0]) / k, p2[1] - (p3[1] - p1[1]) / k)
        d += f"C{c1[0]:.2f} {c1[1]:.2f} {c2[0]:.2f} {c2[1]:.2f} {p2[0]:.2f} {p2[1]:.2f}"
    return d + "Z", pts


def shade(t):
    lo, hi = (0xA9, 0xB7, 0xC9), (0xFF, 0xFF, 0xFF)
    return "#%02X%02X%02X" % tuple(round(l + (h - l) * t) for l, h in zip(lo, hi))


def ball(cx, cy, r, seed):
    """Crumpled paper: an irregular triangulation (outline points plus several
    scattered interior points), each flat facet tilted at random but biased
    toward the light, so the planes are uneven in size and direction; only
    some shared edges show as creases."""
    from scipy.spatial import Delaunay
    d, pts = outline(cx, cy, r, seed)
    rnd = random.Random(seed * 7 + 1)
    inner = []
    while len(inner) < 11:
        a, rr = rnd.uniform(0, 2 * math.pi), r * math.sqrt(rnd.uniform(0, .8))
        inner.append((cx + rr * math.cos(a), cy + rr * .92 * math.sin(a)))
    allp = pts + inner
    tri = Delaunay(allp)
    facets, edges = [], set()
    for simplex in tri.simplices:
        a, b, c = (allp[k] for k in simplex)
        mx, my = (a[0] + b[0] + c[0]) / 3, (a[1] + b[1] + c[1]) / 3
        # facing: where the facet sits on the ball, plus a random tilt of its plane
        facing = math.atan2(my - cy, mx - cx) + rnd.uniform(-1.3, 1.3)
        dist = min(1, math.hypot(mx - cx, my - cy) / r)
        t = .56 + .44 * math.cos(facing - LIGHT) * (.45 + .55 * dist) + rnd.uniform(-.16, .16)
        t = min(1, max(0, t))
        facets.append(f'<path d="M{a[0]:.2f} {a[1]:.2f}L{b[0]:.2f} {b[1]:.2f}L{c[0]:.2f} {c[1]:.2f}Z" fill="{shade(t)}" stroke="{shade(t)}" stroke-width=".15"/>')
        for u, v in ((simplex[0], simplex[1]), (simplex[1], simplex[2]), (simplex[2], simplex[0])):
            edges.add((min(u, v), max(u, v)))
    n = len(pts)
    creases = [f"M{allp[u][0]:.2f} {allp[u][1]:.2f}L{allp[v][0]:.2f} {allp[v][1]:.2f}"
               for u, v in sorted(edges) if not (u < n and v < n) and rnd.random() < .35]
    clip = f"{P}-b{seed}"
    CLIPS.append(f'<clipPath id="{clip}"><path d="{d}"/></clipPath>')
    return (f'<path d="{d}" fill="#E3E9F1"/>'
            f'<g clip-path="url(#{clip})">{"".join(facets)}'
            f'<path d="{"".join(creases)}" fill="none" stroke="#9DAEC3" stroke-opacity=".5" stroke-width=".35"/></g>'
            f'<path d="{d}" fill="none" stroke="#8FA2BA" stroke-opacity=".55" stroke-width=".45" stroke-linejoin="round"/>')


# Bottom-up pile: the larger balls settle low and the pile reaches the brim.
PILE = [(18.2, 37.4, 6.4, 11), (29.8, 37.8, 6.2, 12), (24.0, 28.6, 6.8, 13), (15.4, 23.2, 5.6, 14), (32.6, 22.8, 5.6, 15)]
MOUTH = (24.2, 15.6, 6.4, 16)      # tops the pile and sits in the opening
pile_svg = "".join(ball(*b) for b in PILE)
mouth_svg = ball(*MOUTH)
body = "M8.4 12.4 13.2 41c.2 1.3 4.9 2.3 10.8 2.3s10.6-1 10.8-2.3l4.8-28.6z"

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="48" height="48">
<!-- Generated by scripts/site/gen_recycle_bin_full.py; edit the generator, not this file.
     The empty bin's glass, holding crumpled paper that rests on itself from the bottom to the brim;
     the top ball sits in the opening, in front of the back rim and behind the front rim. -->
<defs><linearGradient id="{P}-inside" x1="0" y1="0" x2="0" y2="1" gradientUnits="objectBoundingBox"><stop offset="0" stop-color="#4E6680"/><stop offset="1" stop-color="#8CA6C2"/></linearGradient><linearGradient id="{P}-back" x1="0" y1="0" x2="0" y2="1" gradientUnits="objectBoundingBox"><stop offset="0" stop-color="#7C96B2" stop-opacity=".55"/><stop offset="1" stop-color="#A9C0D8" stop-opacity=".35"/></linearGradient><linearGradient id="{P}-glass" x1="0" y1="0" x2="1" y2="0" gradientUnits="objectBoundingBox"><stop offset="0" stop-color="#E4F0FB" stop-opacity=".55"/><stop offset="0.45" stop-color="#C3D8EE" stop-opacity=".22"/><stop offset="1" stop-color="#93B0D0" stop-opacity=".6"/></linearGradient><linearGradient id="{P}-rim" x1="0" y1="0" x2="0" y2="1" gradientUnits="objectBoundingBox"><stop offset="0" stop-color="#E8F0F8"/><stop offset="1" stop-color="#7D93AD"/></linearGradient><linearGradient id="{P}-spec" x1="0" y1="0" x2="1" y2="0" gradientUnits="objectBoundingBox"><stop offset="0" stop-color="#FFFFFF" stop-opacity="0"/><stop offset="0.45" stop-color="#FFFFFF" stop-opacity=".55"/><stop offset="1" stop-color="#FFFFFF" stop-opacity="0"/></linearGradient><clipPath id="{P}-interior"><path d="{body}"/><ellipse cx="24" cy="12.4" rx="15.6" ry="4"/></clipPath>{"".join(CLIPS)}</defs>
<path d="{body}" fill="url(#{P}-back)"/>
<ellipse cx="24" cy="12.4" rx="15.6" ry="4" fill="url(#{P}-inside)"/>
<path d="M8.4 12.4A15.6 4 0 0 1 39.6 12.4" fill="none" stroke="url(#{P}-rim)" stroke-width="1.8"/>
<path d="M11.6 10.4C15 9.4 19.3 8.9 24 8.9" fill="none" stroke="#FFFFFF" stroke-opacity=".85" stroke-linecap="round"/>
<g clip-path="url(#{P}-interior)">{pile_svg}</g>
{mouth_svg}
<path d="M8.4 12.4C8.4 14.6 15.4 16.4 24 16.4s15.6-1.8 15.6-4L34.8 41c-.2 1.3-4.9 2.3-10.8 2.3s-10.6-1-10.8-2.3z" fill="url(#{P}-glass)"/>
<path d="M11.2 17.2c2.1.8 3.7 1.1 5.4 1.3l2.2 23.8c-1.8-.3-3.5-.7-4.6-1.2z" fill="url(#{P}-spec)"/>
<path d="M8.9 13.6 13.4 40.7M39.1 13.6 34.6 40.7" fill="none" stroke="#56708E" stroke-opacity=".75" stroke-width=".9"/>
<path d="M13.3 41.1c.8 1.2 5.2 2.1 10.7 2.1s9.9-.9 10.7-2.1" fill="none" stroke="#56708E" stroke-opacity=".75" stroke-width=".9"/>
<path d="M8.4 12.4A15.6 4 0 0 0 39.6 12.4" fill="none" stroke="url(#{P}-rim)" stroke-width="1.8"/>
</svg>
'''
OUT.write_text(svg, encoding="utf-8")
print(f"wrote {OUT.relative_to(OUT.parents[3])}")
