#!/usr/bin/env python3
"""Keep release docs trees published beside `main` across every deploy.

Every Pages deploy uploads one whole-site artifact built from `main`, so a docs
tree for a release survives only if each deploy puts it back. The trees are
therefore FROZEN once, when the release is published, on the orphan data branch
`docs-releases` (never the dormant `gh-pages` branch):

    versions.json      {"schema": 1, "releases": [{"version", "commit", "files", "digest"}],
                        "retired": [{"version", "commit"}]}
    <version>/...      the tree `build.py --release <version>` rendered, byte for byte

A frozen tree cannot be changed or broken by a later build.py, and it is not a
GitHub Release asset, which release.yml deletes when a stable release replaces
its pre-releases. `versions.json` is the authoritative list: a directory it does
not name is never published, and a listed tree whose files no longer match its
digest fails the deploy instead of publishing altered bytes. `retired` records
releases an operator took off the site (to stay under the size budget, say):
publish never freezes them again while their tag still names that commit.

The whole published site must stay under SITE_BUDGET bytes (GitHub Pages
publishes at most 1 GB): freezing a release that would pass it is refused, and
so is a deploy that has grown past it.

Commands:
  publish   --store DIR --main-site DIR [--new-store]
                                         render and freeze every site-era `v*` tag the
                                         store lacks (a re-run resumes; a moved tag fails)
  assemble  --site DIR --releases remote|none|<store sha> [--github-output FILE]
  assemble  --site DIR --store DIR       copy every retained tree into DIR/docs/<version>/
                                         and write DIR/docs/versions.json for the picker
  push-store                             push the store branch and, if the remote lacks it,
                                         the docs-releases-root marker in one atomic push
  store-sha                              print the remote store's commit, or `none` when no
                                         store ever existed (a lost one is refused, exit 1)
  deletable                              JSON {tag: ref object} release.yml may delete: tags
                                         the store holds or retired at their frozen commit,
                                         and tags older than the site

Exit: 0 ok, 1 refused (collision, digest mismatch, moved tag, bad store), 2 usage.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import stat
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
BRANCH = "docs-releases"
MARKER_TAG = "docs-releases-root"   # pushed when the store is first created; never moved or deleted
STORE_REF = f"refs/remotes/origin/{BRANCH}"
MANIFEST = "versions.json"          # at the store root
PUBLISHED = "docs/versions.json"    # in the site, read by the docs template's picker
SCHEMA = 1
# One path segment, so no release can nest inside another; the `v` prefix is the
# tag filter release.yml and docs-release.yml trigger on.
VERSION_RE = re.compile(r"v[A-Za-z0-9._-]*")
SHA_RE = re.compile(r"[0-9a-f]{40}|[0-9a-f]{64}")
SITE_BUDGET = 900_000_000   # bytes: headroom under GitHub Pages' 1 GB published-site limit


STORE_README = """# docs-releases

Generated by `.github/workflows/docs-release.yml` on `main`; do not edit by hand.
Each directory is a release's documentation tree, rendered once from its tag by
`scripts/site/build.py --release` and published at `docs/<version>/` on the site.
`versions.json` lists them; a tree that no longer matches its digest there stops
the deploy. See `docs/infrastructure/documentation-site.md` on `main`.
"""


class StoreError(Exception):
    pass


GIT_TIMEOUT = 300      # local git: sub-second here, so a hang is a fault, not a slow repository
NET_TIMEOUT = 1200     # fetch, ls-remote and push of the store; docs-release.yml's job allows 60 minutes
RENDER_TIMEOUT = 1200  # one release render; a normal one takes seconds, so this only catches a hang


def git(*args: str, check: bool = True, timeout: float = GIT_TIMEOUT) -> subprocess.CompletedProcess:
    """git in the CALLER's process group, so a supervisor that kills that group
    (verify_live's run deadline) takes git and its transport helpers with it. On
    this call's own timeout git is killed and reaped and the call raises
    StoreError; a helper git started can outlive it until the group is killed,
    because nothing here contains a process that has been reparented."""
    try:
        return subprocess.run(["git", *args], cwd=REPO, check=check, capture_output=True, text=True,
                              timeout=timeout)
    except subprocess.TimeoutExpired:
        raise StoreError(f"git {' '.join(args[:2])} did not finish within {timeout:.0f} s") from None


def valid_version(v: str) -> bool:
    return bool(VERSION_RE.fullmatch(v)) and v not in ("v.", "v..") and ".." not in v


def tree_files(root: Path) -> list[str]:
    """Every regular file under root, relative, in path order. A symlink or any
    other non-regular entry is refused: the digest would not cover what a copy
    that follows it publishes (a link to an unlisted directory, say)."""
    out: list[str] = []
    for d, dirs, files in os.walk(root):
        for name in dirs + files:
            p = Path(d) / name
            mode = p.lstat().st_mode
            if stat.S_ISLNK(mode) or not (stat.S_ISDIR(mode) or stat.S_ISREG(mode)):
                raise StoreError(f"{p.relative_to(root).as_posix()}: not a regular file or directory "
                                 f"(a retained tree holds plain files only)")
        out.extend((Path(d) / f).relative_to(root).as_posix() for f in files)
    return sorted(out)


def copy_tree(src: Path, dest: Path, files: list[str]) -> None:
    """Copy exactly the validated inventory, never following anything."""
    for rel in files:
        (dest / rel).parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src / rel, dest / rel, follow_symlinks=False)


def tree_digest(root: Path) -> tuple[int, str]:
    """(file count, sha256 over every `path NUL sha256(bytes) LF` line in path order)."""
    h = hashlib.sha256()
    files = tree_files(root)
    for rel in files:
        h.update(rel.encode("utf-8") + b"\0" + hashlib.sha256((root / rel).read_bytes()).hexdigest().encode() + b"\n")
    return len(files), h.hexdigest()


def load_manifest(store: Path | None, required: bool = False) -> list[dict]:
    """The retained releases, in publish order. No store at all is an empty list.
    A store without a manifest is refused where one is REQUIRED (assembling a
    deploy): read as "no releases" it would publish main alone and delete every
    retained release from the live site. publish() writes one into a new store."""
    if store is None:
        return []
    if not (store / MANIFEST).is_file():
        if required:
            raise StoreError(f"the store has no {MANIFEST}; refusing to publish without its releases")
        return []   # fail-direction: not assembling; publish ensures a manifest (or a verified new store) first
    try:
        data = json.loads((store / MANIFEST).read_text(encoding="utf-8"))
    except ValueError as e:
        raise StoreError(f"{MANIFEST}: not JSON ({e})")
    if not isinstance(data, dict) or data.get("schema") != SCHEMA or not isinstance(data.get("releases"), list):
        raise StoreError(f"{MANIFEST}: expected {{\"schema\": {SCHEMA}, \"releases\": [...]}}")
    retired = data.get("retired", [])
    if not isinstance(retired, list) or not all(
            isinstance(r, dict) and isinstance(r.get("version"), str) and isinstance(r.get("commit"), str)
            for r in retired):
        raise StoreError(f"{MANIFEST}: `retired` must be a list of {{\"version\", \"commit\"}}")
    seen: set[str] = {r["version"] for r in retired}
    for r in data["releases"]:
        if not (isinstance(r, dict) and isinstance(r.get("version"), str) and isinstance(r.get("commit"), str)
                and isinstance(r.get("files"), int) and isinstance(r.get("digest"), str)):
            raise StoreError(f"{MANIFEST}: malformed release entry {r!r}")
        if not valid_version(r["version"]):
            raise StoreError(f"{MANIFEST}: invalid version {r['version']!r}")
        if r["version"] in seen:
            raise StoreError(f"{MANIFEST}: {r['version']} is listed twice (or both retained and retired)")
        seen.add(r["version"])
    return data["releases"]


def load_retired(store: Path) -> dict[str, str]:
    """{version: frozen commit} of every release an operator retired from the site."""
    load_manifest(store)   # validates the whole file, `retired` included
    if not (store / MANIFEST).is_file():
        return {}   # fail-direction: only publish's verified new store lacks one, and it has retired nothing
    data = json.loads((store / MANIFEST).read_text(encoding="utf-8"))
    return {r["version"]: r["commit"] for r in data.get("retired", [])}


def write_manifest(store: Path, releases: list[dict]) -> None:
    retired = [{"version": v, "commit": c} for v, c in load_retired(store).items()]
    data = {"schema": SCHEMA, "releases": releases}
    if retired:
        data["retired"] = retired
    (store / MANIFEST).write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def collisions(version: str, main_files: set[str]) -> list[str]:
    """Main-site paths that would share a path with docs/<version>/: the tree's
    root itself or anything under it, or a FILE at one of its ancestors (a main
    page docs/v1.html would have to become a directory). The picker's manifest is
    reserved as a main file even when no build has written it yet."""
    dest = f"docs/{version}"
    files = set(main_files) | {PUBLISHED}
    hits = sorted(f for f in files if f == dest or f.startswith(dest + "/"))
    parts = dest.split("/")
    hits += [a for a in ("/".join(parts[:i]) for i in range(1, len(parts))) if a in files]
    return hits


def site_files(site: Path) -> set[str]:
    """Every file of a built main site. A missing site RAISES: read as empty it
    would clear every collision and undercount the size budget."""
    if not site.is_dir():
        raise StoreError(f"main site {site} is not a directory; build it before freezing or assembling")
    return set(tree_files(site))


def tree_bytes(root: Path, files) -> int:
    return sum((root / f).stat().st_size for f in files)


def over_budget(total: int, budget: int) -> str | None:
    if total <= budget:
        return None
    return (f"the site would be {total / 1e6:.0f} MB, over the {budget / 1e6:.0f} MB budget "
            f"(GitHub Pages publishes at most 1 GB); retire an old release first: on the {BRANCH} branch "
            f"move its entry from `releases` to `retired` in {MANIFEST} and delete its directory")


def picker_manifest(releases: list[dict]) -> bytes:
    """docs/versions.json: `main` first, then releases newest first; paths are
    relative to the site's docs/ directory."""
    versions = [{"name": "main", "path": ""}] + [{"name": r["version"], "path": r["version"] + "/"}
                                                 for r in reversed(releases)]
    return (json.dumps({"schema": SCHEMA, "versions": versions}, separators=(",", ":")) + "\n").encode()


def assemble(site: Path, store: Path | None, budget: int = SITE_BUDGET) -> list[str]:
    """Copy every retained tree into site/docs/<version>/ and write the picker
    manifest. Everything is checked before anything is written, so a refusal
    leaves the site as the main build produced it."""
    releases = load_manifest(store, required=store is not None)
    main_files = site_files(site)
    errors: list[str] = []
    inventory: dict[str, list[str]] = {}
    for r in releases:
        v = r["version"]
        hit = collisions(v, main_files)
        if hit:
            errors.append(f"release {v}: docs/{v}/ collides with the main site at {', '.join(hit[:3])} "
                          f"(rename the main docs path; a published release is frozen)")
            continue
        tree = store / v  # type: ignore[operator]
        if not tree.is_dir():
            errors.append(f"release {v}: listed in {MANIFEST} but its tree is missing from the store")
            continue
        try:
            inventory[v] = tree_files(tree)
            n, digest = tree_digest(tree)
        except StoreError as e:
            errors.append(f"release {v}: {e}")
            continue
        if (n, digest) != (r["files"], r["digest"]):
            errors.append(f"release {v}: stored tree does not match its manifest digest "
                          f"({n} files {digest[:12]} vs {r['files']} files {r['digest'][:12]})")
    if not errors:
        total = tree_bytes(site, main_files) + sum(tree_bytes(store / v, fs) for v, fs in inventory.items())  # type: ignore[operator]
        msg = over_budget(total, budget)
        if msg:
            errors.append(msg)
    if errors:
        return errors
    for r in releases:
        copy_tree(store / r["version"], site / "docs" / r["version"], inventory[r["version"]])  # type: ignore[operator]
    (site / PUBLISHED).parent.mkdir(parents=True, exist_ok=True)
    (site / PUBLISHED).write_bytes(picker_manifest(releases))
    return []


def add(store: Path, main_site: Path, tree: Path, version: str, commit: str, budget: int = SITE_BUDGET) -> str:
    """Freeze one rendered release tree into the store. Returns "added" or
    "present" (the same commit is already stored: a re-run after a push that
    succeeded resumes instead of failing). A stored version whose tag now names
    another commit is refused: a published release is never replaced."""
    if not valid_version(version):
        raise StoreError(f"release {version!r}: a retained version is one path segment matching {VERSION_RE.pattern}")
    releases = load_manifest(store)
    for r in releases:
        if r["version"] == version:
            if r["commit"] != commit:
                raise StoreError(f"release {version}: stored from {r['commit'][:12]} but the tag now names "
                                 f"{commit[:12]}; a published release is frozen (publish a new tag)")
            return "present"
    hit = collisions(version, site_files(main_site))
    if hit:
        raise StoreError(f"release {version}: docs/{version}/ collides with the main site at {', '.join(hit[:3])}")
    if not tree.is_dir() or not tree_files(tree):   # tree_files also refuses links
        raise StoreError(f"release {version}: rendered tree {tree} is empty")
    dest = store / version
    if dest.exists():
        raise StoreError(f"release {version}: {dest} exists in the store but {MANIFEST} does not list it")
    files = tree_files(tree)
    main_files = site_files(main_site)
    total = (tree_bytes(main_site, main_files) + tree_bytes(tree, files)
             + sum(tree_bytes(store / r["version"], tree_files(store / r["version"])) for r in releases))
    msg = over_budget(total, budget)
    if msg:
        raise StoreError(f"release {version}: {msg}")
    copy_tree(tree, dest, files)
    n, digest = tree_digest(dest)
    releases.append({"version": version, "commit": commit, "files": n, "digest": digest})
    write_manifest(store, releases)
    return "added"


def tag_commits() -> list[tuple[str, str]]:
    """Every `v*` tag with its commit, oldest first (the order releases were cut)."""
    out = git("for-each-ref", "--sort=creatordate", "--format=%(refname:strip=2) %(objectname)", "refs/tags/v*").stdout
    tags = []
    for line in out.splitlines():
        name = line.split(" ", 1)[0]
        tags.append((name, git("rev-parse", f"{name}^{{commit}}").stdout.strip()))
    return tags


def render_release(tag: str, out: Path) -> None:
    """Render TAG's docs tree into out/docs/<tag>/ with the site generator."""
    try:
        r = subprocess.run([sys.executable, str(REPO / "scripts/site/build.py"), "--release", tag,
                            "--out", str(out), "--quiet"], cwd=REPO, capture_output=True, text=True,
                           timeout=RENDER_TIMEOUT)
    except subprocess.TimeoutExpired:
        raise StoreError(f"release {tag}: render did not finish within {RENDER_TIMEOUT} s") from None
    if r.returncode != 0:
        raise StoreError(f"release {tag}: render failed (rc {r.returncode})\n{r.stderr}")


def publish(store: Path, main_site: Path, only: list[str] | None = None, render=render_release,
            new_store: bool = False) -> list[str]:
    """Render and freeze every site-era tag the store lacks. Reconciling ALL tags,
    not only the one that triggered the run, is what makes delivery reliable: a
    run GitHub cancelled while it was queued is picked up by the next one."""
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import build as B  # noqa: E402  (sibling module: the site-era rule lives with the renderer)
    if not (store / MANIFEST).exists():
        # Only a NEW store may be given an empty manifest, and "new" is the caller's
        # verified claim (docs-release.yml opens an orphan only after store-sha found
        # no trace of a store), never an inference from the files: a fully retired
        # store holds nothing but its manifest, and a fresh one written over it
        # would forget every retirement and re-freeze those releases.
        if not new_store:
            raise StoreError(f"the store has no {MANIFEST}; restore it from the branch history "
                             f"(an empty one is written only into a new store)")
        extra = sorted(p.name for p in store.iterdir() if p.name not in (".git", "README.md"))
        if extra:
            raise StoreError(f"the store has no {MANIFEST} but holds {', '.join(extra[:3])}; "
                             f"restore the manifest from the branch history")
        write_manifest(store, [])
    if not (store / "README.md").exists():
        (store / "README.md").write_text(STORE_README, encoding="utf-8")
    changed: list[str] = []
    for name, commit in tag_commits():
        if only and name not in only:
            continue
        stored = {r["version"]: r["commit"] for r in load_manifest(store)}
        stored.update(load_retired(store))   # a retired release stays off the site
        if name in stored:
            # Judged before any eligibility filter: a stored tag moved anywhere,
            # even to a commit older than the site, is a moved release.
            if stored[name] != commit:
                raise StoreError(f"release {name}: stored from {stored[name][:12]} but the tag now names "
                                 f"{commit[:12]}; a published release is frozen (publish a new tag)")
            continue
        if not valid_version(name):
            print(f"releases: skipping tag {name!r}: not a single-segment version name")
            continue
        if not B.is_site_era(commit):
            print(f"releases: skipping tag {name}: it predates the docs site")
            continue
        with tempfile.TemporaryDirectory(prefix="release-tree-") as tmp:
            render(name, Path(tmp))
            status = add(store, main_site, Path(tmp) / "docs" / name, name, commit)
            if status == "added":
                changed.append(name)
                print(f"releases: froze {name} @ {commit[:12]}")
    return changed


def remote_store_sha(remote: str = "origin") -> str | None:
    """Fetch the store branch and return its commit; None when the branch does not
    exist yet. A failed lookup RAISES: publishing without the releases would
    delete every one of them from the live site."""
    r = git("ls-remote", "--exit-code", "--heads", remote, BRANCH, check=False, timeout=NET_TIMEOUT)
    if r.returncode == 2:
        return None   # fail-direction: rc 2 is only "no such ref"; every other failure raises below
    if r.returncode != 0:
        raise StoreError(f"cannot query {remote} for {BRANCH}: {r.stderr.strip()}")
    f = git("fetch", "--no-tags", "--quiet", remote, f"+refs/heads/{BRANCH}:{STORE_REF}", check=False,
            timeout=NET_TIMEOUT)
    if f.returncode != 0:
        raise StoreError(f"cannot fetch {BRANCH}: {f.stderr.strip()}")
    return git("rev-parse", "--verify", f"{STORE_REF}^{{commit}}").stdout.strip()


def materialise(ref: str, dest: Path) -> str:
    """Extract the store at REF (a commit, fetched from origin when absent) into dest."""
    r = git("rev-parse", "--verify", "--quiet", f"{ref}^{{commit}}", check=False)
    if r.returncode != 0:
        f = git("fetch", "--no-tags", "--quiet", "origin", ref, check=False, timeout=NET_TIMEOUT)
        r = git("rev-parse", "--verify", "--quiet", f"{ref}^{{commit}}", check=False)
        if r.returncode != 0:
            raise StoreError(f"store commit {ref} is not available: {f.stderr.strip()}")
    sha = r.stdout.strip()
    dest.mkdir(parents=True, exist_ok=True)
    # Streamed, never buffered: the store grows with every release.
    with tempfile.TemporaryFile() as err:
        # deadline: a hung local archive is owned by the caller's limit (verify_live's deadline or the job's)
        proc = subprocess.Popen(["git", "archive", "--format=tar", sha], cwd=REPO, stdout=subprocess.PIPE, stderr=err)
        bad = None
        try:
            with tarfile.open(fileobj=proc.stdout, mode="r|") as t:
                t.extractall(dest, filter="data")   # refuses absolute paths, `..` and links leaving dest
        except (tarfile.TarError, OSError) as e:
            bad = e
            proc.kill()
        finally:
            proc.stdout.close()
            try:
                rc = proc.wait(timeout=GIT_TIMEOUT)   # its stdout is closed: a live archive dies of SIGPIPE
            except subprocess.TimeoutExpired:
                proc.kill()
                rc = proc.wait(timeout=GIT_TIMEOUT)
        if rc not in (0, -9) or (rc == -9 and bad is None):
            err.seek(0)
            raise StoreError(f"store commit {sha[:12]}: git archive failed: {err.read().decode(errors='replace').strip()}")
        if bad is not None:
            raise StoreError(f"store commit {sha[:12]}: cannot extract: {bad}")
    return sha


def deletable_tags() -> dict[str, str]:
    """Tags release.yml's pre-release cleanup may delete, as a POSITIVE map of tag
    to ref object: a release the fetched store holds (or retired) whose tag still
    names the frozen commit, and a tag older than the docs site. Any other tag
    (one pushed after this checkout, one moved, or one whose docs run was
    cancelled or failed) is kept, because a tag is the only way its docs reach
    the store."""
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import build as B  # noqa: E402
    sha = remote_store_sha()
    stored: dict[str, str] = {}     # verified: tree present and matching, or retired
    listed: set[str] = set()        # every version the store names, verified or not
    if sha is not None:
        with tempfile.TemporaryDirectory(prefix="release-store-") as tmp:
            store = Path(tmp)
            materialise(sha, store)
            # A retained release counts only if its tree is really there, as its
            # digest says: a manifest line alone does not keep its docs published.
            for e in load_manifest(store, required=True):
                listed.add(e["version"])
                try:
                    ok = (store / e["version"]).is_dir() and tree_digest(store / e["version"]) == (e["files"], e["digest"])
                except StoreError:
                    ok = False
                if ok:
                    stored[e["version"]] = e["commit"]
            retired = load_retired(store)
            stored.update(retired)
            listed |= set(retired)
    # A listed release is safe only when verified AND still at its frozen commit;
    # the pre-site rule is for tags the store never named.
    safe = {t: stored.get(t) == c if t in listed else not B.is_site_era(c) for t, c in tag_commits()}
    objects = tag_objects()
    return {t: objects[t] for t, ok in sorted(safe.items()) if ok and t in objects}


def tag_objects() -> dict[str, str]:
    """{tag: the object its ref names} (a tag object when annotated): what the
    cleanup compares with the live ref before deleting, so a tag moved since this
    list was made is kept."""
    out = git("for-each-ref", "--format=%(refname:strip=2) %(objectname)", "refs/tags/v*").stdout
    return dict(line.split(" ", 1) for line in out.splitlines() if " " in line)


def store_marker_exists(remote: str = "origin") -> bool:
    """Whether MARKER_TAG exists on the remote: the durable record that a store
    was ever created, pushed beside the branch when the store is first made.
    It lives in the repository, not in the replaceable Pages deployment, so a
    site rollback or a missing picker cannot erase it. A failed query raises."""
    r = git("ls-remote", "--exit-code", remote, f"refs/tags/{MARKER_TAG}", check=False, timeout=NET_TIMEOUT)
    if r.returncode == 2:
        return False
    if r.returncode != 0:
        raise StoreError(f"cannot query {remote} for {MARKER_TAG}: {r.stderr.strip()}")
    return True


def push_store(remote: str = "origin") -> str:
    """Publish the local store branch, and the marker tag when the remote lacks
    it, in ONE atomic push: either both land or neither does, so a store can
    never exist on the remote without the marker that makes its loss detectable.
    Returns "pushed branch", "pushed marker" or "up to date"."""
    local = git("rev-parse", "--verify", "--quiet", f"refs/heads/{BRANCH}", check=False).stdout.strip()
    if not local:
        raise StoreError(f"no local {BRANCH} branch to push")
    r = git("ls-remote", "--heads", remote, BRANCH, check=False, timeout=NET_TIMEOUT)
    if r.returncode != 0:
        raise StoreError(f"cannot query {remote} for {BRANCH}: {r.stderr.strip()}")
    remote_sha = r.stdout.split()[0] if r.stdout.strip() else None
    refspecs = []
    if remote_sha != local:
        refspecs.append(f"refs/heads/{BRANCH}:refs/heads/{BRANCH}")
    if not store_marker_exists(remote):
        refspecs.append(f"{local}:refs/tags/{MARKER_TAG}")
    if not refspecs:
        return "up to date"
    p = git("push", "--atomic", remote, *refspecs, check=False, timeout=NET_TIMEOUT)
    if p.returncode != 0:
        raise StoreError(f"push of {' '.join(refspecs)} refused, nothing published: {p.stderr.strip()}")
    return "pushed branch" if remote_sha != local else "pushed marker"


def check_store_absent_is_new() -> None:
    """With no store branch, refuse unless no store was ever created. Recreating
    a LOST store from the surviving tags would silently drop every release whose
    tag was since cleaned up, and every retirement record. The evidence is
    MARKER_TAG; a release TAG proves nothing here, since the first tag always
    arrives before the store exists."""
    if store_marker_exists():
        raise StoreError(f"the {BRANCH} branch is missing but tag {MARKER_TAG} shows a store was created; "
                         f"restore the branch from its last commit")


def assemble_from(site: Path, releases: str) -> tuple[str, list[str]]:
    """Assemble from `none` (no store), `remote` (fetch the branch now) or a store
    commit. Returns (store sha or "none", errors)."""
    if releases not in ("remote", "none") and not SHA_RE.fullmatch(releases):
        raise StoreError(f"releases {releases!r}: expected remote, none or a full store commit SHA")
    sha = remote_store_sha() if releases == "remote" else (None if releases == "none" else releases)
    if sha is None and releases == "remote":
        # No store branch. Before the first release that is the normal state; after
        # one it means the store was deleted, and publishing main alone would take
        # every retained release off the site.
        check_store_absent_is_new()
    if sha is None:
        return "none", assemble(site, None)
    with tempfile.TemporaryDirectory(prefix="release-store-") as tmp:
        sha = materialise(sha, Path(tmp))
        return sha, assemble(site, Path(tmp))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("publish")
    p.add_argument("--store", type=Path, required=True)
    p.add_argument("--main-site", type=Path, required=True)
    p.add_argument("--tag", action="append", help="only these tags (default: every tag the store lacks)")
    p.add_argument("--new-store", action="store_true",
                   help="the store is a new orphan (store-sha printed none): write its first, empty manifest")
    a = sub.add_parser("assemble")
    a.add_argument("--site", type=Path, required=True)
    src = a.add_mutually_exclusive_group(required=True)
    src.add_argument("--store", type=Path, help="a checked-out store")
    src.add_argument("--releases", help="`remote`, `none`, or a store commit")
    a.add_argument("--github-output", type=Path, help="append store=<sha|none> for later jobs (with --releases)")
    sub.add_parser("store-sha")
    sub.add_parser("push-store", help="push the store branch and, when missing, its marker tag atomically")
    sub.add_parser("deletable", help="print the tags release.yml may delete, JSON {tag: ref object}")
    args = ap.parse_args()
    if args.cmd == "assemble" and args.store is not None and args.github_output:
        # A checked-out directory has no commit a later job could assemble again.
        ap.error("--github-output records a store commit; use it with --releases")
    try:
        if args.cmd == "deletable":
            print(json.dumps(deletable_tags()))
            return 0
        if args.cmd == "push-store":
            print(push_store())
            return 0
        if args.cmd == "store-sha":
            sha = remote_store_sha()
            if sha is None:
                check_store_absent_is_new()   # `none` means "start a new store": only when it is one
            print(sha or "none")
            return 0
        if args.cmd == "publish":
            changed = publish(args.store, args.main_site, args.tag, new_store=args.new_store)
            print(f"releases: {len(changed)} release(s) frozen" + (f": {', '.join(changed)}" if changed else ""))
            return 0
        if args.store is not None:
            sha, errors = "local", assemble(args.site, args.store)   # no receipt: --github-output refused above
        else:
            sha, errors = assemble_from(args.site, args.releases)
    except StoreError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1
    for e in errors:
        print(f"ERROR: {e}", file=sys.stderr)
    if errors:
        return 1
    if args.github_output:
        with args.github_output.open("a", encoding="utf-8") as f:
            f.write(f"store={sha}\n")
    n = len(json.loads((args.site / PUBLISHED).read_text(encoding="utf-8"))["versions"]) - 1
    print(f"releases: {n} retained release tree(s) assembled into {args.site} (store {sha})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
