/* ease_lut.h -- Auto-generated by tools/gen_ease_lut.py (2026-03-19T19:55:03Z)
 *
 * 64-entry ease-in-out curve (quarter-sine).
 * Index 0..63 maps to eased value 0..255.
 * For full ease-in-out: ease_lut[phase < 64 ? phase : 127 - phase]
 *
 * DO NOT EDIT -- regenerate with: python3 tools/gen_ease_lut.py
 */

#pragma once

#include "kernel/types.h"

static const uint8_t ease_lut[64] = {
      0,   6,  13,  19,  25,  32,  38,  44,  /*  0.. 7 */
     51,  57,  63,  69,  75,  81,  87,  93,  /*  8..15 */
     99, 105, 111, 116, 122, 127, 133, 138,  /* 16..23 */
    144, 149, 154, 159, 164, 169, 173, 178,  /* 24..31 */
    183, 187, 191, 195, 199, 203, 207, 211,  /* 32..39 */
    214, 218, 221, 224, 227, 230, 232, 235,  /* 40..47 */
    237, 240, 242, 244, 245, 247, 249, 250,  /* 48..55 */
    251, 252, 253, 254, 254, 255, 255, 255  /* 56..63 */
};

