#!/usr/bin/env bash
# build-shim.sh -- Clone and build rhboot/shim v16.1 with Impossible OS VENDOR_CERT_FILE.
#
# Usage:
#   bash scripts/build-shim.sh
#
# Output:
#   shim/shimx64.efi   -- shim binary (place as EFI/BOOT/BOOTX64.EFI on ESP)
#   shim/mmx64.efi     -- MokManager (place as EFI/BOOT/mmx64.efi on ESP)
#
# Prerequisites:
#   apt install gnu-efi libelf-dev libssl-dev pesign
#   keys/MOK.cer must exist (generated by openssl, see keys/README.md)
#
# This script is idempotent -- re-running rebuilds the shim with the current MOK.cer.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SHIM_DIR="$REPO_ROOT/shim"
BUILD_DIR="/tmp/shim-build-$$"
MOK_CER="$REPO_ROOT/keys/MOK.cer"
SHIM_VERSION="16.1"
SHIM_URL="https://github.com/rhboot/shim.git"

echo "[SHIM] Building rhboot/shim v${SHIM_VERSION} with Impossible OS MOK.cer"

# Check prerequisites
if [ ! -f "$MOK_CER" ]; then
    echo "[ERROR] keys/MOK.cer not found. Run: openssl req -new -x509 ..."
    exit 1
fi
for tool in gcc make objcopy; do
    command -v "$tool" >/dev/null || { echo "[ERROR] Missing: $tool"; exit 1; }
done

# Clone shim
echo "[SHIM] Cloning rhboot/shim..."
git clone --depth=1 "$SHIM_URL" "$BUILD_DIR"
cd "$BUILD_DIR"
git submodule update --init gnu-efi

# Build
echo "[SHIM] Building shimx64.efi + mmx64.efi..."
make VENDOR_CERT_FILE="$MOK_CER" ARCH=x86_64 shimx64.efi mmx64.efi

# Copy outputs to shim/
mkdir -p "$SHIM_DIR"
cp shimx64.efi mmx64.efi "$SHIM_DIR/"
echo "[SHIM] shimx64.efi: $(wc -c < "$SHIM_DIR/shimx64.efi") bytes"
echo "[SHIM] mmx64.efi:   $(wc -c < "$SHIM_DIR/mmx64.efi") bytes"

# Cleanup
cd /
rm -rf "$BUILD_DIR"

echo "[SHIM] Done -- shim/ is ready. Run bash scripts/build.sh to package into ISO."
echo ""
echo "  EFI/BOOT/BOOTX64.EFI ← shim/shimx64.efi  (THIS SCRIPT)"
echo "  EFI/BOOT/grubx64.efi ← build/tools/BOOTX64.EFI (signed with MOK)"
echo "  EFI/BOOT/mmx64.efi   ← shim/mmx64.efi     (THIS SCRIPT)"
