#!/usr/bin/env bash
# ============================================================================
# gen-loader-identity.sh -- emit build/boot_loader_identity.h with the
#                           current git commit's identity baked in.
#
# Both the UEFI bootloader (src/boot/uefi/bootx64.c) and the kernel
# include this header so the bootloader can populate
# boot_info.loader_identity with a stable build-identity tuple
# (git SHA-1 + commit unix time + git describe label) at handoff time.
#
# Owner: Bootloader Build Identity feature (boot-protocol-abi-handoff
#        TODO; see todo/01-boot-platform/TODO-01-boot-protocol-abi-handoff.md
#        anchor `#20-bootloader-build-identity`).
#
# Usage (called from the top-level Makefile):
#   bash tools/boot-info-manifest/gen-loader-identity.sh
#
# Always rewrites build/boot_loader_identity.h via mktemp+mv so a
# concurrent compile cannot read a half-written header. Idempotent at
# the file-content level: writes are byte-identical when neither the
# git HEAD nor the working-tree dirty state has changed.
#
# Fallback: if `git` is unavailable or the working tree isn't a git
# repo (CI build from a tarball, for example), fall back to the all-
# zero identity so the bootloader still compiles -- the kernel
# detects "loader did not populate" via the all-zero git_sha sentinel
# and renders identity as "unavailable" in the fatal screen.
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BUILD_DIR="${BUILD_DIR:-$REPO_ROOT/build}"
OUT="$BUILD_DIR/boot_loader_identity.h"

mkdir -p "$BUILD_DIR"

# Probe git. Any error here -> fallback to zero identity.
GIT_OK=1
GIT_SHA_HEX=""
BUILD_TIME=0
BUILD_LABEL="unknown"
if command -v git >/dev/null 2>&1 && \
   git -C "$REPO_ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    GIT_SHA_HEX="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || echo)"
    BUILD_TIME="$(git -C "$REPO_ROOT" log -1 --format=%ct 2>/dev/null || echo 0)"
    BUILD_LABEL="$(git -C "$REPO_ROOT" describe --dirty --always --tags 2>/dev/null || \
                   git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
    if [ -z "$GIT_SHA_HEX" ] || [ ${#GIT_SHA_HEX} -ne 40 ]; then
        GIT_OK=0
    fi
else
    GIT_OK=0
fi

# Truncate label to 23 bytes + NUL (struct layout: char build_label[24]).
# A label longer than that is operator-readable garnish; truncating
# preserves the leading bytes which carry the most discriminating
# information (commit SHA prefix, tag name).
BUILD_LABEL="${BUILD_LABEL:0:23}"

# Convert the 40-char hex SHA to a C array of 20 bytes. On the no-git
# fallback path, emit all zeros (the boot_loader_identity zero sentinel).
if [ "$GIT_OK" -eq 1 ]; then
    # Format: "0x12, 0x34, ..." (20 bytes). awk handles the conversion
    # without needing python on the build host.
    GIT_SHA_BYTES="$(printf '%s' "$GIT_SHA_HEX" | \
        awk '{
            for (i = 1; i <= length($0); i += 2) {
                if (i > 1) printf ", ";
                printf "0x%s", substr($0, i, 2);
            }
        }')"
else
    GIT_SHA_BYTES="0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
fi

# Atomic write via mktemp + mv so the compiler never sees a torn file.
TMP="$(mktemp "$BUILD_DIR/boot_loader_identity.h.XXXXXX")"
trap 'rm -f "$TMP"' EXIT
{
    echo "/* AUTO-GENERATED by tools/boot-info-manifest/gen-loader-identity.sh."
    echo " * DO NOT EDIT BY HAND. Regenerated on every build."
    echo " *"
    echo " * Captures the bootloader's build identity (git HEAD + commit time +"
    echo " * git-describe label) so boot_info.loader_identity carries a stable"
    echo " * triple that survives across reboots and surfaces in:"
    echo " *   - HKLM\\\\SYSTEM\\\\Boot\\\\Decision\\\\Loader{GitSha,BuildTime,BuildLabel}"
    echo " *   - X:\\\\Diag\\\\boot-loader-identity.txt (BlackBox transcript)"
    echo " *   - boot_version_fault NVRAM record (prior-fault attribution)"
    echo " */"
    echo "#ifndef BOOT_LOADER_IDENTITY_H"
    echo "#define BOOT_LOADER_IDENTITY_H"
    echo ""
    echo "/* git rev-parse HEAD (20 raw bytes; all-zero on no-git fallback). */"
    echo "#define BOOT_LOADER_GIT_SHA      { $GIT_SHA_BYTES }"
    echo ""
    echo "/* git log -1 --format=%ct (commit unix time; 0 on fallback). */"
    echo "#define BOOT_LOADER_BUILD_TIME   ${BUILD_TIME}ULL"
    echo ""
    echo "/* git describe --dirty --always --tags (truncated to 23 bytes + NUL). */"
    echo "#define BOOT_LOADER_BUILD_LABEL  \"$BUILD_LABEL\""
    echo ""
    echo "#endif /* BOOT_LOADER_IDENTITY_H */"
} > "$TMP"

# Idempotency: only mv if the content actually changed. Avoids
# pointlessly invalidating downstream object dependencies on every
# build when nothing in git changed.
if [ -f "$OUT" ] && cmp -s "$TMP" "$OUT"; then
    rm -f "$TMP"
    trap - EXIT
    exit 0
fi
mv "$TMP" "$OUT"
trap - EXIT
echo "[gen-loader-identity] $OUT updated (git=${GIT_SHA_HEX:0:12} time=$BUILD_TIME label=$BUILD_LABEL)" >&2
