#!/usr/bin/env bash
# ============================================================================
# gen-proto-sha-header.sh -- emit build/boot_proto_sha.h from the
#                            boot-info ABI manifest JSON.
#
# Input:  build/boot-info-abi.kernel.json  (produced by the boot-info-abi
#                                           manifest dumper; pinned to
#                                           current BOOT_INFO_VERSION)
# Output: build/boot_proto_sha.h            (included by the kernel TU
#                                           src/kernel/main/boot_proto.c
#                                           and the bootloader body so
#                                           both sides see byte-identical
#                                           expected SHA-256)
#
# The header emits:
#   #define KERNEL_ABI_SHA256 { 0x.., 0x.., ... }    /* 32 bytes */
#   #define KERNEL_ABI_SHA256_HEX "e4b23e94...ecf549"
#
# Idempotent: if the generated bytes match the on-disk header, do not
# touch the file (preserves mtime so make does not rebuild downstream
# unless the manifest actually changed).
#
# Canonical doc: the sha256 canonicality invariant is documented in the
# boot-protocol manifest generation stage (docs/boot/boot-protocol.md).
# ============================================================================
set -euo pipefail

INPUT="${1:-build/boot-info-abi.kernel.json}"
OUTPUT="${2:-build/boot_proto_sha.h}"

if [ ! -f "$INPUT" ]; then
    echo "gen-proto-sha-header: input manifest not found: $INPUT" >&2
    exit 1
fi

# Pull the canonical, view-independent ABI fingerprint from the
# manifest "sha256" field. The dumper computes it over the tuple
# (version, struct_size, per-field name+offset+size) in F() emission
# order via a fixed delimited byte stream prefixed `BOOTINFO-ABI-V1\n`,
# never from the JSON bytes. Hashing the raw JSON file would make the
# .bootproto BAD_SHA diagnostic fire on cosmetic JSON formatting
# changes that do not change the ABI -- exactly the failure mode the
# canonical-hash rework (2026-04-23) was designed to close.
HEX=$(python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    m = json.load(f)
sha = m.get('sha256', '')
if len(sha) != 64 or not all(c in '0123456789abcdef' for c in sha):
    sys.stderr.write(f\"gen-proto-sha-header: manifest sha256 invalid: {sha!r}\\n\")
    sys.exit(2)
print(sha)
" "$INPUT")

if [ ${#HEX} -ne 64 ]; then
    echo "gen-proto-sha-header: unexpected sha256 length ${#HEX} (want 64)" >&2
    exit 2
fi

# Build the C-array initializer: "0xNN, 0xNN, ..." 32 comma-separated
# hex byte values on ONE line. A multi-line #define would need
# backslash-newline on every line; keeping the initializer on a
# single line sidesteps that and keeps the generator simple.
CARRAY=$(python3 -c "
h = '$HEX'
bs = [int(h[i:i+2], 16) for i in range(0, 64, 2)]
print(', '.join(f'0x{b:02x}' for b in bs))
")

NEW=$(cat <<EOF
/* ============================================================================
 * boot_proto_sha.h -- AUTO-GENERATED from build/boot-info-abi.kernel.json.
 *
 * DO NOT EDIT MANUALLY. Regenerated by
 * tools/boot-info-manifest/gen-proto-sha-header.sh whenever the ABI
 * manifest's sha256 changes. Included by the kernel TU that populates
 * the .bootproto ELF section and by the bootloader body that compares
 * the kernel descriptor against its compile-time expected bytes.
 *
 * Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ") UTC
 * Source hash:  $HEX
 * ============================================================================ */

#ifndef BOOT_PROTO_SHA_H
#define BOOT_PROTO_SHA_H

#define KERNEL_ABI_SHA256 { $CARRAY }

#define KERNEL_ABI_SHA256_HEX "$HEX"

#endif /* BOOT_PROTO_SHA_H */
EOF
)

# Idempotent write: only touch file if contents differ.
if [ -f "$OUTPUT" ] && diff -q <(echo "$NEW") "$OUTPUT" >/dev/null 2>&1; then
    exit 0
fi

# Atomic publish: write to a sibling tempfile and rename over the final
# path. Prevents a racing make / compiler from reading a torn header.
# mv is atomic within the same filesystem; the tempfile lives beside the
# target so cross-fs rename is not a concern.
OUTDIR="$(dirname "$OUTPUT")"
mkdir -p "$OUTDIR"
TMP="$(mktemp "$OUTDIR/boot_proto_sha.h.XXXXXX")"
trap 'rm -f "$TMP"' EXIT
echo "$NEW" > "$TMP"
mv "$TMP" "$OUTPUT"
trap - EXIT
echo "[TOOL] $OUTPUT emitted (sha=${HEX:0:12}...)"
