#!/usr/bin/env bash
# ============================================================================
# gen-proto-sha-header.sh -- emit build/boot_proto_sha.h from the
#                            boot-info ABI manifest JSON.
#
# Input:  build/boot-info-abi.kernel.json  (produced by the boot-info-abi
#                                           manifest dumper; pinned to
#                                           current BOOT_INFO_VERSION)
# Output: build/boot_proto_sha.h            (included by the kernel TU
#                                           src/kernel/main/boot_proto.c
#                                           and the bootloader body so
#                                           both sides see byte-identical
#                                           expected SHA-256)
#
# The header emits:
#   #define KERNEL_ABI_SHA256 { 0x.., 0x.., ... }    /* 32 bytes */
#   #define KERNEL_ABI_SHA256_HEX "e4b23e94...ecf549"
#
# Idempotent: if the generated bytes match the on-disk header, do not
# touch the file (preserves mtime so make does not rebuild downstream
# unless the manifest actually changed).
#
# Canonical doc: the sha256 canonicality invariant is documented in the
# boot-protocol manifest generation stage (docs/boot/boot-protocol.md).
# ============================================================================
set -euo pipefail

INPUT="${1:-build/boot-info-abi.kernel.json}"
OUTPUT="${2:-build/boot_proto_sha.h}"

if [ ! -f "$INPUT" ]; then
    echo "gen-proto-sha-header: input manifest not found: $INPUT" >&2
    exit 1
fi

# Canonicalize: hash the raw file bytes. No re-formatting; the manifest
# dumper already emits a stable representation.
HEX=$(sha256sum "$INPUT" | awk '{print $1}')

if [ ${#HEX} -ne 64 ]; then
    echo "gen-proto-sha-header: unexpected sha256 length ${#HEX} (want 64)" >&2
    exit 2
fi

# Build the C-array initializer: "0xNN, 0xNN, ..." 32 comma-separated
# hex byte values on ONE line. A multi-line #define would need
# backslash-newline on every line; keeping the initializer on a
# single line sidesteps that and keeps the generator simple.
CARRAY=$(python3 -c "
h = '$HEX'
bs = [int(h[i:i+2], 16) for i in range(0, 64, 2)]
print(', '.join(f'0x{b:02x}' for b in bs))
")

NEW=$(cat <<EOF
/* ============================================================================
 * boot_proto_sha.h -- AUTO-GENERATED from build/boot-info-abi.kernel.json.
 *
 * DO NOT EDIT MANUALLY. Regenerated by
 * tools/boot-info-manifest/gen-proto-sha-header.sh whenever the ABI
 * manifest's sha256 changes. Included by the kernel TU that populates
 * the .bootproto ELF section and by the bootloader body that compares
 * the kernel descriptor against its compile-time expected bytes.
 *
 * Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ") UTC
 * Source hash:  $HEX
 * ============================================================================ */

#ifndef BOOT_PROTO_SHA_H
#define BOOT_PROTO_SHA_H

#define KERNEL_ABI_SHA256 { $CARRAY }

#define KERNEL_ABI_SHA256_HEX "$HEX"

#endif /* BOOT_PROTO_SHA_H */
EOF
)

# Idempotent write: only touch file if contents differ.
if [ -f "$OUTPUT" ] && diff -q <(echo "$NEW") "$OUTPUT" >/dev/null 2>&1; then
    exit 0
fi

mkdir -p "$(dirname "$OUTPUT")"
echo "$NEW" > "$OUTPUT"
echo "[TOOL] $OUTPUT emitted (sha=${HEX:0:12}...)"
