#!/usr/bin/env bash
# ============================================================================
# debug.sh -- Launch QEMU in debug mode + connect GDB with kernel symbols
#
# Usage:
#   bash scripts/debug.sh                          # Default breakpoints
#   bash scripts/debug.sh --breakpoint=my_func     # Add custom breakpoint
#   bash scripts/debug.sh --breakpoint=vfs_open --breakpoint=fat32_read
#   bash scripts/debug.sh --no-default-bp          # Skip default breakpoints
#
# Default breakpoints: kernel_main, panic, page_fault_handler,
#                       general_protection_fault_handler, double_fault_handler
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

KERNEL_ELF="$REPO_ROOT/build/kernel.exe"
KERNEL_MAP="$REPO_ROOT/build/kernel.map"
GDB_INIT="$REPO_ROOT/build/.gdbinit-kernel"

# ---- Colors ----
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
DIM='\033[0;90m'
NC='\033[0m'

# ---- Default breakpoints ----
DEFAULT_BPS=(
    kernel_main
    panic
    page_fault_handler
    general_protection_fault_handler
    double_fault_handler
)

# ---- Parse arguments ----
CUSTOM_BPS=()
USE_DEFAULT_BPS=true

for arg in "$@"; do
    case "$arg" in
        --breakpoint=*)
            CUSTOM_BPS+=("${arg#--breakpoint=}")
            ;;
        --no-default-bp)
            USE_DEFAULT_BPS=false
            ;;
        -h|--help)
            echo "Usage: $0 [--breakpoint=<function>]... [--no-default-bp]"
            echo ""
            echo "Options:"
            echo "  --breakpoint=<func>   Add a custom breakpoint"
            echo "  --no-default-bp       Skip default breakpoints"
            echo ""
            echo "Default breakpoints:"
            for bp in "${DEFAULT_BPS[@]}"; do
                echo "  - $bp"
            done
            exit 0
            ;;
        *)
            echo "Unknown argument: $arg"
            echo "Usage: $0 [--breakpoint=<function>]... [--no-default-bp]"
            exit 1
            ;;
    esac
done

# ---- Preflight ----
if [ ! -f "$KERNEL_ELF" ]; then
    echo -e "${YELLOW}kernel.exe not found. Building...${NC}"
    bash "$REPO_ROOT/scripts/build.sh" >/dev/null 2>&1
fi

if ! command -v gdb &>/dev/null; then
    echo "ERROR: gdb not found. Install with: sudo apt install -y gdb"
    exit 1
fi

# ---- Generate GDB init script ----
cat > "$GDB_INIT" << 'GDBEOF'
# Auto-generated by scripts/debug.sh -- do not edit
set confirm off
set pagination off
set disassembly-flavor intel

# Connect to QEMU
target remote localhost:1234

GDBEOF

# Add symbol file
echo "symbol-file $KERNEL_ELF" >> "$GDB_INIT"

# Add breakpoints
if [ "$USE_DEFAULT_BPS" = true ]; then
    for bp in "${DEFAULT_BPS[@]}"; do
        echo "break $bp" >> "$GDB_INIT"
    done
fi
for bp in "${CUSTOM_BPS[@]}"; do
    echo "break $bp" >> "$GDB_INIT"
done

# Final message
cat >> "$GDB_INIT" << 'GDBEOF'

echo \n
echo ╔══════════════════════════════════════════════════╗\n
echo ║  GDB connected to Impossible OS kernel          ║\n
echo ║                                                  ║\n
echo ║  Type 'c' to continue booting                   ║\n
echo ║  Type 'bt' for backtrace                        ║\n
echo ║  Type 'info registers' for CPU state            ║\n
echo ║  Type 'x/20i $rip' to disassemble at RIP        ║\n
echo ╚══════════════════════════════════════════════════╝\n
echo \n
GDBEOF

# ---- Banner ----
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}  Impossible OS -- GDB Debug Session${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${DIM}Kernel:  $KERNEL_ELF${NC}"
if [ -f "$KERNEL_MAP" ]; then
    SYM_COUNT=$(grep -c ' [Tt] ' "$KERNEL_MAP" 2>/dev/null || echo 0)
    echo -e "  ${DIM}Symbols: $KERNEL_MAP ($SYM_COUNT text symbols)${NC}"
fi
echo ""
echo -e "  ${GREEN}Breakpoints:${NC}"
if [ "$USE_DEFAULT_BPS" = true ]; then
    for bp in "${DEFAULT_BPS[@]}"; do
        echo -e "    ${DIM}• $bp${NC}"
    done
fi
for bp in "${CUSTOM_BPS[@]}"; do
    echo -e "    ${GREEN}• $bp (custom)${NC}"
done
echo ""

# ---- Launch QEMU in background ----
echo -e "  ${DIM}Starting QEMU (paused, GDB stub on :1234)...${NC}"
"$SCRIPT_DIR/run-qemu.sh" --debug &
QEMU_PID=$!

# Wait for QEMU GDB stub to be ready
sleep 2

# Verify QEMU is still running
if ! kill -0 "$QEMU_PID" 2>/dev/null; then
    echo "ERROR: QEMU failed to start"
    exit 1
fi

echo -e "  ${GREEN}✓${NC} QEMU running (PID $QEMU_PID)"
echo ""

# ---- Connect GDB ----
gdb -q -x "$GDB_INIT"

# ---- Cleanup ----
kill "$QEMU_PID" 2>/dev/null || true
wait "$QEMU_PID" 2>/dev/null || true
rm -f "$GDB_INIT"
echo ""
echo -e "${DIM}Debug session ended.${NC}"
