#!/usr/bin/env bash
# extract-shim-ca.sh -- generate build/generated/shim_ca.h from the
# pinned shim binary's MS UEFI CA generation.
#
# Reads `sbverify --list shim/shimx64.efi`, extracts the
# "Microsoft Corporation UEFI CA YYYY" subject, writes
# `build/generated/shim_ca.h`:
#
#   #define SHIM_CA_YEAR <year>
#
# Sentinel values:
#   0          = shim binary not pinned in-tree
#   0xFFFFFFFF = shim present but sbverify could not identify CA
#   2011|2023  = sbverify-confirmed CA year
#
# Consumed by src/kernel/uefi_runtime.c
# uefi_secureboot_populate_registry() to publish
# HKLM\SYSTEM\SecureBoot\ShimCA at boot.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHIM_BIN="${SHIM_BIN:-$REPO_ROOT/shim/shimx64.efi}"
OUT_DIR="$REPO_ROOT/build/generated"
OUT_HDR="$OUT_DIR/shim_ca.h"

mkdir -p "$OUT_DIR"

SHIM_CA_YEAR_VALUE="0u"
SHIM_CA_SOURCE="not pinned"

if [ -f "$SHIM_BIN" ]; then
    if command -v sbverify >/dev/null 2>&1; then
        # Capture sbverify rc separately from output (Codex final
        # adversarial M1 2026-04-29). Tool failure (corrupt shim,
        # unreadable file) becomes the explicit 0xFFFFFFFFu sentinel
        # rather than being silently swallowed into "no CA matched."
        SBVERIFY_RC=0
        SBVERIFY_OUT="$(sbverify --list "$SHIM_BIN" 2>&1)" || SBVERIFY_RC=$?
        if [ "$SBVERIFY_RC" -ne 0 ]; then
            SHIM_CA_YEAR_VALUE="0xFFFFFFFFu"
            SHIM_CA_SOURCE="shim present, sbverify --list exited $SBVERIFY_RC"
            echo "[shim-ca] WARN: sbverify --list failed (rc=$SBVERIFY_RC) on $SHIM_BIN; defaulting to 0xFFFFFFFFu sentinel" >&2
            printf '%s\n' "$SBVERIFY_OUT" | sed 's/^/[shim-ca]   sbverify: /' >&2
        else
            DETECTED_YEAR="$(printf '%s\n' "$SBVERIFY_OUT" \
                | grep -oE 'Microsoft Corporation UEFI CA 20[12][0-9]' \
                | grep -oE '20[12][0-9]' \
                | sort -u | tail -1 || true)"
            if [ -n "$DETECTED_YEAR" ]; then
                SHIM_CA_YEAR_VALUE="${DETECTED_YEAR}u"
                SHIM_CA_SOURCE="sbverify --list (CA $DETECTED_YEAR)"
            else
                SHIM_CA_YEAR_VALUE="0xFFFFFFFFu"
                SHIM_CA_SOURCE="shim present, sbverify could not identify CA"
            fi
        fi
    else
        SHIM_CA_YEAR_VALUE="0xFFFFFFFFu"
        SHIM_CA_SOURCE="shim present, sbverify not on PATH"
    fi
fi

SHIM_SHA="(no shim)"
if [ -f "$SHIM_BIN" ] && command -v sha256sum >/dev/null 2>&1; then
    SHIM_SHA="$(sha256sum "$SHIM_BIN" | awk '{print $1}')"
fi

# Write to a temp file and only replace the real header when content
# actually drifted (Codex perf M1 fix 2026-04-29). Mirrors the
# include/build_info.h pattern in the Makefile: preserving mtime when
# the generated content is identical avoids a needless uefi_runtime.c
# recompile + kernel relink (~321 ms) on every otherwise-clean
# incremental build, since uefi_runtime.d tracks shim_ca.h as an input.
TMP_HDR="$(mktemp "${OUT_HDR}.XXXXXX")"
trap 'rm -f "$TMP_HDR"' EXIT

cat > "$TMP_HDR" <<HDREOF
/* AUTO-GENERATED by scripts/extract-shim-ca.sh -- do NOT hand-edit.
 *
 * Microsoft Corporation UEFI CA generation that signs the bundled
 * shim binary at \`shim/shimx64.efi\`. Consumed by
 * uefi_secureboot_populate_registry() to publish
 * HKLM\\SYSTEM\\SecureBoot\\ShimCA at boot.
 *
 * Source: $SHIM_CA_SOURCE
 * Shim SHA256: $SHIM_SHA
 * Sentinels: 0u (not pinned), 0xFFFFFFFFu (parse failure), 2011u | 2023u
 *
 * See docs/guides/secure-boot-keys.md "MS UEFI CA Lifecycle".
 */
#ifndef IMPOSSIBLE_GENERATED_SHIM_CA_H
#define IMPOSSIBLE_GENERATED_SHIM_CA_H

#define SHIM_CA_YEAR $SHIM_CA_YEAR_VALUE

#endif /* IMPOSSIBLE_GENERATED_SHIM_CA_H */
HDREOF

if [ -f "$OUT_HDR" ] && cmp -s "$TMP_HDR" "$OUT_HDR"; then
    rm -f "$TMP_HDR"
    echo "[shim-ca] $OUT_HDR unchanged (SHIM_CA_YEAR=$SHIM_CA_YEAR_VALUE; $SHIM_CA_SOURCE)"
else
    mv "$TMP_HDR" "$OUT_HDR"
    echo "[shim-ca] generated $OUT_HDR (SHIM_CA_YEAR=$SHIM_CA_YEAR_VALUE; $SHIM_CA_SOURCE)"
fi
