#!/usr/bin/env bash
# extract-shim-ca.sh -- generate build/generated/shim_ca.h from the
# pinned shim binary's MS UEFI CA generation.
#
# Reads `sbverify --list shim/shimx64.efi`, extracts the
# "Microsoft Corporation UEFI CA YYYY" subject, writes
# `build/generated/shim_ca.h`:
#
#   #define SHIM_CA_YEAR <year>
#
# Sentinel values:
#   0          = shim binary not pinned in-tree
#   0xFFFFFFFF = shim present but sbverify could not identify CA
#   2011|2023  = sbverify-confirmed CA year
#
# Consumed by src/kernel/uefi_runtime.c
# uefi_secureboot_populate_registry() to publish
# HKLM\SYSTEM\SecureBoot\ShimCA at boot.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHIM_BIN="${SHIM_BIN:-$REPO_ROOT/shim/shimx64.efi}"
OUT_DIR="$REPO_ROOT/build/generated"
OUT_HDR="$OUT_DIR/shim_ca.h"

mkdir -p "$OUT_DIR"

SHIM_CA_YEAR_VALUE="0u"
SHIM_CA_SOURCE="not pinned"

if [ -f "$SHIM_BIN" ]; then
    if command -v sbverify >/dev/null 2>&1; then
        SBVERIFY_OUT="$(sbverify --list "$SHIM_BIN" 2>&1 || true)"
        DETECTED_YEAR="$(printf '%s\n' "$SBVERIFY_OUT" \
            | grep -oE 'Microsoft Corporation UEFI CA 20[12][0-9]' \
            | grep -oE '20[12][0-9]' \
            | sort -u | tail -1)"
        if [ -n "$DETECTED_YEAR" ]; then
            SHIM_CA_YEAR_VALUE="${DETECTED_YEAR}u"
            SHIM_CA_SOURCE="sbverify --list (CA $DETECTED_YEAR)"
        else
            SHIM_CA_YEAR_VALUE="0xFFFFFFFFu"
            SHIM_CA_SOURCE="shim present, sbverify could not identify CA"
        fi
    else
        SHIM_CA_YEAR_VALUE="0xFFFFFFFFu"
        SHIM_CA_SOURCE="shim present, sbverify not on PATH"
    fi
fi

SHIM_SHA="(no shim)"
if [ -f "$SHIM_BIN" ] && command -v sha256sum >/dev/null 2>&1; then
    SHIM_SHA="$(sha256sum "$SHIM_BIN" | awk '{print $1}')"
fi

cat > "$OUT_HDR" <<HDREOF
/* AUTO-GENERATED by scripts/extract-shim-ca.sh -- do NOT hand-edit.
 *
 * Microsoft Corporation UEFI CA generation that signs the bundled
 * shim binary at \`shim/shimx64.efi\`. Consumed by
 * uefi_secureboot_populate_registry() to publish
 * HKLM\\SYSTEM\\SecureBoot\\ShimCA at boot.
 *
 * Source: $SHIM_CA_SOURCE
 * Shim SHA256: $SHIM_SHA
 * Sentinels: 0u (not pinned), 0xFFFFFFFFu (parse failure), 2011u | 2023u
 *
 * See docs/guides/secure-boot-keys.md "MS UEFI CA Lifecycle".
 */
#ifndef IMPOSSIBLE_GENERATED_SHIM_CA_H
#define IMPOSSIBLE_GENERATED_SHIM_CA_H

#define SHIM_CA_YEAR $SHIM_CA_YEAR_VALUE

#endif /* IMPOSSIBLE_GENERATED_SHIM_CA_H */
HDREOF

echo "[shim-ca] generated $OUT_HDR (SHIM_CA_YEAR=$SHIM_CA_YEAR_VALUE; $SHIM_CA_SOURCE)"
