#!/usr/bin/env python3
"""Convert BSOD PNG to a C header with white BGRA pixel data.

Usage: python3 tools/convert_bsod_icon.py
Reads:  resources/system/bsod.png
Writes: src/kernel/bsod_icon.h

All non-transparent pixels are forced to white (0xFFFFFF).
Alpha channel is preserved from the original.
"""
import struct, zlib, os

# --- Minimal PNG decoder (no dependencies) ---

def read_png(path):
    """Read a PNG file and return (width, height, rgba_pixels)."""
    with open(path, 'rb') as f:
        data = f.read()

    assert data[:8] == b'\x89PNG\r\n\x1a\n', "Not a PNG file"

    pos = 8
    idat_data = b''
    width = height = 0
    bit_depth = color_type = 0

    while pos < len(data):
        length = struct.unpack('>I', data[pos:pos+4])[0]
        ctype = data[pos+4:pos+8]
        cdata = data[pos+8:pos+8+length]
        pos += 12 + length

        if ctype == b'IHDR':
            width, height, bit_depth, color_type = struct.unpack('>IIBB', cdata[:10])
        elif ctype == b'IDAT':
            idat_data += cdata
        elif ctype == b'IEND':
            break

    raw = zlib.decompress(idat_data)

    if color_type == 6:    # RGBA
        bpp = 4
    elif color_type == 2:  # RGB
        bpp = 3
    elif color_type == 0:  # Grayscale
        bpp = 1
    elif color_type == 4:  # Grayscale + Alpha
        bpp = 2
    else:
        raise ValueError(f"Unsupported color type: {color_type}")

    stride = 1 + width * bpp
    pixels = []

    prev_row = [0] * (width * bpp)
    for y in range(height):
        row_start = y * stride
        filt = raw[row_start]
        row_data = list(raw[row_start+1:row_start+stride])

        if filt == 0:
            pass
        elif filt == 1:
            for i in range(len(row_data)):
                a = row_data[i - bpp] if i >= bpp else 0
                row_data[i] = (row_data[i] + a) & 0xFF
        elif filt == 2:
            for i in range(len(row_data)):
                row_data[i] = (row_data[i] + prev_row[i]) & 0xFF
        elif filt == 3:
            for i in range(len(row_data)):
                a = row_data[i - bpp] if i >= bpp else 0
                b = prev_row[i]
                row_data[i] = (row_data[i] + (a + b) // 2) & 0xFF
        elif filt == 4:
            for i in range(len(row_data)):
                a = row_data[i - bpp] if i >= bpp else 0
                b = prev_row[i]
                c = prev_row[i - bpp] if i >= bpp else 0
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                if pa <= pb and pa <= pc:
                    pr = a
                elif pb <= pc:
                    pr = b
                else:
                    pr = c
                row_data[i] = (row_data[i] + pr) & 0xFF

        prev_row = row_data

        for x in range(width):
            off = x * bpp
            if bpp == 4:
                r, g, b_, a = row_data[off], row_data[off+1], row_data[off+2], row_data[off+3]
            elif bpp == 3:
                r, g, b_ = row_data[off], row_data[off+1], row_data[off+2]
                a = 255
            elif bpp == 2:
                # Grayscale + alpha: use luminance as alpha indicator
                gray, a = row_data[off], row_data[off+1]
                r = g = b_ = gray
            else:
                # Grayscale: use 255 - gray as alpha (black = opaque, white = transparent)
                gray = row_data[off]
                a = 255 - gray  # black pixels → fully opaque white
                r = g = b_ = 255

            pixels.append((r, g, b_, a))

    return width, height, pixels


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(script_dir)
    png_path = os.path.join(root, 'resources', 'system', 'bsod.png')
    out_path = os.path.join(root, 'src', 'kernel', 'bsod_icon.h')

    w, h, pixels = read_png(png_path)

    with open(out_path, 'w') as f:
        f.write("/* Auto-generated by tools/convert_bsod_icon.py — DO NOT EDIT */\n")
        f.write("#pragma once\n\n")
        f.write(f"#define BSOD_ICON_W {w}\n")
        f.write(f"#define BSOD_ICON_H {h}\n\n")
        f.write("/* White icon with alpha (BGRA, matches framebuffer byte order) */\n")
        f.write(f"static const uint32_t bsod_icon_pixels[{w * h}] = {{\n")

        for i, (r, g, b_, a) in enumerate(pixels):
            # Force RGB to white, keep alpha
            bgra = 0xFF | (0xFF << 8) | (0xFF << 16) | (a << 24)
            if i % 8 == 0:
                f.write("    ")
            f.write(f"0x{bgra:08X},")
            if i % 8 == 7:
                f.write("\n")
            else:
                f.write(" ")

        f.write("};\n")

    print(f"[ICON] {out_path} ({w}x{h}, {w*h*4} bytes, white)")


if __name__ == '__main__':
    main()
