#!/usr/bin/env python3
"""Convert a TTF font file to a C header with raw byte data.

Usage: python3 tools/convert_boot_font.py
Reads:  resources/fonts/selawk.ttf
Writes: src/kernel/boot_splash_font.h
"""
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(script_dir)
    ttf_path = os.path.join(root, 'resources', 'fonts', 'selawk.ttf')
    out_path = os.path.join(root, 'src', 'kernel', 'boot_splash_font.h')

    with open(ttf_path, 'rb') as f:
        data = f.read()

    with open(out_path, 'w') as f:
        f.write("/* Auto-generated by tools/convert_boot_font.py — DO NOT EDIT */\n")
        f.write("#pragma once\n\n")
        f.write(f"#define BOOT_FONT_SIZE {len(data)}\n\n")
        f.write("/* Selawik Regular TTF — embedded for boot splash text */\n")
        f.write(f"static const unsigned char boot_font_data[{len(data)}] = {{\n")

        for i, byte in enumerate(data):
            if i % 16 == 0:
                f.write("    ")
            f.write(f"0x{byte:02X},")
            if i % 16 == 15:
                f.write("\n")
            else:
                f.write(" ")

        f.write("\n};\n")

    print(f"[FONT] {out_path} ({len(data)} bytes, Selawik Regular)")

if __name__ == '__main__':
    main()
