#!/usr/bin/env python3
"""Generate per-size OS logo headers + a single data source from resources/logo/.

Usage: python3 tools/convert_icon.py
Reads:  resources/logo/os_logo_*.png
Writes: include/kernel/os_logo.h  — extern declarations + helper macros
        src/kernel/os_logo.c      — all pixel data (compiled once)
"""
import struct, zlib, os, re

# --- Minimal PNG decoder (no dependencies) ---

def read_png(path):
    """Read a PNG file and return (width, height, bgra_pixels as uint32 list)."""
    with open(path, 'rb') as f:
        data = f.read()

    assert data[:8] == b'\x89PNG\r\n\x1a\n', f"Not a PNG: {path}"

    pos = 8
    idat_data = b''
    width = height = bit_depth = color_type = 0

    while pos < len(data):
        length = struct.unpack('>I', data[pos:pos+4])[0]
        ctype = data[pos+4:pos+8]
        cdata = data[pos+8:pos+8+length]
        pos += 12 + length

        if ctype == b'IHDR':
            width, height, bit_depth, color_type = struct.unpack('>IIBB', cdata[:10])
        elif ctype == b'IDAT':
            idat_data += cdata
        elif ctype == b'IEND':
            break

    raw = zlib.decompress(idat_data)

    if color_type == 6:   bpp = 4
    elif color_type == 2: bpp = 3
    else: raise ValueError(f"Unsupported color type {color_type} in {path}")

    stride = 1 + width * bpp
    prev_row = [0] * (width * bpp)
    pixels = []

    for y in range(height):
        row_start = y * stride
        filt = raw[row_start]
        row_data = list(raw[row_start+1:row_start+stride])

        if filt == 0:
            pass
        elif filt == 1:
            for i in range(len(row_data)):
                a = row_data[i - bpp] if i >= bpp else 0
                row_data[i] = (row_data[i] + a) & 0xFF
        elif filt == 2:
            for i in range(len(row_data)):
                row_data[i] = (row_data[i] + prev_row[i]) & 0xFF
        elif filt == 3:
            for i in range(len(row_data)):
                a = row_data[i - bpp] if i >= bpp else 0
                b = prev_row[i]
                row_data[i] = (row_data[i] + (a + b) // 2) & 0xFF
        elif filt == 4:
            for i in range(len(row_data)):
                a = row_data[i - bpp] if i >= bpp else 0
                b = prev_row[i]
                c = prev_row[i - bpp] if i >= bpp else 0
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pr = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                row_data[i] = (row_data[i] + pr) & 0xFF

        prev_row = row_data

        for x in range(width):
            off = x * bpp
            r = row_data[off]
            g = row_data[off + 1]
            b = row_data[off + 2]
            a = row_data[off + 3] if bpp == 4 else 255
            # Store as BGRA uint32 (matches framebuffer byte order)
            pixels.append(b | (g << 8) | (r << 16) | (a << 24))

    return width, height, pixels


def write_pixels(f, pixels):
    """Write pixel array body (values only, no braces)."""
    for i, px in enumerate(pixels):
        if i % 8 == 0:
            f.write("    ")
        f.write(f"0x{px:08X},")
        if i % 8 == 7:
            f.write("\n")
        else:
            f.write(" ")


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(script_dir)
    logo_dir = os.path.join(root, 'resources', 'logo')
    hdr_path = os.path.join(root, 'include', 'kernel', 'os_logo.h')
    src_path = os.path.join(root, 'src', 'kernel', 'os_logo.c')

    # Find all os_logo_NNN.png files sorted by size
    pattern = re.compile(r'^os_logo_(\d+)\.png$')
    entries = []
    for fname in sorted(os.listdir(logo_dir)):
        m = pattern.match(fname)
        if m:
            size = int(m.group(1))
            entries.append((size, os.path.join(logo_dir, fname)))

    if not entries:
        raise RuntimeError(f"No os_logo_*.png files found in {logo_dir}")

    # Decode each PNG
    logos = []  # list of (size, width, height, pixels)
    for size, path in entries:
        w, h, pixels = read_png(path)
        assert w == size and h == size, \
            f"{path}: expected {size}x{size}, got {w}x{h}"
        logos.append((size, w, h, pixels))
        print(f"  [OK] os_logo_{size}.png  ({w}x{h}, {w*h*4} bytes)")

    # Write header: extern declarations only
    with open(hdr_path, 'w') as f:
        f.write("/* Auto-generated by tools/convert_icon.py — DO NOT EDIT */\n")
        f.write("#pragma once\n\n")
        f.write("/* Pre-built OS logo arrays at exact native sizes.\n")
        f.write(" * Select the right size for each use case — no runtime scaling.\n")
        f.write(" * Data defined in src/kernel/os_logo.c (compiled once). */\n\n")
        for size, w, h, pixels in logos:
            f.write(f"/* {w}x{h} BGRA logo */\n")
            f.write(f"#define OS_LOGO_{size}_W {w}\n")
            f.write(f"#define OS_LOGO_{size}_H {h}\n")
            f.write(f"extern const unsigned int os_logo_{size}_pixels[];\n\n")

        # Helper macro: pick boot splash logo based on screen height
        f.write("/* Pick the splash logo matching screen height — exact size, no scaling */\n")
        f.write("#define OS_LOGO_FOR_HEIGHT(scr_h) \\\n")
        f.write("    ((scr_h) >= 2160 ? os_logo_256_pixels : \\\n")
        f.write("                       os_logo_128_pixels)\n\n")
        f.write("#define OS_LOGO_SIZE_FOR_HEIGHT(scr_h) \\\n")
        f.write("    ((scr_h) >= 2160 ? 256 : 128)\n")

    # Write source: all pixel data
    with open(src_path, 'w') as f:
        f.write("/* Auto-generated by tools/convert_icon.py — DO NOT EDIT */\n")
        f.write("/* Use GCC built-in type — works in freestanding -nostdinc builds */\n")
        f.write("typedef __UINT32_TYPE__ uint32_t;\n\n")

        for size, w, h, pixels in logos:
            f.write(f"/* {w}x{h} OS logo — BGRA pixel data */\n")
            f.write(f"const uint32_t os_logo_{size}_pixels[{w * h}] = {{\n")
            write_pixels(f, pixels)
            f.write("};\n\n")

    total_bytes = sum(w * h * 4 for _, w, h, _ in logos)
    print(f"[ICON] {len(logos)} sizes → {hdr_path}")
    print(f"       {src_path}  ({total_bytes // 1024} KB total)")


if __name__ == '__main__':
    main()
