#!/usr/bin/env python3
"""Convert OS logo PNG to a C header with raw BGRA pixel data.

Usage: python3 tools/convert_icon.py
Reads:  resources/logo_256.png
Writes: include/kernel/os_logo.h
"""
import struct, zlib, os

# --- Minimal PNG decoder (no dependencies) ---

def read_png(path):
    """Read a PNG file and return (width, height, rgba_pixels)."""
    with open(path, 'rb') as f:
        data = f.read()

    # Validate PNG signature
    assert data[:8] == b'\x89PNG\r\n\x1a\n', "Not a PNG file"

    pos = 8
    chunks = {}
    idat_data = b''
    width = height = 0
    bit_depth = color_type = 0

    while pos < len(data):
        length = struct.unpack('>I', data[pos:pos+4])[0]
        ctype = data[pos+4:pos+8]
        cdata = data[pos+8:pos+8+length]
        pos += 12 + length

        if ctype == b'IHDR':
            width, height, bit_depth, color_type = struct.unpack('>IIBB', cdata[:10])
        elif ctype == b'IDAT':
            idat_data += cdata
        elif ctype == b'IEND':
            break

    # Decompress
    raw = zlib.decompress(idat_data)

    # Determine bytes per pixel
    if color_type == 6:   # RGBA
        bpp = 4
    elif color_type == 2: # RGB
        bpp = 3
    else:
        raise ValueError(f"Unsupported color type: {color_type}")

    stride = 1 + width * bpp  # 1 byte filter + pixel data
    pixels = []

    prev_row = [0] * (width * bpp)
    for y in range(height):
        row_start = y * stride
        filt = raw[row_start]
        row_data = list(raw[row_start+1:row_start+stride])

        # Apply PNG filter
        if filt == 0:  # None
            pass
        elif filt == 1:  # Sub
            for i in range(len(row_data)):
                a = row_data[i - bpp] if i >= bpp else 0
                row_data[i] = (row_data[i] + a) & 0xFF
        elif filt == 2:  # Up
            for i in range(len(row_data)):
                row_data[i] = (row_data[i] + prev_row[i]) & 0xFF
        elif filt == 3:  # Average
            for i in range(len(row_data)):
                a = row_data[i - bpp] if i >= bpp else 0
                b = prev_row[i]
                row_data[i] = (row_data[i] + (a + b) // 2) & 0xFF
        elif filt == 4:  # Paeth
            for i in range(len(row_data)):
                a = row_data[i - bpp] if i >= bpp else 0
                b = prev_row[i]
                c = prev_row[i - bpp] if i >= bpp else 0
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                if pa <= pb and pa <= pc:
                    pr = a
                elif pb <= pc:
                    pr = b
                else:
                    pr = c
                row_data[i] = (row_data[i] + pr) & 0xFF

        prev_row = row_data

        # Extract pixels
        for x in range(width):
            off = x * bpp
            r = row_data[off]
            g = row_data[off + 1]
            b = row_data[off + 2]
            a = row_data[off + 3] if bpp == 4 else 255
            pixels.append((r, g, b, a))

    return width, height, pixels


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(script_dir)
    png_path = os.path.join(root, 'resources', 'logo_256.png')
    hdr_path = os.path.join(root, 'include', 'kernel', 'os_logo.h')
    src_path = os.path.join(root, 'src', 'kernel', 'os_logo.c')

    w, h, pixels = read_png(png_path)

    # Write header: macros + extern declaration only (no data)
    with open(hdr_path, 'w') as f:
        f.write("/* Auto-generated by tools/convert_icon.py — DO NOT EDIT */\n")
        f.write("#pragma once\n\n")
        f.write(f"#define OS_LOGO_W {w}\n")
        f.write(f"#define OS_LOGO_H {h}\n\n")
        f.write("/* BGRA pixel data — defined in src/kernel/os_logo.c */\n")
        f.write("extern const uint32_t impossible_os_logo_pixels[];\n")

    # Write source: actual pixel data (compiled once)
    with open(src_path, 'w') as f:
        f.write("/* Auto-generated by tools/convert_icon.py — DO NOT EDIT */\n")
        f.write("/* Use GCC built-in type — works in freestanding -nostdinc builds */\n")
        f.write("typedef __UINT32_TYPE__ uint32_t;\n\n")
        f.write("/* BGRA pixel data for the Impossible OS logo (256x256) */\n")
        f.write(f"const uint32_t impossible_os_logo_pixels[{w * h}] = {{\n")

        for i, (r, g, b, a) in enumerate(pixels):
            bgra = b | (g << 8) | (r << 16) | (a << 24)
            if i % 8 == 0:
                f.write("    ")
            f.write(f"0x{bgra:08X},")
            if i % 8 == 7:
                f.write("\n")
            else:
                f.write(" ")

        f.write("};\n")

    print(f"[ICON] {hdr_path} + {src_path} ({w}x{h}, {w*h*4} bytes)")


if __name__ == '__main__':
    main()
