#!/usr/bin/env python3
"""Generate ease_lut.h — 64-entry ease-in-out lookup table.

Shape: quarter-sine wave, approximating cubic-bezier(0.42, 0, 0.58, 1).
Input:  linear phase 0–63
Output: eased value 0–255

The full ease-in-out cycle is symmetric: indices 0–63 cover 0→255.
The caller mirrors by using: ease_lut[phase < 64 ? phase : 127 - phase].

Usage:
    python3 tools/gen_ease_lut.py > src/kernel/gfx/ease_lut.h
"""

import math
import sys
import datetime

N = 64  # entries in the table

def main():
    vals = []
    for i in range(N):
        # Quarter-sine: sin(i/63 * pi/2) maps [0,63] → [0.0, 1.0]
        t = i / (N - 1)
        v = round(math.sin(t * math.pi / 2.0) * 255)
        v = max(0, min(255, v))
        vals.append(v)

    # Verify endpoints
    assert vals[0] == 0,   f"ease[0] should be 0, got {vals[0]}"
    assert vals[63] == 255, f"ease[63] should be 255, got {vals[63]}"

    ts = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    print(f"/* ease_lut.h — Auto-generated by tools/gen_ease_lut.py ({ts})")
    print(f" *")
    print(f" * 64-entry ease-in-out curve (quarter-sine).")
    print(f" * Index 0..63 maps to eased value 0..255.")
    print(f" * For full ease-in-out: ease_lut[phase < 64 ? phase : 127 - phase]")
    print(f" *")
    print(f" * DO NOT EDIT — regenerate with: python3 tools/gen_ease_lut.py")
    print(f" */")
    print()
    print("#pragma once")
    print()
    print('#include "kernel/types.h"')
    print()

    print(f"static const uint8_t ease_lut[{N}] = {{")
    for row in range(N // 8):
        start = row * 8
        line = ", ".join(f"{vals[start + j]:3d}" for j in range(8))
        comma = "," if row < (N // 8 - 1) else ""
        idx_comment = f"/* {start:2d}..{start+7:2d} */"
        print(f"    {line}{comma}  {idx_comment}")
    print("};")
    print()

    return 0

if __name__ == "__main__":
    sys.exit(main())
