#!/bin/bash
# gen_icon_map.sh — Parse Fluent UI CSS and generate C codepoint header
#
# Input:  resources/icons/FluentSystemIcons-Filled.css
# Output: include/generated/fluent_codepoints.h
#
# Run whenever the Fluent CSS files are updated:
#   bash tools/gen_icon_map.sh

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CSS_FILE="$ROOT_DIR/resources/icons/FluentSystemIcons-Filled.css"
OUT_DIR="$ROOT_DIR/include/generated"
OUT_FILE="$OUT_DIR/fluent_codepoints.h"

mkdir -p "$OUT_DIR"

[ -f "$CSS_FILE" ] || { echo "ERROR: $CSS_FILE not found"; exit 1; }

# Extract hex codepoint for a given icon name
get_cp() {
    grep -A1 "ic_fluent_${1}_filled" "$CSS_FILE" \
        | grep 'content:' \
        | awk -F'"' '{print $2}' \
        | tr -d '\\' \
        | head -1
}

# ---- Write header preamble ----
cat > "$OUT_FILE" << 'EOF'
/* ============================================================================
 * fluent_codepoints.h — AUTO-GENERATED by tools/gen_icon_map.sh
 * Source: resources/icons/FluentSystemIcons-Filled.css
 * DO NOT EDIT — regenerate with: bash tools/gen_icon_map.sh
 * ============================================================================ */

#pragma once

#include "icon_store.h"

/* ---- Curated enum → codepoint (O(1) by array index) ---- */

static const uint32_t icon_codepoints[ICON_MONO_COUNT] = {
EOF

# ---- Curated mapping (enum order) ----
declare -a ICONS=(
    "cut_20|ICON_CUT"
    "copy_20|ICON_COPY"
    "clipboard_paste_20|ICON_PASTE"
    "arrow_undo_20|ICON_UNDO"
    "arrow_redo_20|ICON_REDO"
    "save_20|ICON_SAVE"
    "folder_open_20|ICON_OPEN"
    "document_add_20|ICON_NEW"
    "delete_20|ICON_DELETE"
    "arrow_clockwise_20|ICON_REFRESH"
    "zoom_in_20|ICON_ZOOM_IN"
    "zoom_out_20|ICON_ZOOM_OUT"
    "text_bold_20|ICON_BOLD"
    "text_italic_20|ICON_ITALIC"
    "text_underline_20|ICON_UNDERLINE"
    "text_align_left_20|ICON_ALIGN_LEFT"
    "text_align_center_20|ICON_ALIGN_CENTER"
    "text_align_right_20|ICON_ALIGN_RIGHT"
    "print_20|ICON_PRINT"
    "home_20|ICON_HOME"
    "arrow_left_20|ICON_BACK"
    "arrow_right_20|ICON_FORWARD"
    "arrow_up_20|ICON_UP"
    "settings_20|ICON_SETTINGS"
    "search_20|ICON_SEARCH"
    "lock_closed_20|ICON_LOCK"
    "person_20|ICON_USER"
    "power_20|ICON_POWER"
    "info_20|ICON_INFO"
    "warning_20|ICON_WARNING"
    "error_circle_20|ICON_ERROR"
    "question_circle_20|ICON_QUESTION"
    "dismiss_20|ICON_CLOSE"
    "arrow_minimize_20|ICON_MINIMIZE"
    "arrow_maximize_20|ICON_MAXIMIZE"
    "square_20|ICON_RESTORE"
    "navigation_20|ICON_MENU"
    "chevron_down_20|ICON_CHEVRON_DOWN"
    "chevron_right_20|ICON_CHEVRON_RIGHT"
    "chevron_left_20|ICON_CHEVRON_LEFT"
    "chevron_up_20|ICON_CHEVRON_UP"
    "checkmark_20|ICON_CHECK"
    "add_20|ICON_ADD"
    "subtract_20|ICON_SUBTRACT"
    "star_20|ICON_STAR"
    "heart_20|ICON_HEART"
    "share_20|ICON_SHARE"
    "arrow_download_20|ICON_DOWNLOAD"
    "arrow_upload_20|ICON_UPLOAD"
    "clock_20|ICON_CLOCK"
    "calendar_20|ICON_CALENDAR"
    "arrow_sort_20|ICON_SORT"
    "filter_20|ICON_FILTER"
    "grid_20|ICON_GRID"
    "list_20|ICON_LIST"
    "link_20|ICON_LINK"
    "attach_20|ICON_ATTACH"
    "pin_20|ICON_PIN"
    "clipboard_20|ICON_CLIPBOARD"
    "full_screen_maximize_20|ICON_FULLSCREEN"
)

CURATED=0
for entry in "${ICONS[@]}"; do
    IFS='|' read -r css_name enum_name <<< "$entry"
    cp=$(get_cp "$css_name")
    if [ -z "$cp" ]; then
        echo "    0x0000,  /* $enum_name — NOT FOUND */" >> "$OUT_FILE"
    else
        echo "    0x${cp},  /* $enum_name */" >> "$OUT_FILE"
        CURATED=$((CURATED + 1))
    fi
done

echo "};" >> "$OUT_FILE"

# ---- Full lookup table (ALL Fluent icons, sorted for binary search) ----

echo "" >> "$OUT_FILE"
echo "typedef struct fluent_icon_entry {" >> "$OUT_FILE"
echo "    const char *name;" >> "$OUT_FILE"
echo "    uint32_t    codepoint;" >> "$OUT_FILE"
echo "} fluent_icon_entry_t;" >> "$OUT_FILE"
echo "" >> "$OUT_FILE"

# Extract all name→codepoint pairs
TMP="/tmp/fluent_gen_$$"
> "$TMP"

current_name=""
while IFS= read -r line; do
    case "$line" in
        *ic_fluent_*_filled:before*)
            current_name=$(echo "$line" | awk -F'ic_fluent_' '{print $2}' | awk -F'_filled' '{print $1}')
            ;;
        *content:*)
            if [ -n "$current_name" ]; then
                cp=$(echo "$line" | awk -F'"' '{print $2}' | tr -d '\\')
                [ -n "$cp" ] && echo "${current_name}|${cp}" >> "$TMP"
                current_name=""
            fi
            ;;
    esac
done < "$CSS_FILE"

TOTAL=$(wc -l < "$TMP")
sort -t'|' -k1,1 "$TMP" > "${TMP}.sorted"

echo "#define FLUENT_ICON_COUNT $TOTAL" >> "$OUT_FILE"
echo "" >> "$OUT_FILE"
echo "/* Sorted by name for O(log n) binary search */" >> "$OUT_FILE"
echo "static const fluent_icon_entry_t fluent_all_icons[FLUENT_ICON_COUNT] = {" >> "$OUT_FILE"

while IFS='|' read -r name cp; do
    echo "    { \"$name\", 0x${cp} }," >> "$OUT_FILE"
done < "${TMP}.sorted"

echo "};" >> "$OUT_FILE"

# ---- Binary search function ----
cat >> "$OUT_FILE" << 'BSEARCH'

/* O(log n) lookup for any Fluent icon by name. Returns codepoint or 0. */
static uint32_t fluent_lookup(const char *name)
{
    int lo = 0, hi = FLUENT_ICON_COUNT - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        const char *a = name;
        const char *b = fluent_all_icons[mid].name;
        while (*a && *a == *b) { a++; b++; }
        int cmp = (int)(*(const unsigned char *)a) -
                  (int)(*(const unsigned char *)b);
        if (cmp == 0) return fluent_all_icons[mid].codepoint;
        if (cmp < 0) hi = mid - 1;
        else         lo = mid + 1;
    }
    return 0;
}
BSEARCH

rm -f "$TMP" "${TMP}.sorted"

LINES=$(wc -l < "$OUT_FILE")
echo "[OK] Generated $OUT_FILE ($LINES lines, $CURATED curated + $TOTAL total icons)"
