#!/usr/bin/env python3
"""Generate arc_lut.h — 256-entry sin/cos lookup table (fixed-point 8.8).

Each entry is sin(angle) * 256 or cos(angle) * 256, where angle steps
through 0°..360° in 256 evenly spaced steps (1.40625° each).

Values range from -256 to +256 (int16_t).

Usage:
    python3 tools/gen_arc_lut.py > src/kernel/gfx/arc_lut.h
"""

import math
import sys
import datetime

N = 256  # number of steps around the circle

def gen_table(name, func):
    """Generate a single LUT array."""
    vals = []
    for i in range(N):
        angle = 2.0 * math.pi * i / N
        v = round(func(angle) * 256)
        # Clamp to int16 range (should naturally be -256..+256)
        v = max(-32768, min(32767, v))
        vals.append(v)
    return vals

def main():
    sin_vals = gen_table("arc_sin_lut", math.sin)
    cos_vals = gen_table("arc_cos_lut", math.cos)

    # Verify key values
    assert sin_vals[0] == 0,     f"sin[0] should be 0, got {sin_vals[0]}"
    assert sin_vals[64] == 256,  f"sin[64] should be 256, got {sin_vals[64]}"
    assert sin_vals[128] == 0,   f"sin[128] should be 0, got {sin_vals[128]}"
    assert cos_vals[0] == 256,   f"cos[0] should be 256, got {cos_vals[0]}"
    assert cos_vals[64] == 0,    f"cos[64] should be 0, got {cos_vals[64]}"

    ts = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    print(f"/* arc_lut.h — Auto-generated by tools/gen_arc_lut.py ({ts})")
    print(f" *")
    print(f" * 256-entry sin/cos lookup table, fixed-point 8.8.")
    print(f" * Index 0..255 maps to angle 0°..358.59° (step = 1.40625°).")
    print(f" * Values: sin(angle)*256 and cos(angle)*256 → range [-256, +256].")
    print(f" *")
    print(f" * DO NOT EDIT — regenerate with: python3 tools/gen_arc_lut.py")
    print(f" */")
    print()
    print("#pragma once")
    print()
    print('#include "kernel/types.h"')
    print()

    # Print sin table
    print(f"static const int16_t arc_sin_lut[{N}] = {{")
    for row in range(N // 8):
        start = row * 8
        line = ", ".join(f"{sin_vals[start + j]:4d}" for j in range(8))
        comma = "," if row < (N // 8 - 1) else ""
        idx_comment = f"/* {start:3d}..{start+7:3d} */"
        print(f"    {line}{comma}  {idx_comment}")
    print("};")
    print()

    # Print cos table
    print(f"static const int16_t arc_cos_lut[{N}] = {{")
    for row in range(N // 8):
        start = row * 8
        line = ", ".join(f"{cos_vals[start + j]:4d}" for j in range(8))
        comma = "," if row < (N // 8 - 1) else ""
        idx_comment = f"/* {start:3d}..{start+7:3d} */"
        print(f"    {line}{comma}  {idx_comment}")
    print("};")
    print()

    return 0

if __name__ == "__main__":
    sys.exit(main())
