/* Auto-generated by tools/convert_icon.py — DO NOT EDIT */
#pragma once

#define OS_LOGO_W 256
#define OS_LOGO_H 256

/* BGRA pixel data — defined in src/kernel/os_logo.c */
extern const uint32_t impossible_os_logo_pixels[];
