/* Auto-generated by tools/convert_icon.py — DO NOT EDIT */
#pragma once

/* Pre-built OS logo arrays at exact native sizes.
 * Select the right size for each use case — no runtime scaling.
 * Data defined in src/kernel/os_logo.c (compiled once). */

/* 128x128 BGRA logo */
#define OS_LOGO_128_W 128
#define OS_LOGO_128_H 128
extern const unsigned int os_logo_128_pixels[];

/* 16x16 BGRA logo */
#define OS_LOGO_16_W 16
#define OS_LOGO_16_H 16
extern const unsigned int os_logo_16_pixels[];

/* 192x192 BGRA logo */
#define OS_LOGO_192_W 192
#define OS_LOGO_192_H 192
extern const unsigned int os_logo_192_pixels[];

/* 20x20 BGRA logo */
#define OS_LOGO_20_W 20
#define OS_LOGO_20_H 20
extern const unsigned int os_logo_20_pixels[];

/* 24x24 BGRA logo */
#define OS_LOGO_24_W 24
#define OS_LOGO_24_H 24
extern const unsigned int os_logo_24_pixels[];

/* 256x256 BGRA logo */
#define OS_LOGO_256_W 256
#define OS_LOGO_256_H 256
extern const unsigned int os_logo_256_pixels[];

/* 32x32 BGRA logo */
#define OS_LOGO_32_W 32
#define OS_LOGO_32_H 32
extern const unsigned int os_logo_32_pixels[];

/* 40x40 BGRA logo */
#define OS_LOGO_40_W 40
#define OS_LOGO_40_H 40
extern const unsigned int os_logo_40_pixels[];

/* 48x48 BGRA logo */
#define OS_LOGO_48_W 48
#define OS_LOGO_48_H 48
extern const unsigned int os_logo_48_pixels[];

/* 64x64 BGRA logo */
#define OS_LOGO_64_W 64
#define OS_LOGO_64_H 64
extern const unsigned int os_logo_64_pixels[];

/* 72x72 BGRA logo */
#define OS_LOGO_72_W 72
#define OS_LOGO_72_H 72
extern const unsigned int os_logo_72_pixels[];

/* 80x80 BGRA logo */
#define OS_LOGO_80_W 80
#define OS_LOGO_80_H 80
extern const unsigned int os_logo_80_pixels[];

/* 96x96 BGRA logo */
#define OS_LOGO_96_W 96
#define OS_LOGO_96_H 96
extern const unsigned int os_logo_96_pixels[];

/* Pick the splash logo matching screen height — exact size, no scaling */
#define OS_LOGO_FOR_HEIGHT(scr_h) \
    ((scr_h) >= 2160 ? os_logo_256_pixels : \
     (scr_h) >= 1440 ? os_logo_192_pixels : \
                       os_logo_128_pixels)

#define OS_LOGO_SIZE_FOR_HEIGHT(scr_h) \
    ((scr_h) >= 2160 ? 256 : \
     (scr_h) >= 1440 ? 192 : \
                       128)
