/* Auto-generated by tools/convert_icon.py — DO NOT EDIT */
#pragma once

/* Pre-built OS logo arrays at exact native sizes.
 * Select the right size for each use case — no runtime scaling.
 * Data defined in src/kernel/os_logo.c (compiled once). */

/* 128x128 BGRA logo */
#define OS_LOGO_128_W 128
#define OS_LOGO_128_H 128
extern const unsigned int os_logo_128_pixels[];

/* 16x16 BGRA logo */
#define OS_LOGO_16_W 16
#define OS_LOGO_16_H 16
extern const unsigned int os_logo_16_pixels[];

/* 24x24 BGRA logo */
#define OS_LOGO_24_W 24
#define OS_LOGO_24_H 24
extern const unsigned int os_logo_24_pixels[];

/* 256x256 BGRA logo */
#define OS_LOGO_256_W 256
#define OS_LOGO_256_H 256
extern const unsigned int os_logo_256_pixels[];

/* 32x32 BGRA logo */
#define OS_LOGO_32_W 32
#define OS_LOGO_32_H 32
extern const unsigned int os_logo_32_pixels[];

/* 48x48 BGRA logo */
#define OS_LOGO_48_W 48
#define OS_LOGO_48_H 48
extern const unsigned int os_logo_48_pixels[];

/* 64x64 BGRA logo */
#define OS_LOGO_64_W 64
#define OS_LOGO_64_H 64
extern const unsigned int os_logo_64_pixels[];

/* Pick the splash logo matching screen height — exact size, no scaling */
#define OS_LOGO_FOR_HEIGHT(scr_h) \
    ((scr_h) >= 2160 ? os_logo_256_pixels : \
                       os_logo_128_pixels)

#define OS_LOGO_SIZE_FOR_HEIGHT(scr_h) \
    ((scr_h) >= 2160 ? 256 : 128)
