/* ============================================================================
 * symtab.h — Kernel symbol table for address→name resolution
 *
 * Provides symbolic stack traces in panics/BSODs.
 * The symbol table is loaded at boot from C:\Impossible\System\kernel.sym
 * (generated by tools/convert_symmap.py during the build).
 *
 * Usage:
 *   symtab_init();  // Call after VFS is ready
 *   const char *name = symtab_resolve(0xFFFF800000012345, &offset);
 *   // name = "kernel_main", offset = 0x42
 * ============================================================================ */

#pragma once

#include "kernel/types.h"

/* Initialize: load kernel.sym from the boot filesystem */
void symtab_init(void);

/* Resolve an address to a symbol name.
 * Returns the symbol name, or NULL if not found.
 * If offset is non-NULL, sets it to the byte offset from the symbol start. */
const char *symtab_resolve(uint64_t addr, uint64_t *offset);

/* Return the number of loaded symbols (0 if not loaded) */
uint32_t symtab_count(void);
