/* GENERATED from docs/design/tokens.json by scripts/site/gen_theme_header.py.
 * Do not edit: change the tokens, then run
 *   python3 scripts/site/gen_theme_header.py
 * scripts/site/build.py --check (lint Check 30) fails if this file drifts.
 * Colours are 0xAARRGGBB; sizes are pixels at 100% scale. */
#ifndef DESKTOP_THEME_TOKENS_H
#define DESKTOP_THEME_TOKENS_H

/* ---- colour: dark ---- */
#define THEME_DARK_ACCENT                            0xFF60CDFFu
#define THEME_DARK_ACCENT_HOVER                      0xFF5AB9E6u
#define THEME_DARK_ACCENT_PRESSED                    0xFF4FA3CCu
#define THEME_DARK_BADGE_FILL                        0xFF60CDFFu
#define THEME_DARK_CAPTION_CLOSE_HOVER               0xFFC42B1Cu
#define THEME_DARK_CAPTION_CLOSE_PRESSED             0xFFC83C31u
#define THEME_DARK_CARD_BG                           0x0DFFFFFFu
#define THEME_DARK_CONTROL_FILL                      0x0FFFFFFFu
#define THEME_DARK_CONTROL_FILL_DISABLED             0x0BFFFFFFu
#define THEME_DARK_CONTROL_FILL_HOVER                0x15FFFFFFu
#define THEME_DARK_CONTROL_FILL_INPUT_ACTIVE         0xB31E1E1Eu
#define THEME_DARK_CONTROL_FILL_PRESSED              0x08FFFFFFu
#define THEME_DARK_CONTROL_STRONG_STROKE             0x8BFFFFFFu
#define THEME_DARK_CONTROL_UNDERLINE                 0x8AFFFFFFu
#define THEME_DARK_DESKTOP_LABEL                     0xFFFFFFFFu
#define THEME_DARK_DESKTOP_LABEL_SHADOW              0x99000000u
#define THEME_DARK_FOCUS_INNER                       0xB3000000u
#define THEME_DARK_FOCUS_OUTER                       0xFFFFFFFFu
#define THEME_DARK_LAYER_BG                          0x4D3A3A3Au
#define THEME_DARK_NOTE_BLUE                         0xFFE2F1FFu
#define THEME_DARK_NOTE_CHARCOAL                     0xFF696969u
#define THEME_DARK_NOTE_GRAY                         0xFFF3F2F1u
#define THEME_DARK_NOTE_GREEN                        0xFFE4F9E0u
#define THEME_DARK_NOTE_PINK                         0xFFFFE4F1u
#define THEME_DARK_NOTE_PURPLE                       0xFFF2E6FFu
#define THEME_DARK_NOTE_YELLOW                       0xFFFFF7D1u
#define THEME_DARK_SELECTION_FILL                    0x3360CDFFu
#define THEME_DARK_SELECTION_STROKE                  0x9960CDFFu
#define THEME_DARK_SMOKE                             0x4D000000u
#define THEME_DARK_STATUS_CAUTION                    0xFFFCE100u
#define THEME_DARK_STATUS_CAUTION_BG                 0xFF433519u
#define THEME_DARK_STATUS_CRITICAL                   0xFFFF99A4u
#define THEME_DARK_STATUS_CRITICAL_BG                0xFF442726u
#define THEME_DARK_STATUS_INFO                       0xFF60CDFFu
#define THEME_DARK_STATUS_SUCCESS                    0xFF6CCB5Fu
#define THEME_DARK_STATUS_SUCCESS_BG                 0xFF393D1Bu
#define THEME_DARK_STROKE_CARD                       0x19000000u
#define THEME_DARK_STROKE_CONTROL                    0x12FFFFFFu
#define THEME_DARK_STROKE_DIVIDER                    0x15FFFFFFu
#define THEME_DARK_STROKE_SURFACE                    0x66757575u
#define THEME_DARK_SUBTLE_FILL_HOVER                 0x0FFFFFFFu
#define THEME_DARK_SUBTLE_FILL_PRESSED               0x0AFFFFFFu
#define THEME_DARK_TASKBAR_ATTENTION_FILL            0xFF433519u
#define THEME_DARK_TASKBAR_ATTENTION_INDICATOR       0xFFFCE100u
#define THEME_DARK_TASKBAR_INDICATOR                 0xFF60CDFFu
#define THEME_DARK_TASKBAR_INDICATOR_IDLE            0xFF9A9A9Au
#define THEME_DARK_TERMINAL_BG                       0xFF0C0C0Cu
#define THEME_DARK_TERMINAL_BLACK                    0xFF0C0C0Cu
#define THEME_DARK_TERMINAL_BLUE                     0xFF0037DAu
#define THEME_DARK_TERMINAL_BRIGHT_BLACK             0xFF767676u
#define THEME_DARK_TERMINAL_BRIGHT_BLUE              0xFF3B78FFu
#define THEME_DARK_TERMINAL_BRIGHT_CYAN              0xFF61D6D6u
#define THEME_DARK_TERMINAL_BRIGHT_GREEN             0xFF16C60Cu
#define THEME_DARK_TERMINAL_BRIGHT_PURPLE            0xFFB4009Eu
#define THEME_DARK_TERMINAL_BRIGHT_RED               0xFFE74856u
#define THEME_DARK_TERMINAL_BRIGHT_WHITE             0xFFF2F2F2u
#define THEME_DARK_TERMINAL_BRIGHT_YELLOW            0xFFF9F1A5u
#define THEME_DARK_TERMINAL_CURSOR                   0xFFFFFFFFu
#define THEME_DARK_TERMINAL_CYAN                     0xFF3A96DDu
#define THEME_DARK_TERMINAL_FG                       0xFFCCCCCCu
#define THEME_DARK_TERMINAL_GREEN                    0xFF13A10Eu
#define THEME_DARK_TERMINAL_PURPLE                   0xFF881798u
#define THEME_DARK_TERMINAL_RED                      0xFFC50F1Fu
#define THEME_DARK_TERMINAL_SELECTION                0x66FFFFFFu
#define THEME_DARK_TERMINAL_WHITE                    0xFFCCCCCCu
#define THEME_DARK_TERMINAL_YELLOW                   0xFFC19C00u
#define THEME_DARK_TEXT_DISABLED                     0xFF5D5D5Du
#define THEME_DARK_TEXT_ON_ACCENT                    0xFF000000u
#define THEME_DARK_TEXT_PRIMARY                      0xFFFFFFFFu
#define THEME_DARK_TEXT_SECONDARY                    0xFFC5C5C5u
#define THEME_DARK_TEXT_TERTIARY                     0xFF9A9A9Au
#define THEME_DARK_TOGGLE_KNOB_OFF                   0xFFC5C5C5u
#define THEME_DARK_WINDOW_BG                         0xFF202020u
#define THEME_DARK_WINDOW_BG_INACTIVE                0xFF2B2B2Bu

/* ---- colour: light ---- */
#define THEME_LIGHT_ACCENT                           0xFF005FB8u
#define THEME_LIGHT_ACCENT_HOVER                     0xFF196EBFu
#define THEME_LIGHT_ACCENT_PRESSED                   0xFF317DC6u
#define THEME_LIGHT_BADGE_FILL                       0xFF005FB8u
#define THEME_LIGHT_CAPTION_CLOSE_HOVER              0xFFC42B1Cu
#define THEME_LIGHT_CAPTION_CLOSE_PRESSED            0xFFC83C31u
#define THEME_LIGHT_CARD_BG                          0xB3FFFFFFu
#define THEME_LIGHT_CONTROL_FILL                     0xB3FFFFFFu
#define THEME_LIGHT_CONTROL_FILL_DISABLED            0x4DF9F9F9u
#define THEME_LIGHT_CONTROL_FILL_HOVER               0x80F9F9F9u
#define THEME_LIGHT_CONTROL_FILL_INPUT_ACTIVE        0xFFFFFFFFu
#define THEME_LIGHT_CONTROL_FILL_PRESSED             0x4DF9F9F9u
#define THEME_LIGHT_CONTROL_STRONG_STROKE            0x72000000u
#define THEME_LIGHT_CONTROL_UNDERLINE                0x72000000u
#define THEME_LIGHT_DESKTOP_LABEL                    0xFFFFFFFFu
#define THEME_LIGHT_DESKTOP_LABEL_SHADOW             0x99000000u
#define THEME_LIGHT_FOCUS_INNER                      0xFFFFFFFFu
#define THEME_LIGHT_FOCUS_OUTER                      0xE4000000u
#define THEME_LIGHT_LAYER_BG                         0x80FFFFFFu
#define THEME_LIGHT_NOTE_BLUE                        0xFFE2F1FFu
#define THEME_LIGHT_NOTE_CHARCOAL                    0xFF696969u
#define THEME_LIGHT_NOTE_GRAY                        0xFFF3F2F1u
#define THEME_LIGHT_NOTE_GREEN                       0xFFE4F9E0u
#define THEME_LIGHT_NOTE_PINK                        0xFFFFE4F1u
#define THEME_LIGHT_NOTE_PURPLE                      0xFFF2E6FFu
#define THEME_LIGHT_NOTE_YELLOW                      0xFFFFF7D1u
#define THEME_LIGHT_SELECTION_FILL                   0x33005FB8u
#define THEME_LIGHT_SELECTION_STROKE                 0x99005FB8u
#define THEME_LIGHT_SMOKE                            0x4D000000u
#define THEME_LIGHT_STATUS_CAUTION                   0xFF9D5D00u
#define THEME_LIGHT_STATUS_CAUTION_BG                0xFFFFF4CEu
#define THEME_LIGHT_STATUS_CRITICAL                  0xFFC42B1Cu
#define THEME_LIGHT_STATUS_CRITICAL_BG               0xFFFDE7E9u
#define THEME_LIGHT_STATUS_INFO                      0xFF005FB8u
#define THEME_LIGHT_STATUS_SUCCESS                   0xFF0F7B0Fu
#define THEME_LIGHT_STATUS_SUCCESS_BG                0xFFDFF6DDu
#define THEME_LIGHT_STROKE_CARD                      0x0F000000u
#define THEME_LIGHT_STROKE_CONTROL                   0x0F000000u
#define THEME_LIGHT_STROKE_DIVIDER                   0x0F000000u
#define THEME_LIGHT_STROKE_SURFACE                   0x66757575u
#define THEME_LIGHT_SUBTLE_FILL_HOVER                0x09000000u
#define THEME_LIGHT_SUBTLE_FILL_PRESSED              0x06000000u
#define THEME_LIGHT_TASKBAR_ATTENTION_FILL           0xFFFFF4CEu
#define THEME_LIGHT_TASKBAR_ATTENTION_INDICATOR      0xFF9D5D00u
#define THEME_LIGHT_TASKBAR_INDICATOR                0xFF005FB8u
#define THEME_LIGHT_TASKBAR_INDICATOR_IDLE           0xFF8A8A8Au
#define THEME_LIGHT_TERMINAL_BG                      0xFF0C0C0Cu
#define THEME_LIGHT_TERMINAL_BLACK                   0xFF0C0C0Cu
#define THEME_LIGHT_TERMINAL_BLUE                    0xFF0037DAu
#define THEME_LIGHT_TERMINAL_BRIGHT_BLACK            0xFF767676u
#define THEME_LIGHT_TERMINAL_BRIGHT_BLUE             0xFF3B78FFu
#define THEME_LIGHT_TERMINAL_BRIGHT_CYAN             0xFF61D6D6u
#define THEME_LIGHT_TERMINAL_BRIGHT_GREEN            0xFF16C60Cu
#define THEME_LIGHT_TERMINAL_BRIGHT_PURPLE           0xFFB4009Eu
#define THEME_LIGHT_TERMINAL_BRIGHT_RED              0xFFE74856u
#define THEME_LIGHT_TERMINAL_BRIGHT_WHITE            0xFFF2F2F2u
#define THEME_LIGHT_TERMINAL_BRIGHT_YELLOW           0xFFF9F1A5u
#define THEME_LIGHT_TERMINAL_CURSOR                  0xFFFFFFFFu
#define THEME_LIGHT_TERMINAL_CYAN                    0xFF3A96DDu
#define THEME_LIGHT_TERMINAL_FG                      0xFFCCCCCCu
#define THEME_LIGHT_TERMINAL_GREEN                   0xFF13A10Eu
#define THEME_LIGHT_TERMINAL_PURPLE                  0xFF881798u
#define THEME_LIGHT_TERMINAL_RED                     0xFFC50F1Fu
#define THEME_LIGHT_TERMINAL_SELECTION               0x66FFFFFFu
#define THEME_LIGHT_TERMINAL_WHITE                   0xFFCCCCCCu
#define THEME_LIGHT_TERMINAL_YELLOW                  0xFFC19C00u
#define THEME_LIGHT_TEXT_DISABLED                    0xFFA0A0A0u
#define THEME_LIGHT_TEXT_ON_ACCENT                   0xFFFFFFFFu
#define THEME_LIGHT_TEXT_PRIMARY                     0xFF1B1B1Bu
#define THEME_LIGHT_TEXT_SECONDARY                   0xFF5D5D5Du
#define THEME_LIGHT_TEXT_TERTIARY                    0xFF8A8A8Au
#define THEME_LIGHT_TOGGLE_KNOB_OFF                  0xFF5D5D5Du
#define THEME_LIGHT_WINDOW_BG                        0xFFF3F3F3u
#define THEME_LIGHT_WINDOW_BG_INACTIVE               0xFFEBEBEBu

/* ---- material: dark ---- */
#define THEME_MAT_DARK_FLYOUT_BLUR                   30
#define THEME_MAT_DARK_FLYOUT_LUMINOSITY_OPACITY     170
#define THEME_MAT_DARK_FLYOUT_NOISE                  6
#define THEME_MAT_DARK_FLYOUT_TINT                   0xFF2C2C2Cu
#define THEME_MAT_DARK_FLYOUT_TINT_OPACITY           204
#define THEME_MAT_DARK_MENU_BLUR                     20
#define THEME_MAT_DARK_MENU_LUMINOSITY_OPACITY       180
#define THEME_MAT_DARK_MENU_NOISE                    4
#define THEME_MAT_DARK_MENU_TINT                     0xFF2C2C2Cu
#define THEME_MAT_DARK_MENU_TINT_OPACITY             214
#define THEME_MAT_DARK_MICA_DESATURATE               40
#define THEME_MAT_DARK_MICA_TINT                     0xFF202020u
#define THEME_MAT_DARK_MICA_TINT_OPACITY             204
#define THEME_MAT_DARK_START_BLUR                    30
#define THEME_MAT_DARK_START_LUMINOSITY_OPACITY      160
#define THEME_MAT_DARK_START_NOISE                   6
#define THEME_MAT_DARK_START_TINT                    0xFF202020u
#define THEME_MAT_DARK_START_TINT_OPACITY            196
#define THEME_MAT_DARK_TASKBAR_BLUR                  24
#define THEME_MAT_DARK_TASKBAR_LUMINOSITY_OPACITY    150
#define THEME_MAT_DARK_TASKBAR_NOISE                 6
#define THEME_MAT_DARK_TASKBAR_TINT                  0xFF1C1C1Cu
#define THEME_MAT_DARK_TASKBAR_TINT_OPACITY          184

/* ---- material: light ---- */
#define THEME_MAT_LIGHT_FLYOUT_BLUR                  30
#define THEME_MAT_LIGHT_FLYOUT_LUMINOSITY_OPACITY    170
#define THEME_MAT_LIGHT_FLYOUT_NOISE                 6
#define THEME_MAT_LIGHT_FLYOUT_TINT                  0xFFFCFCFCu
#define THEME_MAT_LIGHT_FLYOUT_TINT_OPACITY          196
#define THEME_MAT_LIGHT_MENU_BLUR                    20
#define THEME_MAT_LIGHT_MENU_LUMINOSITY_OPACITY      180
#define THEME_MAT_LIGHT_MENU_NOISE                   4
#define THEME_MAT_LIGHT_MENU_TINT                    0xFFFCFCFCu
#define THEME_MAT_LIGHT_MENU_TINT_OPACITY            214
#define THEME_MAT_LIGHT_MICA_DESATURATE              40
#define THEME_MAT_LIGHT_MICA_TINT                    0xFFF3F3F3u
#define THEME_MAT_LIGHT_MICA_TINT_OPACITY            204
#define THEME_MAT_LIGHT_START_BLUR                   30
#define THEME_MAT_LIGHT_START_LUMINOSITY_OPACITY     160
#define THEME_MAT_LIGHT_START_NOISE                  6
#define THEME_MAT_LIGHT_START_TINT                   0xFFF3F3F3u
#define THEME_MAT_LIGHT_START_TINT_OPACITY           190
#define THEME_MAT_LIGHT_TASKBAR_BLUR                 24
#define THEME_MAT_LIGHT_TASKBAR_LUMINOSITY_OPACITY   150
#define THEME_MAT_LIGHT_TASKBAR_NOISE                6
#define THEME_MAT_LIGHT_TASKBAR_TINT                 0xFFEEEEEEu
#define THEME_MAT_LIGHT_TASKBAR_TINT_OPACITY         176

/* ---- size ---- */
#define THEME_SIZE_ALT_TAB_THUMB_HEIGHT              158
#define THEME_SIZE_APP_INSTALLER_HEIGHT              480
#define THEME_SIZE_APP_INSTALLER_WIDTH               640
#define THEME_SIZE_BADGE_HEIGHT                      16
#define THEME_SIZE_BADGE_MIN_WIDTH                   16
#define THEME_SIZE_BOOT_LOGO                         128
#define THEME_SIZE_BOOT_PROGRESS_WIDTH               240
#define THEME_SIZE_BOOT_SPINNER                      40
#define THEME_SIZE_CAPTION_BUTTON_WIDTH              46
#define THEME_SIZE_CAPTION_GLYPH                     10
#define THEME_SIZE_CAPTION_HEIGHT                    32
#define THEME_SIZE_CHECK_BOX                         20
#define THEME_SIZE_CLIPBOARD_MAX_HEIGHT              480
#define THEME_SIZE_CLIPBOARD_WIDTH                   360
#define THEME_SIZE_COMMAND_BAR_HEIGHT                48
#define THEME_SIZE_CONTEXT_MENU_ICON_ROW_HEIGHT      40
#define THEME_SIZE_CONTEXT_MENU_ITEM_HEIGHT          32
#define THEME_SIZE_CONTEXT_MENU_WIDTH                256
#define THEME_SIZE_CONTROL_GLYPH                     16
#define THEME_SIZE_CONTROL_HEIGHT                    32
#define THEME_SIZE_CONTROL_MIN_WIDTH                 96
#define THEME_SIZE_CONTROL_PADDING_X                 12
#define THEME_SIZE_DESKTOP_CELL_HEIGHT               86
#define THEME_SIZE_DESKTOP_CELL_LARGE_HEIGHT         132
#define THEME_SIZE_DESKTOP_CELL_LARGE_WIDTH          120
#define THEME_SIZE_DESKTOP_CELL_SMALL_HEIGHT         70
#define THEME_SIZE_DESKTOP_CELL_SMALL_WIDTH          64
#define THEME_SIZE_DESKTOP_CELL_WIDTH                76
#define THEME_SIZE_DESKTOP_ICON                      48
#define THEME_SIZE_DESKTOP_ICON_LARGE                96
#define THEME_SIZE_DESKTOP_ICON_SMALL                32
#define THEME_SIZE_DESKTOP_MARGIN                    8
#define THEME_SIZE_DIALOG_FOOTER_HEIGHT              80
#define THEME_SIZE_DIALOG_MAX_WIDTH                  548
#define THEME_SIZE_DIALOG_MIN_WIDTH                  320
#define THEME_SIZE_DIALOG_PADDING                    24
#define THEME_SIZE_EXPLORER_HEADER_HEIGHT            32
#define THEME_SIZE_EXPLORER_TILE_WIDTH               96
#define THEME_SIZE_FLYOUT_RISE                       12
#define THEME_SIZE_FLYOUT_WIDTH                      360
#define THEME_SIZE_KEYPAD_BUTTON_MIN                 40
#define THEME_SIZE_LIST_ITEM_HEIGHT                  32
#define THEME_SIZE_LOCK_CLOCK                        96
#define THEME_SIZE_LOGIN_AVATAR                      192
#define THEME_SIZE_LOGIN_FIELD_WIDTH                 296
#define THEME_SIZE_MAGNIFIER_LENS_HEIGHT             300
#define THEME_SIZE_MAGNIFIER_LENS_WIDTH              400
#define THEME_SIZE_MESSAGE_ICON                      32
#define THEME_SIZE_NAV_ITEM_HEIGHT                   36
#define THEME_SIZE_NAV_PANE_WIDTH                    280
#define THEME_SIZE_OSD_HEIGHT                        48
#define THEME_SIZE_OSD_WIDTH                         196
#define THEME_SIZE_PROGRESS_BAR                      3
#define THEME_SIZE_PROGRESS_TRACK                    1
#define THEME_SIZE_RADIO                             20
#define THEME_SIZE_RADIO_DOT                         12
#define THEME_SIZE_RESIZE_MARGIN                     5
#define THEME_SIZE_SCROLLBAR_COLLAPSED               2
#define THEME_SIZE_SCROLLBAR_EXPANDED                6
#define THEME_SIZE_SELECTION_PILL_HEIGHT             16
#define THEME_SIZE_SELECTION_PILL_WIDTH              3
#define THEME_SIZE_SETTINGS_CARD_MIN_HEIGHT          64
#define THEME_SIZE_SHIELD_GLYPH                      16
#define THEME_SIZE_SHORTCUT_OVERLAY_RATIO_PCT        33
#define THEME_SIZE_SHOW_DESKTOP_WIDTH                8
#define THEME_SIZE_SLIDER_THUMB                      20
#define THEME_SIZE_SLIDER_THUMB_INNER                12
#define THEME_SIZE_SLIDER_TRACK                      4
#define THEME_SIZE_SNAP_FLYOUT_TILE                  72
#define THEME_SIZE_SNIP_TOOLBAR_HEIGHT               48
#define THEME_SIZE_START_FOOTER_HEIGHT               64
#define THEME_SIZE_START_HEIGHT                      720
#define THEME_SIZE_START_OFFSET_BOTTOM               12
#define THEME_SIZE_START_PINNED_COLS                 6
#define THEME_SIZE_START_PINNED_ROWS                 3
#define THEME_SIZE_START_SEARCH_HEIGHT               36
#define THEME_SIZE_START_SLIDE                       48
#define THEME_SIZE_START_TILE_HEIGHT                 84
#define THEME_SIZE_START_TILE_ICON                   32
#define THEME_SIZE_START_TILE_WIDTH                  96
#define THEME_SIZE_START_WIDTH                       640
#define THEME_SIZE_STATUS_BAR_HEIGHT                 24
#define THEME_SIZE_TAB_HEIGHT                        32
#define THEME_SIZE_TASKBAR_BUTTON                    40
#define THEME_SIZE_TASKBAR_GAP                       4
#define THEME_SIZE_TASKBAR_HEIGHT                    48
#define THEME_SIZE_TASKBAR_ICON                      24
#define THEME_SIZE_TASKBAR_INDICATOR_HEIGHT          3
#define THEME_SIZE_TASKBAR_INDICATOR_WIDTH_ACTIVE    16
#define THEME_SIZE_TASKBAR_INDICATOR_WIDTH_IDLE      6
#define THEME_SIZE_TASKBAR_PREVIEW_HEIGHT            120
#define THEME_SIZE_TASKBAR_PREVIEW_WIDTH             200
#define THEME_SIZE_TEXT_BOX_UNDERLINE                1
#define THEME_SIZE_TEXT_BOX_UNDERLINE_FOCUSED        2
#define THEME_SIZE_TOAST_GAP                         12
#define THEME_SIZE_TOAST_WIDTH                       364
#define THEME_SIZE_TOGGLE_HEIGHT                     20
#define THEME_SIZE_TOGGLE_KNOB                       12
#define THEME_SIZE_TOGGLE_KNOB_HOVER                 14
#define THEME_SIZE_TOGGLE_WIDTH                      40
#define THEME_SIZE_TOOLTIP_MAX_WIDTH                 320
#define THEME_SIZE_TRAY_CLOCK_WIDTH                  76
#define THEME_SIZE_WINDOW_BORDER                     1
#define THEME_SIZE_WINDOW_OPEN_SCALE_PCT             96

/* ---- radius ---- */
#define THEME_RADIUS_CARD                            8
#define THEME_RADIUS_CHECK_BOX                       4
#define THEME_RADIUS_CONTROL                         4
#define THEME_RADIUS_DIALOG                          8
#define THEME_RADIUS_OVERLAY                         8
#define THEME_RADIUS_SEARCH_BOX                      18
#define THEME_RADIUS_START_TILE                      4
#define THEME_RADIUS_TASKBAR_BUTTON                  4
#define THEME_RADIUS_TOGGLE                          10
#define THEME_RADIUS_TOOLTIP                         4
#define THEME_RADIUS_WINDOW                          8

/* ---- spacing ---- */
#define THEME_SPACE_L                                16
#define THEME_SPACE_M                                12
#define THEME_SPACE_S                                8
#define THEME_SPACE_XL                               24
#define THEME_SPACE_XS                               4
#define THEME_SPACE_XXL                              32
#define THEME_SPACE_XXS                              2

/* ---- type ramp ---- */
#define THEME_TYPE_BODY_SIZE                         14
#define THEME_TYPE_BODY_LINE                         20
#define THEME_TYPE_BODY_WEIGHT                       400
#define THEME_TYPE_BODY_LARGE_SIZE                   18
#define THEME_TYPE_BODY_LARGE_LINE                   24
#define THEME_TYPE_BODY_LARGE_WEIGHT                 400
#define THEME_TYPE_BODY_STRONG_SIZE                  14
#define THEME_TYPE_BODY_STRONG_LINE                  20
#define THEME_TYPE_BODY_STRONG_WEIGHT                600
#define THEME_TYPE_CAPTION_SIZE                      12
#define THEME_TYPE_CAPTION_LINE                      16
#define THEME_TYPE_CAPTION_WEIGHT                    400
#define THEME_TYPE_DISPLAY_SIZE                      68
#define THEME_TYPE_DISPLAY_LINE                      92
#define THEME_TYPE_DISPLAY_WEIGHT                    600
#define THEME_TYPE_SUBTITLE_SIZE                     20
#define THEME_TYPE_SUBTITLE_LINE                     28
#define THEME_TYPE_SUBTITLE_WEIGHT                   600
#define THEME_TYPE_TITLE_SIZE                        28
#define THEME_TYPE_TITLE_LINE                        36
#define THEME_TYPE_TITLE_WEIGHT                      600
#define THEME_TYPE_TITLE_LARGE_SIZE                  40
#define THEME_TYPE_TITLE_LARGE_LINE                  52
#define THEME_TYPE_TITLE_LARGE_WEIGHT                600

/* ---- elevation: [offset_y, blur, alpha] for gfx_drop_shadow ---- */
#define THEME_ELEV_CARD_Y                            2
#define THEME_ELEV_CARD_BLUR                         4
#define THEME_ELEV_CARD_ALPHA                        24
#define THEME_ELEV_CONTROL_Y                         1
#define THEME_ELEV_CONTROL_BLUR                      2
#define THEME_ELEV_CONTROL_ALPHA                     20
#define THEME_ELEV_FLYOUT_Y                          8
#define THEME_ELEV_FLYOUT_BLUR                       16
#define THEME_ELEV_FLYOUT_ALPHA                      56
#define THEME_ELEV_START_Y                           16
#define THEME_ELEV_START_BLUR                        32
#define THEME_ELEV_START_ALPHA                       72
#define THEME_ELEV_TOOLTIP_Y                         4
#define THEME_ELEV_TOOLTIP_BLUR                      8
#define THEME_ELEV_TOOLTIP_ALPHA                     36
#define THEME_ELEV_WINDOW_ACTIVE_Y                   16
#define THEME_ELEV_WINDOW_ACTIVE_BLUR                32
#define THEME_ELEV_WINDOW_ACTIVE_ALPHA               94
#define THEME_ELEV_WINDOW_INACTIVE_Y                 8
#define THEME_ELEV_WINDOW_INACTIVE_BLUR              16
#define THEME_ELEV_WINDOW_INACTIVE_ALPHA             48

/* ---- motion (ms) ---- */
#define THEME_MOTION_FAST_MS                         83
#define THEME_MOTION_FLYOUT_OPEN_MS                  167
#define THEME_MOTION_NORMAL_MS                       167
#define THEME_MOTION_PEEK_DELAY_MS                   500
#define THEME_MOTION_SLOW_MS                         250
#define THEME_MOTION_SNAP_HOVER_DELAY_MS             500
#define THEME_MOTION_START_CLOSE_MS                  167
#define THEME_MOTION_START_OPEN_MS                   250
#define THEME_MOTION_TASKBAR_PREVIEW_DELAY_MS        400
#define THEME_MOTION_TOAST_DWELL_MS                  5000
#define THEME_MOTION_TOAST_IN_MS                     250
#define THEME_MOTION_TOOLTIP_DELAY_MS                400

#endif /* DESKTOP_THEME_TOKENS_H */
